// Code generated by MockGen. DO NOT EDIT.
// Source: delivery_order_repository.go
//
// Generated by: mockgen -source=delivery_order_repository.go -destination=../../mocks/repomock/mock_delivery_order_repository.go -package=repomock

package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/delivery-order-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryOrderRepositoryInterface is a mock of DeliveryOrderRepositoryInterface interface.
type MockDeliveryOrderRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryOrderRepositoryInterfaceMockRecorder
}

// MockDeliveryOrderRepositoryInterfaceMockRecorder is the mock recorder for MockDeliveryOrderRepositoryInterface.
type MockDeliveryOrderRepositoryInterfaceMockRecorder struct {
	mock *MockDeliveryOrderRepositoryInterface
}

// NewMockDeliveryOrderRepositoryInterface creates a new mock instance.
func NewMockDeliveryOrderRepositoryInterface(ctrl *gomock.Controller) *MockDeliveryOrderRepositoryInterface {
	mock := &MockDeliveryOrderRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockDeliveryOrderRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryOrderRepositoryInterface) EXPECT() *MockDeliveryOrderRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) CreateOrder(ctx context.Context, o *repository.DeliveryOrder, pkg *repository.DeliveryPackage) (*repository.DeliveryOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, o, pkg)
	ret0, _ := ret[0].(*repository.DeliveryOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) CreateOrder(ctx, o, pkg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).CreateOrder), ctx, o, pkg)
}

// GetOrderByID mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) GetOrderByID(ctx context.Context, orderID string) (*repository.DeliveryOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, orderID)
	ret0, _ := ret[0].(*repository.DeliveryOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) GetOrderByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).GetOrderByID), ctx, orderID)
}

// GetPackageByOrderID mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) GetPackageByOrderID(ctx context.Context, orderID string) (*repository.DeliveryPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPackageByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*repository.DeliveryPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPackageByOrderID indicates an expected call of GetPackageByOrderID.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) GetPackageByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPackageByOrderID", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).GetPackageByOrderID), ctx, orderID)
}

// GetActiveOrderByUserID mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) GetActiveOrderByUserID(ctx context.Context, userID string) (*repository.DeliveryOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrderByUserID", ctx, userID)
	ret0, _ := ret[0].(*repository.DeliveryOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrderByUserID indicates an expected call of GetActiveOrderByUserID.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) GetActiveOrderByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrderByUserID", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).GetActiveOrderByUserID), ctx, userID)
}

// ListUserHistory mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) ListUserHistory(ctx context.Context, userID string, f repository.HistoryFilter) ([]*repository.DeliveryOrder, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserHistory", ctx, userID, f)
	ret0, _ := ret[0].([]*repository.DeliveryOrder)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserHistory indicates an expected call of ListUserHistory.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) ListUserHistory(ctx, userID, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserHistory", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).ListUserHistory), ctx, userID, f)
}

// UpdateStatus mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) UpdateStatus(ctx context.Context, orderID, fromStatus, toStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, orderID, fromStatus, toStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) UpdateStatus(ctx, orderID, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).UpdateStatus), ctx, orderID, fromStatus, toStatus)
}

// AssignDriver mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) AssignDriver(ctx context.Context, orderID, driverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDriver", ctx, orderID, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignDriver indicates an expected call of AssignDriver.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) AssignDriver(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDriver", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).AssignDriver), ctx, orderID, driverID)
}

// SetCancelled mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) SetCancelled(ctx context.Context, orderID, reason, cancelledBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCancelled", ctx, orderID, reason, cancelledBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCancelled indicates an expected call of SetCancelled.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) SetCancelled(ctx, orderID, reason, cancelledBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCancelled", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).SetCancelled), ctx, orderID, reason, cancelledBy)
}

// SetFareFinal mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) SetFareFinal(ctx context.Context, orderID string, fareFinal float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFareFinal", ctx, orderID, fareFinal)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFareFinal indicates an expected call of SetFareFinal.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) SetFareFinal(ctx, orderID, fareFinal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFareFinal", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).SetFareFinal), ctx, orderID, fareFinal)
}

// SetPickupProof mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) SetPickupProof(ctx context.Context, orderID, photoURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPickupProof", ctx, orderID, photoURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPickupProof indicates an expected call of SetPickupProof.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) SetPickupProof(ctx, orderID, photoURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPickupProof", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).SetPickupProof), ctx, orderID, photoURL)
}

// SetDeliveryDetails mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) SetDeliveryDetails(ctx context.Context, orderID, photoURL string, distanceKm float64, durationMin int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDeliveryDetails", ctx, orderID, photoURL, distanceKm, durationMin)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDeliveryDetails indicates an expected call of SetDeliveryDetails.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) SetDeliveryDetails(ctx, orderID, photoURL, distanceKm, durationMin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeliveryDetails", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).SetDeliveryDetails), ctx, orderID, photoURL, distanceKm, durationMin)
}

// InsertStateLog mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) InsertStateLog(ctx context.Context, log *repository.DeliveryStateLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertStateLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertStateLog indicates an expected call of InsertStateLog.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) InsertStateLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertStateLog", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).InsertStateLog), ctx, log)
}

// ListStateLogs mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) ListStateLogs(ctx context.Context, orderID string) ([]*repository.DeliveryStateLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStateLogs", ctx, orderID)
	ret0, _ := ret[0].([]*repository.DeliveryStateLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStateLogs indicates an expected call of ListStateLogs.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) ListStateLogs(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStateLogs", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).ListStateLogs), ctx, orderID)
}

// UpsertFareBreakdown mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) UpsertFareBreakdown(ctx context.Context, fb *repository.DeliveryFareBreakdown) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFareBreakdown", ctx, fb)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFareBreakdown indicates an expected call of UpsertFareBreakdown.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) UpsertFareBreakdown(ctx, fb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFareBreakdown", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).UpsertFareBreakdown), ctx, fb)
}

// GetFareBreakdown mocks base method.
func (m *MockDeliveryOrderRepositoryInterface) GetFareBreakdown(ctx context.Context, orderID string) (*repository.DeliveryFareBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareBreakdown", ctx, orderID)
	ret0, _ := ret[0].(*repository.DeliveryFareBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFareBreakdown indicates an expected call of GetFareBreakdown.
func (mr *MockDeliveryOrderRepositoryInterfaceMockRecorder) GetFareBreakdown(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareBreakdown", reflect.TypeOf((*MockDeliveryOrderRepositoryInterface)(nil).GetFareBreakdown), ctx, orderID)
}
