// Code generated by MockGen. DO NOT EDIT.
// Source: rating_service.go
//
// Generated by this command:
//
//	mockgen -source=rating_service.go -destination=../../mocks/rating_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/rating-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockRatingServiceInterface is a mock of RatingServiceInterface interface.
type MockRatingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRatingServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockRatingServiceInterfaceMockRecorder is the mock recorder for MockRatingServiceInterface.
type MockRatingServiceInterfaceMockRecorder struct {
	mock *MockRatingServiceInterface
}

// NewMockRatingServiceInterface creates a new mock instance.
func NewMockRatingServiceInterface(ctrl *gomock.Controller) *MockRatingServiceInterface {
	mock := &MockRatingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockRatingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingServiceInterface) EXPECT() *MockRatingServiceInterfaceMockRecorder {
	return m.recorder
}

// BatchGetAverageRatings mocks base method.
func (m *MockRatingServiceInterface) BatchGetAverageRatings(ctx context.Context, req service.BatchAverageRequest) (*service.BatchAverageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetAverageRatings", ctx, req)
	ret0, _ := ret[0].(*service.BatchAverageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetAverageRatings indicates an expected call of BatchGetAverageRatings.
func (mr *MockRatingServiceInterfaceMockRecorder) BatchGetAverageRatings(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetAverageRatings", reflect.TypeOf((*MockRatingServiceInterface)(nil).BatchGetAverageRatings), ctx, req)
}

// GetAverageRating mocks base method.
func (m *MockRatingServiceInterface) GetAverageRating(ctx context.Context, subjectType, subjectID string) (*service.AverageRatingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageRating", ctx, subjectType, subjectID)
	ret0, _ := ret[0].(*service.AverageRatingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageRating indicates an expected call of GetAverageRating.
func (mr *MockRatingServiceInterfaceMockRecorder) GetAverageRating(ctx, subjectType, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRating", reflect.TypeOf((*MockRatingServiceInterface)(nil).GetAverageRating), ctx, subjectType, subjectID)
}

// GetDriverScore mocks base method.
func (m *MockRatingServiceInterface) GetDriverScore(ctx context.Context, driverID string) (*service.AverageRatingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverScore", ctx, driverID)
	ret0, _ := ret[0].(*service.AverageRatingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverScore indicates an expected call of GetDriverScore.
func (mr *MockRatingServiceInterfaceMockRecorder) GetDriverScore(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverScore", reflect.TypeOf((*MockRatingServiceInterface)(nil).GetDriverScore), ctx, driverID)
}

// GetMyGivenRatings mocks base method.
func (m *MockRatingServiceInterface) GetMyGivenRatings(ctx context.Context, userID string, page, limit int) (*service.RatingListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyGivenRatings", ctx, userID, page, limit)
	ret0, _ := ret[0].(*service.RatingListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyGivenRatings indicates an expected call of GetMyGivenRatings.
func (mr *MockRatingServiceInterfaceMockRecorder) GetMyGivenRatings(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyGivenRatings", reflect.TypeOf((*MockRatingServiceInterface)(nil).GetMyGivenRatings), ctx, userID, page, limit)
}

// GetMyReceivedRatings mocks base method.
func (m *MockRatingServiceInterface) GetMyReceivedRatings(ctx context.Context, userID string, page, limit int) (*service.RatingListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyReceivedRatings", ctx, userID, page, limit)
	ret0, _ := ret[0].(*service.RatingListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyReceivedRatings indicates an expected call of GetMyReceivedRatings.
func (mr *MockRatingServiceInterfaceMockRecorder) GetMyReceivedRatings(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyReceivedRatings", reflect.TypeOf((*MockRatingServiceInterface)(nil).GetMyReceivedRatings), ctx, userID, page, limit)
}

// GetOrderRatings mocks base method.
func (m *MockRatingServiceInterface) GetOrderRatings(ctx context.Context, orderID string) (*service.OrderRatingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderRatings", ctx, orderID)
	ret0, _ := ret[0].(*service.OrderRatingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderRatings indicates an expected call of GetOrderRatings.
func (mr *MockRatingServiceInterfaceMockRecorder) GetOrderRatings(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderRatings", reflect.TypeOf((*MockRatingServiceInterface)(nil).GetOrderRatings), ctx, orderID)
}

// GetRatings mocks base method.
func (m *MockRatingServiceInterface) GetRatings(ctx context.Context, subjectType, subjectID string, page, limit int) (*service.RatingListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatings", ctx, subjectType, subjectID, page, limit)
	ret0, _ := ret[0].(*service.RatingListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatings indicates an expected call of GetRatings.
func (mr *MockRatingServiceInterfaceMockRecorder) GetRatings(ctx, subjectType, subjectID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatings", reflect.TypeOf((*MockRatingServiceInterface)(nil).GetRatings), ctx, subjectType, subjectID, page, limit)
}

// SubmitRating mocks base method.
func (m *MockRatingServiceInterface) SubmitRating(ctx context.Context, userID string, req service.SubmitRatingRequest) (*service.RatingSubmitResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRating", ctx, userID, req)
	ret0, _ := ret[0].(*service.RatingSubmitResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitRating indicates an expected call of SubmitRating.
func (mr *MockRatingServiceInterfaceMockRecorder) SubmitRating(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRating", reflect.TypeOf((*MockRatingServiceInterface)(nil).SubmitRating), ctx, userID, req)
}
