// Code generated by MockGen. DO NOT EDIT.
// Source: push_repository.go
//
// Generated by this command:
//
//	mockgen -source=push_repository.go -destination=../../mocks/repomock/mock_push_repository.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/push-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPushRepositoryInterface is a mock of PushRepositoryInterface interface.
type MockPushRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPushRepositoryInterfaceMockRecorder is the mock recorder for MockPushRepositoryInterface.
type MockPushRepositoryInterfaceMockRecorder struct {
	mock *MockPushRepositoryInterface
}

// NewMockPushRepositoryInterface creates a new mock instance.
func NewMockPushRepositoryInterface(ctrl *gomock.Controller) *MockPushRepositoryInterface {
	mock := &MockPushRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPushRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushRepositoryInterface) EXPECT() *MockPushRepositoryInterfaceMockRecorder {
	return m.recorder
}

// BatchSend mocks base method.
func (m *MockPushRepositoryInterface) BatchSend(ctx context.Context, tokens []string, platform string, payload repository.PushPayload) (*repository.BatchDeliveryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSend", ctx, tokens, platform, payload)
	ret0, _ := ret[0].(*repository.BatchDeliveryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchSend indicates an expected call of BatchSend.
func (mr *MockPushRepositoryInterfaceMockRecorder) BatchSend(ctx, tokens, platform, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSend", reflect.TypeOf((*MockPushRepositoryInterface)(nil).BatchSend), ctx, tokens, platform, payload)
}

// GetRetryMessage mocks base method.
func (m *MockPushRepositoryInterface) GetRetryMessage(ctx context.Context, messageID string) (*repository.RetryMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetryMessage", ctx, messageID)
	ret0, _ := ret[0].(*repository.RetryMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRetryMessage indicates an expected call of GetRetryMessage.
func (mr *MockPushRepositoryInterfaceMockRecorder) GetRetryMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetryMessage", reflect.TypeOf((*MockPushRepositoryInterface)(nil).GetRetryMessage), ctx, messageID)
}

// IsTokenInvalid mocks base method.
func (m *MockPushRepositoryInterface) IsTokenInvalid(ctx context.Context, tokenHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenInvalid", ctx, tokenHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenInvalid indicates an expected call of IsTokenInvalid.
func (mr *MockPushRepositoryInterfaceMockRecorder) IsTokenInvalid(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenInvalid", reflect.TypeOf((*MockPushRepositoryInterface)(nil).IsTokenInvalid), ctx, tokenHash)
}

// MarkTokenInvalid mocks base method.
func (m *MockPushRepositoryInterface) MarkTokenInvalid(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTokenInvalid", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTokenInvalid indicates an expected call of MarkTokenInvalid.
func (mr *MockPushRepositoryInterfaceMockRecorder) MarkTokenInvalid(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTokenInvalid", reflect.TypeOf((*MockPushRepositoryInterface)(nil).MarkTokenInvalid), ctx, tokenHash)
}

// SaveRetryMessage mocks base method.
func (m *MockPushRepositoryInterface) SaveRetryMessage(ctx context.Context, messageID string, msg *repository.RetryMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRetryMessage", ctx, messageID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRetryMessage indicates an expected call of SaveRetryMessage.
func (mr *MockPushRepositoryInterfaceMockRecorder) SaveRetryMessage(ctx, messageID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRetryMessage", reflect.TypeOf((*MockPushRepositoryInterface)(nil).SaveRetryMessage), ctx, messageID, msg)
}

// Send mocks base method.
func (m *MockPushRepositoryInterface) Send(ctx context.Context, token, platform string, payload repository.PushPayload) (*repository.PushDeliveryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, token, platform, payload)
	ret0, _ := ret[0].(*repository.PushDeliveryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockPushRepositoryInterfaceMockRecorder) Send(ctx, token, platform, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockPushRepositoryInterface)(nil).Send), ctx, token, platform, payload)
}

// SendToTopic mocks base method.
func (m *MockPushRepositoryInterface) SendToTopic(ctx context.Context, topic string, payload repository.PushPayload) (*repository.PushDeliveryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToTopic", ctx, topic, payload)
	ret0, _ := ret[0].(*repository.PushDeliveryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendToTopic indicates an expected call of SendToTopic.
func (mr *MockPushRepositoryInterfaceMockRecorder) SendToTopic(ctx, topic, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToTopic", reflect.TypeOf((*MockPushRepositoryInterface)(nil).SendToTopic), ctx, topic, payload)
}

// SubscribeToTopic mocks base method.
func (m *MockPushRepositoryInterface) SubscribeToTopic(ctx context.Context, topic string, tokens []string) (*repository.TopicResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToTopic", ctx, topic, tokens)
	ret0, _ := ret[0].(*repository.TopicResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToTopic indicates an expected call of SubscribeToTopic.
func (mr *MockPushRepositoryInterfaceMockRecorder) SubscribeToTopic(ctx, topic, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToTopic", reflect.TypeOf((*MockPushRepositoryInterface)(nil).SubscribeToTopic), ctx, topic, tokens)
}

// UnsubscribeFromTopic mocks base method.
func (m *MockPushRepositoryInterface) UnsubscribeFromTopic(ctx context.Context, topic string, tokens []string) (*repository.TopicResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeFromTopic", ctx, topic, tokens)
	ret0, _ := ret[0].(*repository.TopicResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsubscribeFromTopic indicates an expected call of UnsubscribeFromTopic.
func (mr *MockPushRepositoryInterfaceMockRecorder) UnsubscribeFromTopic(ctx, topic, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeFromTopic", reflect.TypeOf((*MockPushRepositoryInterface)(nil).UnsubscribeFromTopic), ctx, topic, tokens)
}
