// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	context "context"
	reflect "reflect"

	cache "github.com/zicofarry/clay-app/backend/services/geo-service/internal/cache"
	service "github.com/zicofarry/clay-app/backend/services/geo-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

type MockGeoServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGeoServiceInterfaceMockRecorder
}
type MockGeoServiceInterfaceMockRecorder struct{ mock *MockGeoServiceInterface }

func NewMockGeoServiceInterface(ctrl *gomock.Controller) *MockGeoServiceInterface {
	m := &MockGeoServiceInterface{ctrl: ctrl}
	m.recorder = &MockGeoServiceInterfaceMockRecorder{m}
	return m
}
func (m *MockGeoServiceInterface) EXPECT() *MockGeoServiceInterfaceMockRecorder { return m.recorder }

func (m *MockGeoServiceInterface) UpdateDriverLocation(ctx context.Context, driverID string, req *service.UpdateLocationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverLocation", ctx, driverID, req)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockGeoServiceInterfaceMockRecorder) UpdateDriverLocation(ctx, driverID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverLocation", reflect.TypeOf((*MockGeoServiceInterface)(nil).UpdateDriverLocation), ctx, driverID, req)
}

func (m *MockGeoServiceInterface) GetDriverLocation(ctx context.Context, driverID string) (*cache.DriverLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverLocation", ctx, driverID)
	ret0, _ := ret[0].(*cache.DriverLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) GetDriverLocation(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverLocation", reflect.TypeOf((*MockGeoServiceInterface)(nil).GetDriverLocation), ctx, driverID)
}

func (m *MockGeoServiceInterface) FindNearbyDrivers(ctx context.Context, lat, lng, radiusKm float64, serviceType string, limit int) (*service.NearbyDriversResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearbyDrivers", ctx, lat, lng, radiusKm, serviceType, limit)
	ret0, _ := ret[0].(*service.NearbyDriversResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) FindNearbyDrivers(ctx, lat, lng, radiusKm, serviceType, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearbyDrivers", reflect.TypeOf((*MockGeoServiceInterface)(nil).FindNearbyDrivers), ctx, lat, lng, radiusKm, serviceType, limit)
}

func (m *MockGeoServiceInterface) EstimateRoute(ctx context.Context, req *service.RouteEstimateRequest) (*service.RouteEstimateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateRoute", ctx, req)
	ret0, _ := ret[0].(*service.RouteEstimateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) EstimateRoute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateRoute", reflect.TypeOf((*MockGeoServiceInterface)(nil).EstimateRoute), ctx, req)
}

func (m *MockGeoServiceInterface) GetPolyline(ctx context.Context, oLat, oLng, dLat, dLng float64) (*service.PolylineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolyline", ctx, oLat, oLng, dLat, dLng)
	ret0, _ := ret[0].(*service.PolylineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) GetPolyline(ctx, oLat, oLng, dLat, dLng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolyline", reflect.TypeOf((*MockGeoServiceInterface)(nil).GetPolyline), ctx, oLat, oLng, dLat, dLng)
}

func (m *MockGeoServiceInterface) GetRouting(ctx context.Context, oLat, oLng, dLat, dLng float64, mode string) (*service.RoutingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouting", ctx, oLat, oLng, dLat, dLng, mode)
	ret0, _ := ret[0].(*service.RoutingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) GetRouting(ctx, oLat, oLng, dLat, dLng, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouting", reflect.TypeOf((*MockGeoServiceInterface)(nil).GetRouting), ctx, oLat, oLng, dLat, dLng, mode)
}

func (m *MockGeoServiceInterface) SnapToRoad(ctx context.Context, req *service.SnappingRequest) (*service.SnappingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapToRoad", ctx, req)
	ret0, _ := ret[0].(*service.SnappingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) SnapToRoad(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapToRoad", reflect.TypeOf((*MockGeoServiceInterface)(nil).SnapToRoad), ctx, req)
}

func (m *MockGeoServiceInterface) GetTraffic(ctx context.Context, oLat, oLng, dLat, dLng float64) (*service.TrafficResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraffic", ctx, oLat, oLng, dLat, dLng)
	ret0, _ := ret[0].(*service.TrafficResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) GetTraffic(ctx, oLat, oLng, dLat, dLng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraffic", reflect.TypeOf((*MockGeoServiceInterface)(nil).GetTraffic), ctx, oLat, oLng, dLat, dLng)
}

func (m *MockGeoServiceInterface) ForwardGeocode(ctx context.Context, req *service.ForwardGeocodeRequest) (*service.ForwardGeocodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForwardGeocode", ctx, req)
	ret0, _ := ret[0].(*service.ForwardGeocodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) ForwardGeocode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardGeocode", reflect.TypeOf((*MockGeoServiceInterface)(nil).ForwardGeocode), ctx, req)
}

func (m *MockGeoServiceInterface) ReverseGeocode(ctx context.Context, req *service.ReverseGeocodeRequest) (*service.GeocodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReverseGeocode", ctx, req)
	ret0, _ := ret[0].(*service.GeocodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) ReverseGeocode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReverseGeocode", reflect.TypeOf((*MockGeoServiceInterface)(nil).ReverseGeocode), ctx, req)
}

func (m *MockGeoServiceInterface) CalculateDistance(ctx context.Context, oLat, oLng, dLat, dLng float64) (*service.DistanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateDistance", ctx, oLat, oLng, dLat, dLng)
	ret0, _ := ret[0].(*service.DistanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) CalculateDistance(ctx, oLat, oLng, dLat, dLng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateDistance", reflect.TypeOf((*MockGeoServiceInterface)(nil).CalculateDistance), ctx, oLat, oLng, dLat, dLng)
}

func (m *MockGeoServiceInterface) PlacesAutocomplete(ctx context.Context, query string, lat, lng *float64, radiusM int) (*service.AutocompleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlacesAutocomplete", ctx, query, lat, lng, radiusM)
	ret0, _ := ret[0].(*service.AutocompleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) PlacesAutocomplete(ctx, query, lat, lng, radiusM any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlacesAutocomplete", reflect.TypeOf((*MockGeoServiceInterface)(nil).PlacesAutocomplete), ctx, query, lat, lng, radiusM)
}

func (m *MockGeoServiceInterface) GetPlaceDetail(ctx context.Context, placeID string) (*service.PlaceDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaceDetail", ctx, placeID)
	ret0, _ := ret[0].(*service.PlaceDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) GetPlaceDetail(ctx, placeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaceDetail", reflect.TypeOf((*MockGeoServiceInterface)(nil).GetPlaceDetail), ctx, placeID)
}

func (m *MockGeoServiceInterface) CheckGeofence(ctx context.Context, req *service.GeofenceCheckRequest) (*service.GeofenceCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckGeofence", ctx, req)
	ret0, _ := ret[0].(*service.GeofenceCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) CheckGeofence(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGeofence", reflect.TypeOf((*MockGeoServiceInterface)(nil).CheckGeofence), ctx, req)
}

func (m *MockGeoServiceInterface) BatchGetDriverLocations(ctx context.Context, req *service.BatchLocationRequest) (map[string]*cache.DriverLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetDriverLocations", ctx, req)
	ret0, _ := ret[0].(map[string]*cache.DriverLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) BatchGetDriverLocations(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetDriverLocations", reflect.TypeOf((*MockGeoServiceInterface)(nil).BatchGetDriverLocations), ctx, req)
}

func (m *MockGeoServiceInterface) GetDriverETA(ctx context.Context, driverID, orderID string) (*service.LiveEtaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverETA", ctx, driverID, orderID)
	ret0, _ := ret[0].(*service.LiveEtaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) GetDriverETA(ctx, driverID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverETA", reflect.TypeOf((*MockGeoServiceInterface)(nil).GetDriverETA), ctx, driverID, orderID)
}

func (m *MockGeoServiceInterface) UpdateDriverETA(ctx context.Context, driverID, orderID string, req *service.UpdateEtaRequest) (*service.LiveEtaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverETA", ctx, driverID, orderID, req)
	ret0, _ := ret[0].(*service.LiveEtaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoServiceInterfaceMockRecorder) UpdateDriverETA(ctx, driverID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverETA", reflect.TypeOf((*MockGeoServiceInterface)(nil).UpdateDriverETA), ctx, driverID, orderID, req)
}
