// Code generated by MockGen. DO NOT EDIT.
// Source: payment_repository.go

package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/payment-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

type MockPaymentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryInterfaceMockRecorder
}

type MockPaymentRepositoryInterfaceMockRecorder struct {
	mock *MockPaymentRepositoryInterface
}

func NewMockPaymentRepositoryInterface(ctrl *gomock.Controller) *MockPaymentRepositoryInterface {
	mock := &MockPaymentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryInterfaceMockRecorder{mock}
	return mock
}

func (m *MockPaymentRepositoryInterface) EXPECT() *MockPaymentRepositoryInterfaceMockRecorder {
	return m.recorder
}

func (m *MockPaymentRepositoryInterface) CreatePaymentMethod(ctx context.Context, pm *repository.PaymentMethod) (*repository.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentMethod", ctx, pm)
	ret0, _ := ret[0].(*repository.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) CreatePaymentMethod(ctx, pm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentMethod", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).CreatePaymentMethod), ctx, pm)
}

func (m *MockPaymentRepositoryInterface) ListPaymentMethods(ctx context.Context, userID string) ([]repository.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaymentMethods", ctx, userID)
	ret0, _ := ret[0].([]repository.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) ListPaymentMethods(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentMethods", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).ListPaymentMethods), ctx, userID)
}

func (m *MockPaymentRepositoryInterface) DeletePaymentMethod(ctx context.Context, userID, methodID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePaymentMethod", ctx, userID, methodID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) DeletePaymentMethod(ctx, userID, methodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentMethod", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).DeletePaymentMethod), ctx, userID, methodID)
}

func (m *MockPaymentRepositoryInterface) SetDefaultPaymentMethod(ctx context.Context, userID, methodID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultPaymentMethod", ctx, userID, methodID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) SetDefaultPaymentMethod(ctx, userID, methodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultPaymentMethod", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).SetDefaultPaymentMethod), ctx, userID, methodID)
}

func (m *MockPaymentRepositoryInterface) FindPaymentMethodByID(ctx context.Context, methodID string) (*repository.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPaymentMethodByID", ctx, methodID)
	ret0, _ := ret[0].(*repository.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) FindPaymentMethodByID(ctx, methodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPaymentMethodByID", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).FindPaymentMethodByID), ctx, methodID)
}

func (m *MockPaymentRepositoryInterface) CreateTransaction(ctx context.Context, tx *repository.Transaction) (*repository.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, tx)
	ret0, _ := ret[0].(*repository.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) CreateTransaction(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).CreateTransaction), ctx, tx)
}

func (m *MockPaymentRepositoryInterface) FindTransactionByID(ctx context.Context, id string) (*repository.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionByID", ctx, id)
	ret0, _ := ret[0].(*repository.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) FindTransactionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionByID", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).FindTransactionByID), ctx, id)
}

func (m *MockPaymentRepositoryInterface) ListTransactions(ctx context.Context, userID string, txType string, page, limit int) ([]repository.Transaction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, userID, txType, page, limit)
	ret0, _ := ret[0].([]repository.Transaction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) ListTransactions(ctx, userID, txType, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).ListTransactions), ctx, userID, txType, page, limit)
}

func (m *MockPaymentRepositoryInterface) UpdateTransactionStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) UpdateTransactionStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).UpdateTransactionStatus), ctx, id, status)
}

func (m *MockPaymentRepositoryInterface) FindTransactionByOrderID(ctx context.Context, orderID string) (*repository.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*repository.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) FindTransactionByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionByOrderID", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).FindTransactionByOrderID), ctx, orderID)
}

func (m *MockPaymentRepositoryInterface) CreateHold(ctx context.Context, hold *repository.Hold) (*repository.Hold, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHold", ctx, hold)
	ret0, _ := ret[0].(*repository.Hold)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) CreateHold(ctx, hold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHold", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).CreateHold), ctx, hold)
}

func (m *MockPaymentRepositoryInterface) FindHoldByID(ctx context.Context, id string) (*repository.Hold, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHoldByID", ctx, id)
	ret0, _ := ret[0].(*repository.Hold)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) FindHoldByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHoldByID", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).FindHoldByID), ctx, id)
}

func (m *MockPaymentRepositoryInterface) UpdateHoldStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHoldStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) UpdateHoldStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHoldStatus", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).UpdateHoldStatus), ctx, id, status)
}

func (m *MockPaymentRepositoryInterface) CreateRefund(ctx context.Context, refund *repository.Refund) (*repository.Refund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefund", ctx, refund)
	ret0, _ := ret[0].(*repository.Refund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) CreateRefund(ctx, refund any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefund", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).CreateRefund), ctx, refund)
}

func (m *MockPaymentRepositoryInterface) CreateSettlement(ctx context.Context, settlement *repository.Settlement) (*repository.Settlement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSettlement", ctx, settlement)
	ret0, _ := ret[0].(*repository.Settlement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) CreateSettlement(ctx, settlement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSettlement", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).CreateSettlement), ctx, settlement)
}

func (m *MockPaymentRepositoryInterface) SettlementExistsByOrderID(ctx context.Context, orderID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SettlementExistsByOrderID", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) SettlementExistsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SettlementExistsByOrderID", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).SettlementExistsByOrderID), ctx, orderID)
}

func (m *MockPaymentRepositoryInterface) CreateCodVerification(ctx context.Context, cv *repository.CodVerification) (*repository.CodVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCodVerification", ctx, cv)
	ret0, _ := ret[0].(*repository.CodVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) CreateCodVerification(ctx, cv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCodVerification", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).CreateCodVerification), ctx, cv)
}

func (m *MockPaymentRepositoryInterface) FindCodVerificationByID(ctx context.Context, id string) (*repository.CodVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCodVerificationByID", ctx, id)
	ret0, _ := ret[0].(*repository.CodVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) FindCodVerificationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCodVerificationByID", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).FindCodVerificationByID), ctx, id)
}

func (m *MockPaymentRepositoryInterface) UpdateCodVerification(ctx context.Context, cv *repository.CodVerification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCodVerification", ctx, cv)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPaymentRepositoryInterfaceMockRecorder) UpdateCodVerification(ctx, cv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCodVerification", reflect.TypeOf((*MockPaymentRepositoryInterface)(nil).UpdateCodVerification), ctx, cv)
}
