// Code generated by MockGen. DO NOT EDIT.
package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/pricing-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

type MockPricingRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPricingRepositoryInterfaceMockRecorder
}
type MockPricingRepositoryInterfaceMockRecorder struct{ mock *MockPricingRepositoryInterface }

func NewMockPricingRepositoryInterface(ctrl *gomock.Controller) *MockPricingRepositoryInterface {
	m := &MockPricingRepositoryInterface{ctrl: ctrl}
	m.recorder = &MockPricingRepositoryInterfaceMockRecorder{m}
	return m
}
func (m *MockPricingRepositoryInterface) EXPECT() *MockPricingRepositoryInterfaceMockRecorder {
	return m.recorder
}

func (m *MockPricingRepositoryInterface) GetFareRule(ctx context.Context, serviceType string, vehicleType *string, zoneID *string) (*repository.FareRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareRule", ctx, serviceType, vehicleType, zoneID)
	ret0, _ := ret[0].(*repository.FareRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingRepositoryInterfaceMockRecorder) GetFareRule(ctx, serviceType, vehicleType, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareRule", reflect.TypeOf((*MockPricingRepositoryInterface)(nil).GetFareRule), ctx, serviceType, vehicleType, zoneID)
}

func (m *MockPricingRepositoryInterface) CreateFareRule(ctx context.Context, rule *repository.FareRule) (*repository.FareRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFareRule", ctx, rule)
	ret0, _ := ret[0].(*repository.FareRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingRepositoryInterfaceMockRecorder) CreateFareRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFareRule", reflect.TypeOf((*MockPricingRepositoryInterface)(nil).CreateFareRule), ctx, rule)
}

func (m *MockPricingRepositoryInterface) ListFareRules(ctx context.Context) ([]repository.FareRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFareRules", ctx)
	ret0, _ := ret[0].([]repository.FareRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingRepositoryInterfaceMockRecorder) ListFareRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFareRules", reflect.TypeOf((*MockPricingRepositoryInterface)(nil).ListFareRules), ctx)
}
