// Code generated by MockGen. DO NOT EDIT.
// Source: food_order_service_interface.go
//
// Generated by: mockgen -source=food_order_service_interface.go -destination=../../mocks/mock_food_order_service.go -package=mocks

package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/zicofarry/clay-app/backend/services/food-order-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFoodOrderServiceInterface is a mock of FoodOrderServiceInterface interface.
type MockFoodOrderServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFoodOrderServiceInterfaceMockRecorder
}

// MockFoodOrderServiceInterfaceMockRecorder is the mock recorder for MockFoodOrderServiceInterface.
type MockFoodOrderServiceInterfaceMockRecorder struct {
	mock *MockFoodOrderServiceInterface
}

// NewMockFoodOrderServiceInterface creates a new mock instance.
func NewMockFoodOrderServiceInterface(ctrl *gomock.Controller) *MockFoodOrderServiceInterface {
	mock := &MockFoodOrderServiceInterface{ctrl: ctrl}
	mock.recorder = &MockFoodOrderServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoodOrderServiceInterface) EXPECT() *MockFoodOrderServiceInterfaceMockRecorder {
	return m.recorder
}

// EstimateFare mocks base method.
func (m *MockFoodOrderServiceInterface) EstimateFare(ctx context.Context, req model.FareEstimateRequest) (*model.FareEstimateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFare", ctx, req)
	ret0, _ := ret[0].(*model.FareEstimateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateFare indicates an expected call of EstimateFare.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) EstimateFare(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFare", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).EstimateFare), ctx, req)
}

// CreateOrder mocks base method.
func (m *MockFoodOrderServiceInterface) CreateOrder(ctx context.Context, userID string, req model.CreateFoodOrderRequest) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, req)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) CreateOrder(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).CreateOrder), ctx, userID, req)
}

// GetOrder mocks base method.
func (m *MockFoodOrderServiceInterface) GetOrder(ctx context.Context, orderID, callerID string) (*model.FoodOrder, []model.FoodOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, orderID, callerID)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].([]model.FoodOrderItem)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) GetOrder(ctx, orderID, callerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).GetOrder), ctx, orderID, callerID)
}

// GetActiveOrder mocks base method.
func (m *MockFoodOrderServiceInterface) GetActiveOrder(ctx context.Context, userID string) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrder", ctx, userID)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrder indicates an expected call of GetActiveOrder.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) GetActiveOrder(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrder", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).GetActiveOrder), ctx, userID)
}

// GetHistory mocks base method.
func (m *MockFoodOrderServiceInterface) GetHistory(ctx context.Context, userID, status string, page, limit int) ([]model.FoodOrder, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID, status, page, limit)
	ret0, _ := ret[0].([]model.FoodOrder)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) GetHistory(ctx, userID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).GetHistory), ctx, userID, status, page, limit)
}

// CancelOrder mocks base method.
func (m *MockFoodOrderServiceInterface) CancelOrder(ctx context.Context, orderID, userID string, req model.CancelOrderRequest) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, orderID, userID, req)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) CancelOrder(ctx, orderID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).CancelOrder), ctx, orderID, userID, req)
}

// MerchantConfirmOrder mocks base method.
func (m *MockFoodOrderServiceInterface) MerchantConfirmOrder(ctx context.Context, orderID, merchantUserID string, req model.MerchantConfirmRequest) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantConfirmOrder", ctx, orderID, merchantUserID, req)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MerchantConfirmOrder indicates an expected call of MerchantConfirmOrder.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) MerchantConfirmOrder(ctx, orderID, merchantUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantConfirmOrder", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).MerchantConfirmOrder), ctx, orderID, merchantUserID, req)
}

// MerchantRejectOrder mocks base method.
func (m *MockFoodOrderServiceInterface) MerchantRejectOrder(ctx context.Context, orderID string, req model.MerchantRejectRequest) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantRejectOrder", ctx, orderID, req)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MerchantRejectOrder indicates an expected call of MerchantRejectOrder.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) MerchantRejectOrder(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantRejectOrder", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).MerchantRejectOrder), ctx, orderID, req)
}

// MerchantUpdateStatus mocks base method.
func (m *MockFoodOrderServiceInterface) MerchantUpdateStatus(ctx context.Context, orderID string, req model.MerchantUpdateStatusRequest) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantUpdateStatus", ctx, orderID, req)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MerchantUpdateStatus indicates an expected call of MerchantUpdateStatus.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) MerchantUpdateStatus(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantUpdateStatus", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).MerchantUpdateStatus), ctx, orderID, req)
}

// MerchantListOrders mocks base method.
func (m *MockFoodOrderServiceInterface) MerchantListOrders(ctx context.Context, merchantID, status string, page, limit int) ([]model.FoodOrder, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantListOrders", ctx, merchantID, status, page, limit)
	ret0, _ := ret[0].([]model.FoodOrder)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MerchantListOrders indicates an expected call of MerchantListOrders.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) MerchantListOrders(ctx, merchantID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantListOrders", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).MerchantListOrders), ctx, merchantID, status, page, limit)
}

// DriverPickup mocks base method.
func (m *MockFoodOrderServiceInterface) DriverPickup(ctx context.Context, orderID, driverID string) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverPickup", ctx, orderID, driverID)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DriverPickup indicates an expected call of DriverPickup.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) DriverPickup(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverPickup", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).DriverPickup), ctx, orderID, driverID)
}

// DriverDeliver mocks base method.
func (m *MockFoodOrderServiceInterface) DriverDeliver(ctx context.Context, orderID, driverID string) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverDeliver", ctx, orderID, driverID)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DriverDeliver indicates an expected call of DriverDeliver.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) DriverDeliver(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverDeliver", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).DriverDeliver), ctx, orderID, driverID)
}

// AssignDriver mocks base method.
func (m *MockFoodOrderServiceInterface) AssignDriver(ctx context.Context, orderID, driverID string) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDriver", ctx, orderID, driverID)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignDriver indicates an expected call of AssignDriver.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) AssignDriver(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDriver", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).AssignDriver), ctx, orderID, driverID)
}

// SubmitRating mocks base method.
func (m *MockFoodOrderServiceInterface) SubmitRating(ctx context.Context, orderID, userID string, req model.SubmitFoodRatingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRating", ctx, orderID, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitRating indicates an expected call of SubmitRating.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) SubmitRating(ctx, orderID, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRating", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).SubmitRating), ctx, orderID, userID, req)
}

// GetFareBreakdown mocks base method.
func (m *MockFoodOrderServiceInterface) GetFareBreakdown(ctx context.Context, orderID, userID string) (*model.FareBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareBreakdown", ctx, orderID, userID)
	ret0, _ := ret[0].(*model.FareBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFareBreakdown indicates an expected call of GetFareBreakdown.
func (mr *MockFoodOrderServiceInterfaceMockRecorder) GetFareBreakdown(ctx, orderID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareBreakdown", reflect.TypeOf((*MockFoodOrderServiceInterface)(nil).GetFareBreakdown), ctx, orderID, userID)
}
