// Code generated by MockGen. DO NOT EDIT.
// Source: email_repository.go
//
// Generated by this command:
//
//	mockgen -source=email_repository.go -destination=../../mocks/mock_email_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/zicofarry/clay-app/backend/services/email-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailRepository is a mock of EmailRepository interface.
type MockEmailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailRepositoryMockRecorder is the mock recorder for MockEmailRepository.
type MockEmailRepositoryMockRecorder struct {
	mock *MockEmailRepository
}

// NewMockEmailRepository creates a new mock instance.
func NewMockEmailRepository(ctrl *gomock.Controller) *MockEmailRepository {
	mock := &MockEmailRepository{ctrl: ctrl}
	mock.recorder = &MockEmailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailRepository) EXPECT() *MockEmailRepositoryMockRecorder {
	return m.recorder
}

// GetEmailStatus mocks base method.
func (m *MockEmailRepository) GetEmailStatus(ctx context.Context, emailId string) (*model.EmailStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailStatus", ctx, emailId)
	ret0, _ := ret[0].(*model.EmailStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailStatus indicates an expected call of GetEmailStatus.
func (mr *MockEmailRepositoryMockRecorder) GetEmailStatus(ctx, emailId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailStatus", reflect.TypeOf((*MockEmailRepository)(nil).GetEmailStatus), ctx, emailId)
}

// GetTemplate mocks base method.
func (m *MockEmailRepository) GetTemplate(ctx context.Context, id model.EmailTemplateId) (*model.EmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", ctx, id)
	ret0, _ := ret[0].(*model.EmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockEmailRepositoryMockRecorder) GetTemplate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockEmailRepository)(nil).GetTemplate), ctx, id)
}

// GetTemplates mocks base method.
func (m *MockEmailRepository) GetTemplates(ctx context.Context) ([]model.EmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplates", ctx)
	ret0, _ := ret[0].([]model.EmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplates indicates an expected call of GetTemplates.
func (mr *MockEmailRepositoryMockRecorder) GetTemplates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplates", reflect.TypeOf((*MockEmailRepository)(nil).GetTemplates), ctx)
}

// IncrementRateLimit mocks base method.
func (m *MockEmailRepository) IncrementRateLimit(ctx context.Context, domain string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRateLimit", ctx, domain)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementRateLimit indicates an expected call of IncrementRateLimit.
func (mr *MockEmailRepositoryMockRecorder) IncrementRateLimit(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRateLimit", reflect.TypeOf((*MockEmailRepository)(nil).IncrementRateLimit), ctx, domain)
}

// SaveEmailLog mocks base method.
func (m *MockEmailRepository) SaveEmailLog(ctx context.Context, email model.EmailStatusResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmailLog", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEmailLog indicates an expected call of SaveEmailLog.
func (mr *MockEmailRepositoryMockRecorder) SaveEmailLog(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmailLog", reflect.TypeOf((*MockEmailRepository)(nil).SaveEmailLog), ctx, email)
}

// SaveRetryQueue mocks base method.
func (m *MockEmailRepository) SaveRetryQueue(ctx context.Context, messageId string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRetryQueue", ctx, messageId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRetryQueue indicates an expected call of SaveRetryQueue.
func (mr *MockEmailRepositoryMockRecorder) SaveRetryQueue(ctx, messageId, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRetryQueue", reflect.TypeOf((*MockEmailRepository)(nil).SaveRetryQueue), ctx, messageId, data)
}

// UpdateEmailStatus mocks base method.
func (m *MockEmailRepository) UpdateEmailStatus(ctx context.Context, providerId, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailStatus", ctx, providerId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailStatus indicates an expected call of UpdateEmailStatus.
func (mr *MockEmailRepositoryMockRecorder) UpdateEmailStatus(ctx, providerId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailStatus", reflect.TypeOf((*MockEmailRepository)(nil).UpdateEmailStatus), ctx, providerId, status)
}

// UpsertTemplate mocks base method.
func (m *MockEmailRepository) UpsertTemplate(ctx context.Context, template model.EmailTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTemplate indicates an expected call of UpsertTemplate.
func (mr *MockEmailRepositoryMockRecorder) UpsertTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTemplate", reflect.TypeOf((*MockEmailRepository)(nil).UpsertTemplate), ctx, template)
}
