// Code generated by hand to bypass Application Control block
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	repository "github.com/zicofarry/clay-app/backend/services/wallet-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockWalletRepository is a mock of WalletRepository interface.
type MockWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepositoryMockRecorder
}

// MockWalletRepositoryMockRecorder is the mock recorder for MockWalletRepository.
type MockWalletRepositoryMockRecorder struct {
	mock *MockWalletRepository
}

// NewMockWalletRepository creates a new mock instance.
func NewMockWalletRepository(ctrl *gomock.Controller) *MockWalletRepository {
	mock := &MockWalletRepository{ctrl: ctrl}
	mock.recorder = &MockWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepository) EXPECT() *MockWalletRepositoryMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockWalletRepository) CreateWallet(ctx context.Context, userID uuid.UUID) (*repository.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, userID)
	ret0, _ := ret[0].(*repository.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockWalletRepositoryMockRecorder) CreateWallet(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockWalletRepository)(nil).CreateWallet), ctx, userID)
}

// CreditWallet mocks base method.
func (m *MockWalletRepository) CreditWallet(ctx context.Context, userID uuid.UUID, amount int64, txType, description string, referenceID uuid.UUID) (*repository.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreditWallet", ctx, userID, amount, txType, description, referenceID)
	ret0, _ := ret[0].(*repository.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreditWallet indicates an expected call of CreditWallet.
func (mr *MockWalletRepositoryMockRecorder) CreditWallet(ctx, userID, amount, txType, description, referenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreditWallet", reflect.TypeOf((*MockWalletRepository)(nil).CreditWallet), ctx, userID, amount, txType, description, referenceID)
}

// DebitWallet mocks base method.
func (m *MockWalletRepository) DebitWallet(ctx context.Context, userID uuid.UUID, amount int64, txType, description string, referenceID uuid.UUID) (*repository.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebitWallet", ctx, userID, amount, txType, description, referenceID)
	ret0, _ := ret[0].(*repository.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DebitWallet indicates an expected call of DebitWallet.
func (mr *MockWalletRepositoryMockRecorder) DebitWallet(ctx, userID, amount, txType, description, referenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebitWallet", reflect.TypeOf((*MockWalletRepository)(nil).DebitWallet), ctx, userID, amount, txType, description, referenceID)
}

// GetWalletByUserID mocks base method.
func (m *MockWalletRepository) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (*repository.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByUserID", ctx, userID)
	ret0, _ := ret[0].(*repository.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByUserID indicates an expected call of GetWalletByUserID.
func (mr *MockWalletRepositoryMockRecorder) GetWalletByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByUserID", reflect.TypeOf((*MockWalletRepository)(nil).GetWalletByUserID), ctx, userID)
}
