// Code generated by hand to match auth-service mock pattern
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	repository "github.com/zicofarry/clay-app/backend/services/wallet-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockWalletService is a mock of WalletService interface.
type MockWalletService struct {
	ctrl     *gomock.Controller
	recorder *MockWalletServiceMockRecorder
}

// MockWalletServiceMockRecorder is the mock recorder for MockWalletService.
type MockWalletServiceMockRecorder struct {
	mock *MockWalletService
}

// NewMockWalletService creates a new mock instance.
func NewMockWalletService(ctrl *gomock.Controller) *MockWalletService {
	mock := &MockWalletService{ctrl: ctrl}
	mock.recorder = &MockWalletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletService) EXPECT() *MockWalletServiceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockWalletService) GetBalance(ctx context.Context, userID uuid.UUID) (*repository.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(*repository.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockWalletServiceMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockWalletService)(nil).GetBalance), ctx, userID)
}

// TopUp mocks base method.
func (m *MockWalletService) TopUp(ctx context.Context, userID uuid.UUID, amount int64, channel string) (*repository.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUp", ctx, userID, amount, channel)
	ret0, _ := ret[0].(*repository.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopUp indicates an expected call of TopUp.
func (mr *MockWalletServiceMockRecorder) TopUp(ctx, userID, amount, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUp", reflect.TypeOf((*MockWalletService)(nil).TopUp), ctx, userID, amount, channel)
}

// Debit mocks base method.
func (m *MockWalletService) Debit(ctx context.Context, userID uuid.UUID, amount int64, refID uuid.UUID, desc string) (*repository.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Debit", ctx, userID, amount, refID, desc)
	ret0, _ := ret[0].(*repository.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Debit indicates an expected call of Debit.
func (mr *MockWalletServiceMockRecorder) Debit(ctx, userID, amount, refID, desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debit", reflect.TypeOf((*MockWalletService)(nil).Debit), ctx, userID, amount, refID, desc)
}

// Credit mocks base method.
func (m *MockWalletService) Credit(ctx context.Context, userID uuid.UUID, amount int64, refID uuid.UUID, txType, desc string) (*repository.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credit", ctx, userID, amount, refID, txType, desc)
	ret0, _ := ret[0].(*repository.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Credit indicates an expected call of Credit.
func (mr *MockWalletServiceMockRecorder) Credit(ctx, userID, amount, refID, txType, desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credit", reflect.TypeOf((*MockWalletService)(nil).Credit), ctx, userID, amount, refID, txType, desc)
}
