// Code generated by MockGen. DO NOT EDIT.
// Source: chat_repository.go
//
// Generated by this command:
//
//	mockgen -source=chat_repository.go -destination=../../mocks/repomock/chat_repository_mock.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/zicofarry/clay-app/backend/services/chat-service/internal/repository"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockChatRepositoryInterface is a mock of ChatRepositoryInterface interface.
type MockChatRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChatRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockChatRepositoryInterfaceMockRecorder is the mock recorder for MockChatRepositoryInterface.
type MockChatRepositoryInterfaceMockRecorder struct {
	mock *MockChatRepositoryInterface
}

// NewMockChatRepositoryInterface creates a new mock instance.
func NewMockChatRepositoryInterface(ctrl *gomock.Controller) *MockChatRepositoryInterface {
	mock := &MockChatRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockChatRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRepositoryInterface) EXPECT() *MockChatRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AssignDriverToRoom mocks base method.
func (m *MockChatRepositoryInterface) AssignDriverToRoom(ctx context.Context, orderID, driverID string) (*repository.ChatRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDriverToRoom", ctx, orderID, driverID)
	ret0, _ := ret[0].(*repository.ChatRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignDriverToRoom indicates an expected call of AssignDriverToRoom.
func (mr *MockChatRepositoryInterfaceMockRecorder) AssignDriverToRoom(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDriverToRoom", reflect.TypeOf((*MockChatRepositoryInterface)(nil).AssignDriverToRoom), ctx, orderID, driverID)
}

// CreateRoom mocks base method.
func (m *MockChatRepositoryInterface) CreateRoom(ctx context.Context, room *repository.ChatRoom) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockChatRepositoryInterfaceMockRecorder) CreateRoom(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockChatRepositoryInterface)(nil).CreateRoom), ctx, room)
}

// GetLastMessage mocks base method.
func (m *MockChatRepositoryInterface) GetLastMessage(ctx context.Context, roomID primitive.ObjectID) (*repository.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastMessage", ctx, roomID)
	ret0, _ := ret[0].(*repository.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMessage indicates an expected call of GetLastMessage.
func (mr *MockChatRepositoryInterfaceMockRecorder) GetLastMessage(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMessage", reflect.TypeOf((*MockChatRepositoryInterface)(nil).GetLastMessage), ctx, roomID)
}

// GetMessageByClientID mocks base method.
func (m *MockChatRepositoryInterface) GetMessageByClientID(ctx context.Context, roomID primitive.ObjectID, clientID string) (*repository.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByClientID", ctx, roomID, clientID)
	ret0, _ := ret[0].(*repository.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByClientID indicates an expected call of GetMessageByClientID.
func (mr *MockChatRepositoryInterfaceMockRecorder) GetMessageByClientID(ctx, roomID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByClientID", reflect.TypeOf((*MockChatRepositoryInterface)(nil).GetMessageByClientID), ctx, roomID, clientID)
}

// GetRoomByID mocks base method.
func (m *MockChatRepositoryInterface) GetRoomByID(ctx context.Context, roomID primitive.ObjectID) (*repository.ChatRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByID", ctx, roomID)
	ret0, _ := ret[0].(*repository.ChatRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByID indicates an expected call of GetRoomByID.
func (mr *MockChatRepositoryInterfaceMockRecorder) GetRoomByID(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByID", reflect.TypeOf((*MockChatRepositoryInterface)(nil).GetRoomByID), ctx, roomID)
}

// GetRoomByOrderID mocks base method.
func (m *MockChatRepositoryInterface) GetRoomByOrderID(ctx context.Context, orderID string) (*repository.ChatRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*repository.ChatRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByOrderID indicates an expected call of GetRoomByOrderID.
func (mr *MockChatRepositoryInterfaceMockRecorder) GetRoomByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByOrderID", reflect.TypeOf((*MockChatRepositoryInterface)(nil).GetRoomByOrderID), ctx, orderID)
}

// GetUnreadCount mocks base method.
func (m *MockChatRepositoryInterface) GetUnreadCount(ctx context.Context, roomID primitive.ObjectID, participantID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadCount", ctx, roomID, participantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadCount indicates an expected call of GetUnreadCount.
func (mr *MockChatRepositoryInterfaceMockRecorder) GetUnreadCount(ctx, roomID, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadCount", reflect.TypeOf((*MockChatRepositoryInterface)(nil).GetUnreadCount), ctx, roomID, participantID)
}

// InsertMessage mocks base method.
func (m *MockChatRepositoryInterface) InsertMessage(ctx context.Context, msg *repository.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMessage indicates an expected call of InsertMessage.
func (mr *MockChatRepositoryInterfaceMockRecorder) InsertMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMessage", reflect.TypeOf((*MockChatRepositoryInterface)(nil).InsertMessage), ctx, msg)
}

// ListMessages mocks base method.
func (m *MockChatRepositoryInterface) ListMessages(ctx context.Context, roomID primitive.ObjectID, beforeID *primitive.ObjectID, limit int) ([]repository.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, roomID, beforeID, limit)
	ret0, _ := ret[0].([]repository.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockChatRepositoryInterfaceMockRecorder) ListMessages(ctx, roomID, beforeID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockChatRepositoryInterface)(nil).ListMessages), ctx, roomID, beforeID, limit)
}

// ListRoomsByParticipant mocks base method.
func (m *MockChatRepositoryInterface) ListRoomsByParticipant(ctx context.Context, participantID, status string, page, limit int) ([]repository.ChatRoom, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomsByParticipant", ctx, participantID, status, page, limit)
	ret0, _ := ret[0].([]repository.ChatRoom)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRoomsByParticipant indicates an expected call of ListRoomsByParticipant.
func (mr *MockChatRepositoryInterfaceMockRecorder) ListRoomsByParticipant(ctx, participantID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomsByParticipant", reflect.TypeOf((*MockChatRepositoryInterface)(nil).ListRoomsByParticipant), ctx, participantID, status, page, limit)
}

// MarkMessagesAsRead mocks base method.
func (m *MockChatRepositoryInterface) MarkMessagesAsRead(ctx context.Context, roomID, upToMessageID primitive.ObjectID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessagesAsRead", ctx, roomID, upToMessageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkMessagesAsRead indicates an expected call of MarkMessagesAsRead.
func (mr *MockChatRepositoryInterfaceMockRecorder) MarkMessagesAsRead(ctx, roomID, upToMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessagesAsRead", reflect.TypeOf((*MockChatRepositoryInterface)(nil).MarkMessagesAsRead), ctx, roomID, upToMessageID)
}

// UpdateRoomStatus mocks base method.
func (m *MockChatRepositoryInterface) UpdateRoomStatus(ctx context.Context, roomID primitive.ObjectID, status string, closedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomStatus", ctx, roomID, status, closedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoomStatus indicates an expected call of UpdateRoomStatus.
func (mr *MockChatRepositoryInterfaceMockRecorder) UpdateRoomStatus(ctx, roomID, status, closedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomStatus", reflect.TypeOf((*MockChatRepositoryInterface)(nil).UpdateRoomStatus), ctx, roomID, status, closedAt)
}
