// Code generated by MockGen. DO NOT EDIT.
// Source: payment_service.go

package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/payment-service/internal/repository"
	service "github.com/zicofarry/clay-app/backend/services/payment-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

type MockPaymentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceInterfaceMockRecorder
}

type MockPaymentServiceInterfaceMockRecorder struct {
	mock *MockPaymentServiceInterface
}

func NewMockPaymentServiceInterface(ctrl *gomock.Controller) *MockPaymentServiceInterface {
	mock := &MockPaymentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceInterfaceMockRecorder{mock}
	return mock
}

func (m *MockPaymentServiceInterface) EXPECT() *MockPaymentServiceInterfaceMockRecorder {
	return m.recorder
}

func (m *MockPaymentServiceInterface) ListPaymentMethods(ctx context.Context, userID string) (*service.PaymentMethodsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaymentMethods", ctx, userID)
	ret0, _ := ret[0].(*service.PaymentMethodsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) ListPaymentMethods(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentMethods", reflect.TypeOf((*MockPaymentServiceInterface)(nil).ListPaymentMethods), ctx, userID)
}

func (m *MockPaymentServiceInterface) AddPaymentMethod(ctx context.Context, userID string, req *service.AddPaymentMethodRequest) (*service.PaymentMethodResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPaymentMethod", ctx, userID, req)
	ret0, _ := ret[0].(*service.PaymentMethodResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) AddPaymentMethod(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPaymentMethod", reflect.TypeOf((*MockPaymentServiceInterface)(nil).AddPaymentMethod), ctx, userID, req)
}

func (m *MockPaymentServiceInterface) DeletePaymentMethod(ctx context.Context, userID, methodID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePaymentMethod", ctx, userID, methodID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPaymentServiceInterfaceMockRecorder) DeletePaymentMethod(ctx, userID, methodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentMethod", reflect.TypeOf((*MockPaymentServiceInterface)(nil).DeletePaymentMethod), ctx, userID, methodID)
}

func (m *MockPaymentServiceInterface) SetDefaultPaymentMethod(ctx context.Context, userID, methodID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultPaymentMethod", ctx, userID, methodID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPaymentServiceInterfaceMockRecorder) SetDefaultPaymentMethod(ctx, userID, methodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultPaymentMethod", reflect.TypeOf((*MockPaymentServiceInterface)(nil).SetDefaultPaymentMethod), ctx, userID, methodID)
}

func (m *MockPaymentServiceInterface) InitiateCodVerification(ctx context.Context, userID string, req *service.CodVerifyInitiateRequest) (*service.CodVerifyInitiateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateCodVerification", ctx, userID, req)
	ret0, _ := ret[0].(*service.CodVerifyInitiateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) InitiateCodVerification(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateCodVerification", reflect.TypeOf((*MockPaymentServiceInterface)(nil).InitiateCodVerification), ctx, userID, req)
}

func (m *MockPaymentServiceInterface) GetCodVerificationStatus(ctx context.Context, verificationID string) (*service.CodVerifyStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodVerificationStatus", ctx, verificationID)
	ret0, _ := ret[0].(*service.CodVerifyStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) GetCodVerificationStatus(ctx, verificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodVerificationStatus", reflect.TypeOf((*MockPaymentServiceInterface)(nil).GetCodVerificationStatus), ctx, verificationID)
}

func (m *MockPaymentServiceInterface) SubmitCodOTP(ctx context.Context, verificationID string, req *service.CodVerifyOTPRequest) (*service.CodVerifyStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitCodOTP", ctx, verificationID, req)
	ret0, _ := ret[0].(*service.CodVerifyStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) SubmitCodOTP(ctx, verificationID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitCodOTP", reflect.TypeOf((*MockPaymentServiceInterface)(nil).SubmitCodOTP), ctx, verificationID, req)
}

func (m *MockPaymentServiceInterface) RespondCodVerification(ctx context.Context, verificationID string, req *service.CodVerifyRespondRequest) (*service.CodVerifyStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondCodVerification", ctx, verificationID, req)
	ret0, _ := ret[0].(*service.CodVerifyStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) RespondCodVerification(ctx, verificationID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondCodVerification", reflect.TypeOf((*MockPaymentServiceInterface)(nil).RespondCodVerification), ctx, verificationID, req)
}

func (m *MockPaymentServiceInterface) GetTransactionHistory(ctx context.Context, userID string, txType string, page, limit int) (*service.TransactionHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionHistory", ctx, userID, txType, page, limit)
	ret0, _ := ret[0].(*service.TransactionHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) GetTransactionHistory(ctx, userID, txType, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionHistory", reflect.TypeOf((*MockPaymentServiceInterface)(nil).GetTransactionHistory), ctx, userID, txType, page, limit)
}

func (m *MockPaymentServiceInterface) GetTransactionDetail(ctx context.Context, transactionID string) (*repository.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionDetail", ctx, transactionID)
	ret0, _ := ret[0].(*repository.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) GetTransactionDetail(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionDetail", reflect.TypeOf((*MockPaymentServiceInterface)(nil).GetTransactionDetail), ctx, transactionID)
}

func (m *MockPaymentServiceInterface) CreateCharge(ctx context.Context, req *service.ChargeRequest) (*service.ChargeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCharge", ctx, req)
	ret0, _ := ret[0].(*service.ChargeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) CreateCharge(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCharge", reflect.TypeOf((*MockPaymentServiceInterface)(nil).CreateCharge), ctx, req)
}

func (m *MockPaymentServiceInterface) CreateRefund(ctx context.Context, req *service.RefundRequest) (*service.RefundResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefund", ctx, req)
	ret0, _ := ret[0].(*service.RefundResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) CreateRefund(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefund", reflect.TypeOf((*MockPaymentServiceInterface)(nil).CreateRefund), ctx, req)
}

func (m *MockPaymentServiceInterface) GetTransactionStatus(ctx context.Context, transactionID string) (*service.TransactionStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatus", ctx, transactionID)
	ret0, _ := ret[0].(*service.TransactionStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) GetTransactionStatus(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatus", reflect.TypeOf((*MockPaymentServiceInterface)(nil).GetTransactionStatus), ctx, transactionID)
}

func (m *MockPaymentServiceInterface) HoldPayment(ctx context.Context, req *service.HoldRequest) (*service.HoldResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HoldPayment", ctx, req)
	ret0, _ := ret[0].(*service.HoldResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) HoldPayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HoldPayment", reflect.TypeOf((*MockPaymentServiceInterface)(nil).HoldPayment), ctx, req)
}

func (m *MockPaymentServiceInterface) CapturePayment(ctx context.Context, req *service.CaptureRequest) (*service.CaptureResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CapturePayment", ctx, req)
	ret0, _ := ret[0].(*service.CaptureResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) CapturePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CapturePayment", reflect.TypeOf((*MockPaymentServiceInterface)(nil).CapturePayment), ctx, req)
}

func (m *MockPaymentServiceInterface) ReleasePayment(ctx context.Context, req *service.ReleaseRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleasePayment", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPaymentServiceInterfaceMockRecorder) ReleasePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleasePayment", reflect.TypeOf((*MockPaymentServiceInterface)(nil).ReleasePayment), ctx, req)
}

func (m *MockPaymentServiceInterface) CreateSettlement(ctx context.Context, req *service.CreateSettlementRequest) (*service.SettlementResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSettlement", ctx, req)
	ret0, _ := ret[0].(*service.SettlementResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPaymentServiceInterfaceMockRecorder) CreateSettlement(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSettlement", reflect.TypeOf((*MockPaymentServiceInterface)(nil).CreateSettlement), ctx, req)
}
