// Code generated by MockGen. DO NOT EDIT.
// Source: geo_client.go
//
// Generated by: mockgen -source=geo_client.go -destination=../../mocks/geomock/mock_geo_client.go -package=geomock

package geomock

import (
	context "context"
	reflect "reflect"

	geo "github.com/zicofarry/clay-app/backend/services/matching-service/internal/geo"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// RegisterDriver mocks base method.
func (m *MockClient) RegisterDriver(ctx context.Context, u geo.LocationUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDriver", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterDriver indicates an expected call of RegisterDriver.
func (mr *MockClientMockRecorder) RegisterDriver(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDriver", reflect.TypeOf((*MockClient)(nil).RegisterDriver), ctx, u)
}

// UnregisterDriver mocks base method.
func (m *MockClient) UnregisterDriver(ctx context.Context, driverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterDriver", ctx, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterDriver indicates an expected call of UnregisterDriver.
func (mr *MockClientMockRecorder) UnregisterDriver(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterDriver", reflect.TypeOf((*MockClient)(nil).UnregisterDriver), ctx, driverID)
}

// UpdateLocation mocks base method.
func (m *MockClient) UpdateLocation(ctx context.Context, u geo.LocationUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockClientMockRecorder) UpdateLocation(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockClient)(nil).UpdateLocation), ctx, u)
}
