// Code generated by MockGen. DO NOT EDIT.
// Source: delivery_order_service.go
//
// Generated by: mockgen -source=delivery_order_service.go -destination=../../mocks/mock_delivery_order_service.go -package=mocks

package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/delivery-order-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryOrderServiceInterface is a mock of DeliveryOrderServiceInterface interface.
type MockDeliveryOrderServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryOrderServiceInterfaceMockRecorder
}

// MockDeliveryOrderServiceInterfaceMockRecorder is the mock recorder for MockDeliveryOrderServiceInterface.
type MockDeliveryOrderServiceInterfaceMockRecorder struct {
	mock *MockDeliveryOrderServiceInterface
}

// NewMockDeliveryOrderServiceInterface creates a new mock instance.
func NewMockDeliveryOrderServiceInterface(ctrl *gomock.Controller) *MockDeliveryOrderServiceInterface {
	mock := &MockDeliveryOrderServiceInterface{ctrl: ctrl}
	mock.recorder = &MockDeliveryOrderServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryOrderServiceInterface) EXPECT() *MockDeliveryOrderServiceInterfaceMockRecorder {
	return m.recorder
}

// EstimateFare mocks base method.
func (m *MockDeliveryOrderServiceInterface) EstimateFare(ctx context.Context, req *service.FareEstimateRequest) (*service.FareEstimateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFare", ctx, req)
	ret0, _ := ret[0].(*service.FareEstimateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateFare indicates an expected call of EstimateFare.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) EstimateFare(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFare", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).EstimateFare), ctx, req)
}

// CreateOrder mocks base method.
func (m *MockDeliveryOrderServiceInterface) CreateOrder(ctx context.Context, userID string, req *service.CreateDeliveryOrderRequest) (*service.DeliveryOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, req)
	ret0, _ := ret[0].(*service.DeliveryOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) CreateOrder(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).CreateOrder), ctx, userID, req)
}

// GetActiveOrder mocks base method.
func (m *MockDeliveryOrderServiceInterface) GetActiveOrder(ctx context.Context, userID string) (*service.DeliveryOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrder", ctx, userID)
	ret0, _ := ret[0].(*service.DeliveryOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrder indicates an expected call of GetActiveOrder.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) GetActiveOrder(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrder", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).GetActiveOrder), ctx, userID)
}

// GetOrderHistory mocks base method.
func (m *MockDeliveryOrderServiceInterface) GetOrderHistory(ctx context.Context, userID string, q service.HistoryQuery) (*service.DeliveryOrderHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderHistory", ctx, userID, q)
	ret0, _ := ret[0].(*service.DeliveryOrderHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderHistory indicates an expected call of GetOrderHistory.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) GetOrderHistory(ctx, userID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderHistory", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).GetOrderHistory), ctx, userID, q)
}

// GetOrder mocks base method.
func (m *MockDeliveryOrderServiceInterface) GetOrder(ctx context.Context, userID, role, orderID string) (*service.DeliveryOrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, userID, role, orderID)
	ret0, _ := ret[0].(*service.DeliveryOrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) GetOrder(ctx, userID, role, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).GetOrder), ctx, userID, role, orderID)
}

// CancelOrder mocks base method.
func (m *MockDeliveryOrderServiceInterface) CancelOrder(ctx context.Context, userID, orderID string, req *service.CancelOrderRequest) (*service.DeliveryOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, userID, orderID, req)
	ret0, _ := ret[0].(*service.DeliveryOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) CancelOrder(ctx, userID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).CancelOrder), ctx, userID, orderID, req)
}

// SubmitRating mocks base method.
func (m *MockDeliveryOrderServiceInterface) SubmitRating(ctx context.Context, userID, orderID string, req *service.SubmitRatingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRating", ctx, userID, orderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitRating indicates an expected call of SubmitRating.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) SubmitRating(ctx, userID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRating", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).SubmitRating), ctx, userID, orderID, req)
}

// GetFareBreakdown mocks base method.
func (m *MockDeliveryOrderServiceInterface) GetFareBreakdown(ctx context.Context, userID, orderID string) (*service.FareBreakdownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareBreakdown", ctx, userID, orderID)
	ret0, _ := ret[0].(*service.FareBreakdownResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFareBreakdown indicates an expected call of GetFareBreakdown.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) GetFareBreakdown(ctx, userID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareBreakdown", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).GetFareBreakdown), ctx, userID, orderID)
}

// DriverAcceptOrder mocks base method.
func (m *MockDeliveryOrderServiceInterface) DriverAcceptOrder(ctx context.Context, driverID, orderID string) (*service.DriverAcceptResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverAcceptOrder", ctx, driverID, orderID)
	ret0, _ := ret[0].(*service.DriverAcceptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DriverAcceptOrder indicates an expected call of DriverAcceptOrder.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) DriverAcceptOrder(ctx, driverID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverAcceptOrder", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).DriverAcceptOrder), ctx, driverID, orderID)
}

// DriverRejectOrder mocks base method.
func (m *MockDeliveryOrderServiceInterface) DriverRejectOrder(ctx context.Context, driverID, orderID string, req *service.DriverRejectRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverRejectOrder", ctx, driverID, orderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DriverRejectOrder indicates an expected call of DriverRejectOrder.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) DriverRejectOrder(ctx, driverID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverRejectOrder", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).DriverRejectOrder), ctx, driverID, orderID, req)
}

// DriverUpdateOrderStatus mocks base method.
func (m *MockDeliveryOrderServiceInterface) DriverUpdateOrderStatus(ctx context.Context, driverID, orderID string, req *service.DriverUpdateStatusRequest) (*service.DeliveryOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverUpdateOrderStatus", ctx, driverID, orderID, req)
	ret0, _ := ret[0].(*service.DeliveryOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DriverUpdateOrderStatus indicates an expected call of DriverUpdateOrderStatus.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) DriverUpdateOrderStatus(ctx, driverID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverUpdateOrderStatus", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).DriverUpdateOrderStatus), ctx, driverID, orderID, req)
}

// InternalCreateOrder mocks base method.
func (m *MockDeliveryOrderServiceInterface) InternalCreateOrder(ctx context.Context, req *service.InternalCreateOrderRequest) (*service.DeliveryOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalCreateOrder", ctx, req)
	ret0, _ := ret[0].(*service.DeliveryOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalCreateOrder indicates an expected call of InternalCreateOrder.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) InternalCreateOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalCreateOrder", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).InternalCreateOrder), ctx, req)
}

// InternalGetOrder mocks base method.
func (m *MockDeliveryOrderServiceInterface) InternalGetOrder(ctx context.Context, orderID string) (*service.DeliveryOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetOrder", ctx, orderID)
	ret0, _ := ret[0].(*service.DeliveryOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetOrder indicates an expected call of InternalGetOrder.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) InternalGetOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetOrder", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).InternalGetOrder), ctx, orderID)
}

// InternalUpdateStatus mocks base method.
func (m *MockDeliveryOrderServiceInterface) InternalUpdateStatus(ctx context.Context, orderID string, req *service.InternalUpdateStatusRequest) (*service.DeliveryOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalUpdateStatus", ctx, orderID, req)
	ret0, _ := ret[0].(*service.DeliveryOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalUpdateStatus indicates an expected call of InternalUpdateStatus.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) InternalUpdateStatus(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalUpdateStatus", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).InternalUpdateStatus), ctx, orderID, req)
}

// InternalAssignDriver mocks base method.
func (m *MockDeliveryOrderServiceInterface) InternalAssignDriver(ctx context.Context, orderID string, req *service.InternalAssignDriverRequest) (*service.InternalAssignDriverResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalAssignDriver", ctx, orderID, req)
	ret0, _ := ret[0].(*service.InternalAssignDriverResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalAssignDriver indicates an expected call of InternalAssignDriver.
func (mr *MockDeliveryOrderServiceInterfaceMockRecorder) InternalAssignDriver(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalAssignDriver", reflect.TypeOf((*MockDeliveryOrderServiceInterface)(nil).InternalAssignDriver), ctx, orderID, req)
}
