// Code generated by MockGen. DO NOT EDIT.
// Source: matching_service.go
//
// Generated by: mockgen -source=matching_service.go -destination=../../mocks/mock_matching_service.go -package=mocks

package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/matching-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchingServiceInterface is a mock of MatchingServiceInterface interface.
type MockMatchingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMatchingServiceInterfaceMockRecorder
}

// MockMatchingServiceInterfaceMockRecorder is the mock recorder for MockMatchingServiceInterface.
type MockMatchingServiceInterfaceMockRecorder struct {
	mock *MockMatchingServiceInterface
}

// NewMockMatchingServiceInterface creates a new mock instance.
func NewMockMatchingServiceInterface(ctrl *gomock.Controller) *MockMatchingServiceInterface {
	mock := &MockMatchingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockMatchingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchingServiceInterface) EXPECT() *MockMatchingServiceInterfaceMockRecorder {
	return m.recorder
}

// GoOnline mocks base method.
func (m *MockMatchingServiceInterface) GoOnline(ctx context.Context, driverID string, req *service.GoOnlineRequest) (*service.DriverStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoOnline", ctx, driverID, req)
	ret0, _ := ret[0].(*service.DriverStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoOnline indicates an expected call of GoOnline.
func (mr *MockMatchingServiceInterfaceMockRecorder) GoOnline(ctx, driverID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoOnline", reflect.TypeOf((*MockMatchingServiceInterface)(nil).GoOnline), ctx, driverID, req)
}

// GoOffline mocks base method.
func (m *MockMatchingServiceInterface) GoOffline(ctx context.Context, driverID string) (*service.DriverStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoOffline", ctx, driverID)
	ret0, _ := ret[0].(*service.DriverStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoOffline indicates an expected call of GoOffline.
func (mr *MockMatchingServiceInterfaceMockRecorder) GoOffline(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoOffline", reflect.TypeOf((*MockMatchingServiceInterface)(nil).GoOffline), ctx, driverID)
}

// UpdateLocation mocks base method.
func (m *MockMatchingServiceInterface) UpdateLocation(ctx context.Context, driverID string, req *service.LocationUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, driverID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockMatchingServiceInterfaceMockRecorder) UpdateLocation(ctx, driverID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockMatchingServiceInterface)(nil).UpdateLocation), ctx, driverID, req)
}

// Heartbeat mocks base method.
func (m *MockMatchingServiceInterface) Heartbeat(ctx context.Context, driverID string) (*service.HeartbeatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, driverID)
	ret0, _ := ret[0].(*service.HeartbeatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockMatchingServiceInterfaceMockRecorder) Heartbeat(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockMatchingServiceInterface)(nil).Heartbeat), ctx, driverID)
}

// Respond mocks base method.
func (m *MockMatchingServiceInterface) Respond(ctx context.Context, driverID string, req *service.OfferResponseRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Respond", ctx, driverID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Respond indicates an expected call of Respond.
func (mr *MockMatchingServiceInterfaceMockRecorder) Respond(ctx, driverID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Respond", reflect.TypeOf((*MockMatchingServiceInterface)(nil).Respond), ctx, driverID, req)
}

// SetMode mocks base method.
func (m *MockMatchingServiceInterface) SetMode(ctx context.Context, driverID string, req *service.SetDispatchModeRequest) (*service.DispatchModeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMode", ctx, driverID, req)
	ret0, _ := ret[0].(*service.DispatchModeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMode indicates an expected call of SetMode.
func (mr *MockMatchingServiceInterfaceMockRecorder) SetMode(ctx, driverID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMode", reflect.TypeOf((*MockMatchingServiceInterface)(nil).SetMode), ctx, driverID, req)
}

// GetFullStatus mocks base method.
func (m *MockMatchingServiceInterface) GetFullStatus(ctx context.Context, driverID string) (*service.FullDriverStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullStatus", ctx, driverID)
	ret0, _ := ret[0].(*service.FullDriverStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullStatus indicates an expected call of GetFullStatus.
func (mr *MockMatchingServiceInterfaceMockRecorder) GetFullStatus(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullStatus", reflect.TypeOf((*MockMatchingServiceInterface)(nil).GetFullStatus), ctx, driverID)
}

// GetTodayEarnings mocks base method.
func (m *MockMatchingServiceInterface) GetTodayEarnings(ctx context.Context, driverID string) (*service.EarningsTodayResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayEarnings", ctx, driverID)
	ret0, _ := ret[0].(*service.EarningsTodayResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayEarnings indicates an expected call of GetTodayEarnings.
func (mr *MockMatchingServiceInterfaceMockRecorder) GetTodayEarnings(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayEarnings", reflect.TypeOf((*MockMatchingServiceInterface)(nil).GetTodayEarnings), ctx, driverID)
}

// StartDispatch mocks base method.
func (m *MockMatchingServiceInterface) StartDispatch(ctx context.Context, req *service.DispatchRequest) (*service.DispatchSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDispatch", ctx, req)
	ret0, _ := ret[0].(*service.DispatchSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDispatch indicates an expected call of StartDispatch.
func (mr *MockMatchingServiceInterfaceMockRecorder) StartDispatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDispatch", reflect.TypeOf((*MockMatchingServiceInterface)(nil).StartDispatch), ctx, req)
}

// CancelDispatch mocks base method.
func (m *MockMatchingServiceInterface) CancelDispatch(ctx context.Context, req *service.CancelDispatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelDispatch", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelDispatch indicates an expected call of CancelDispatch.
func (mr *MockMatchingServiceInterfaceMockRecorder) CancelDispatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelDispatch", reflect.TypeOf((*MockMatchingServiceInterface)(nil).CancelDispatch), ctx, req)
}

// NearbyActiveDrivers mocks base method.
func (m *MockMatchingServiceInterface) NearbyActiveDrivers(ctx context.Context, q service.NearbyDriversQuery) (*service.NearbyDriversResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NearbyActiveDrivers", ctx, q)
	ret0, _ := ret[0].(*service.NearbyDriversResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NearbyActiveDrivers indicates an expected call of NearbyActiveDrivers.
func (mr *MockMatchingServiceInterfaceMockRecorder) NearbyActiveDrivers(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NearbyActiveDrivers", reflect.TypeOf((*MockMatchingServiceInterface)(nil).NearbyActiveDrivers), ctx, q)
}

// GetSession mocks base method.
func (m *MockMatchingServiceInterface) GetSession(ctx context.Context, orderID string) (*service.DispatchSessionDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, orderID)
	ret0, _ := ret[0].(*service.DispatchSessionDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockMatchingServiceInterfaceMockRecorder) GetSession(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockMatchingServiceInterface)(nil).GetSession), ctx, orderID)
}

// GetZoneStats mocks base method.
func (m *MockMatchingServiceInterface) GetZoneStats(ctx context.Context, vehicleType, zoneID string) (*service.ZoneStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZoneStats", ctx, vehicleType, zoneID)
	ret0, _ := ret[0].(*service.ZoneStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZoneStats indicates an expected call of GetZoneStats.
func (mr *MockMatchingServiceInterfaceMockRecorder) GetZoneStats(ctx, vehicleType, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZoneStats", reflect.TypeOf((*MockMatchingServiceInterface)(nil).GetZoneStats), ctx, vehicleType, zoneID)
}

// FreeDriver mocks base method.
func (m *MockMatchingServiceInterface) FreeDriver(ctx context.Context, driverID string, req *service.FreeDriverRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreeDriver", ctx, driverID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// FreeDriver indicates an expected call of FreeDriver.
func (mr *MockMatchingServiceInterfaceMockRecorder) FreeDriver(ctx, driverID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeDriver", reflect.TypeOf((*MockMatchingServiceInterface)(nil).FreeDriver), ctx, driverID, req)
}
