// Code generated by MockGen. DO NOT EDIT.
// Source: promotion_repository.go
//
// Generated by this command:
//
//	mockgen -source=promotion_repository.go -destination=../../mocks/repomock/promotion_repository_mock.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	repository "github.com/zicofarry/clay-app/backend/services/promotion-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPromotionRepositoryInterface is a mock of PromotionRepositoryInterface interface.
type MockPromotionRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPromotionRepositoryInterfaceMockRecorder is the mock recorder for MockPromotionRepositoryInterface.
type MockPromotionRepositoryInterfaceMockRecorder struct {
	mock *MockPromotionRepositoryInterface
}

// NewMockPromotionRepositoryInterface creates a new mock instance.
func NewMockPromotionRepositoryInterface(ctrl *gomock.Controller) *MockPromotionRepositoryInterface {
	mock := &MockPromotionRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPromotionRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionRepositoryInterface) EXPECT() *MockPromotionRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreatePromoCode mocks base method.
func (m *MockPromotionRepositoryInterface) CreatePromoCode(ctx context.Context, promo *repository.PromoCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePromoCode", ctx, promo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePromoCode indicates an expected call of CreatePromoCode.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) CreatePromoCode(ctx, promo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePromoCode", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).CreatePromoCode), ctx, promo)
}

// CreatePromoUsage mocks base method.
func (m *MockPromotionRepositoryInterface) CreatePromoUsage(ctx context.Context, usage *repository.PromoUsage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePromoUsage", ctx, usage)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePromoUsage indicates an expected call of CreatePromoUsage.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) CreatePromoUsage(ctx, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePromoUsage", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).CreatePromoUsage), ctx, usage)
}

// CreateUserPromo mocks base method.
func (m *MockPromotionRepositoryInterface) CreateUserPromo(ctx context.Context, up *repository.UserPromo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserPromo", ctx, up)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserPromo indicates an expected call of CreateUserPromo.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) CreateUserPromo(ctx, up any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserPromo", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).CreateUserPromo), ctx, up)
}

// GetPromoCodeByCode mocks base method.
func (m *MockPromotionRepositoryInterface) GetPromoCodeByCode(ctx context.Context, code string) (*repository.PromoCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoCodeByCode", ctx, code)
	ret0, _ := ret[0].(*repository.PromoCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoCodeByCode indicates an expected call of GetPromoCodeByCode.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) GetPromoCodeByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoCodeByCode", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).GetPromoCodeByCode), ctx, code)
}

// GetPromoCodeByID mocks base method.
func (m *MockPromotionRepositoryInterface) GetPromoCodeByID(ctx context.Context, id uuid.UUID) (*repository.PromoCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoCodeByID", ctx, id)
	ret0, _ := ret[0].(*repository.PromoCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoCodeByID indicates an expected call of GetPromoCodeByID.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) GetPromoCodeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoCodeByID", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).GetPromoCodeByID), ctx, id)
}

// GetPromoUsageByOrder mocks base method.
func (m *MockPromotionRepositoryInterface) GetPromoUsageByOrder(ctx context.Context, orderID uuid.UUID) (*repository.PromoUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoUsageByOrder", ctx, orderID)
	ret0, _ := ret[0].(*repository.PromoUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoUsageByOrder indicates an expected call of GetPromoUsageByOrder.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) GetPromoUsageByOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoUsageByOrder", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).GetPromoUsageByOrder), ctx, orderID)
}

// GetUserPromo mocks base method.
func (m *MockPromotionRepositoryInterface) GetUserPromo(ctx context.Context, userID, promoID uuid.UUID) (*repository.UserPromo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPromo", ctx, userID, promoID)
	ret0, _ := ret[0].(*repository.UserPromo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPromo indicates an expected call of GetUserPromo.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) GetUserPromo(ctx, userID, promoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPromo", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).GetUserPromo), ctx, userID, promoID)
}

// IncrementPromoUsage mocks base method.
func (m *MockPromotionRepositoryInterface) IncrementPromoUsage(ctx context.Context, promoID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPromoUsage", ctx, promoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementPromoUsage indicates an expected call of IncrementPromoUsage.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) IncrementPromoUsage(ctx, promoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPromoUsage", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).IncrementPromoUsage), ctx, promoID)
}

// ListPromoCodes mocks base method.
func (m *MockPromotionRepositoryInterface) ListPromoCodes(ctx context.Context, status string, limit, offset int) ([]repository.PromoCode, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPromoCodes", ctx, status, limit, offset)
	ret0, _ := ret[0].([]repository.PromoCode)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPromoCodes indicates an expected call of ListPromoCodes.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) ListPromoCodes(ctx, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPromoCodes", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).ListPromoCodes), ctx, status, limit, offset)
}

// ListUserPromos mocks base method.
func (m *MockPromotionRepositoryInterface) ListUserPromos(ctx context.Context, userID uuid.UUID, serviceType, status string) ([]repository.UserPromo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserPromos", ctx, userID, serviceType, status)
	ret0, _ := ret[0].([]repository.UserPromo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserPromos indicates an expected call of ListUserPromos.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) ListUserPromos(ctx, userID, serviceType, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserPromos", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).ListUserPromos), ctx, userID, serviceType, status)
}

// ReleasePromoUsage mocks base method.
func (m *MockPromotionRepositoryInterface) ReleasePromoUsage(ctx context.Context, promoID, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleasePromoUsage", ctx, promoID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleasePromoUsage indicates an expected call of ReleasePromoUsage.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) ReleasePromoUsage(ctx, promoID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleasePromoUsage", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).ReleasePromoUsage), ctx, promoID, orderID)
}

// RunInTx mocks base method.
func (m *MockPromotionRepositoryInterface) RunInTx(ctx context.Context, fn func(repository.PromotionRepositoryInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).RunInTx), ctx, fn)
}

// UpdatePromoCode mocks base method.
func (m *MockPromotionRepositoryInterface) UpdatePromoCode(ctx context.Context, promo *repository.PromoCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePromoCode", ctx, promo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePromoCode indicates an expected call of UpdatePromoCode.
func (mr *MockPromotionRepositoryInterfaceMockRecorder) UpdatePromoCode(ctx, promo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePromoCode", reflect.TypeOf((*MockPromotionRepositoryInterface)(nil).UpdatePromoCode), ctx, promo)
}
