// Code generated by MockGen. DO NOT EDIT.
// Source: food_order_repository_interface.go
//
// Generated by: mockgen -source=food_order_repository_interface.go -destination=../../mocks/repomock/mock_food_order_repository.go -package=repomock

package repomock

import (
	context "context"
	reflect "reflect"

	model "github.com/zicofarry/clay-app/backend/services/food-order-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFoodOrderRepositoryInterface is a mock of FoodOrderRepositoryInterface interface.
type MockFoodOrderRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFoodOrderRepositoryInterfaceMockRecorder
}

// MockFoodOrderRepositoryInterfaceMockRecorder is the mock recorder for MockFoodOrderRepositoryInterface.
type MockFoodOrderRepositoryInterfaceMockRecorder struct {
	mock *MockFoodOrderRepositoryInterface
}

// NewMockFoodOrderRepositoryInterface creates a new mock instance.
func NewMockFoodOrderRepositoryInterface(ctrl *gomock.Controller) *MockFoodOrderRepositoryInterface {
	mock := &MockFoodOrderRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockFoodOrderRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoodOrderRepositoryInterface) EXPECT() *MockFoodOrderRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFoodOrderRepositoryInterface) Create(ctx context.Context, order *model.FoodOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) Create(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).Create), ctx, order)
}

// GetByID mocks base method.
func (m *MockFoodOrderRepositoryInterface) GetByID(ctx context.Context, orderID string) (*model.FoodOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, orderID)
	ret0, _ := ret[0].(*model.FoodOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) GetByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).GetByID), ctx, orderID)
}

// UpdateStatus mocks base method.
func (m *MockFoodOrderRepositoryInterface) UpdateStatus(ctx context.Context, orderID string, status model.OrderStatus, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, orderID, status, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) UpdateStatus(ctx, orderID, status, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).UpdateStatus), ctx, orderID, status, updates)
}

// UpdateConfirmed mocks base method.
func (m *MockFoodOrderRepositoryInterface) UpdateConfirmed(ctx context.Context, orderID string, estPrepMin int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfirmed", ctx, orderID, estPrepMin)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfirmed indicates an expected call of UpdateConfirmed.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) UpdateConfirmed(ctx, orderID, estPrepMin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfirmed", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).UpdateConfirmed), ctx, orderID, estPrepMin)
}

// UpdateCancelled mocks base method.
func (m *MockFoodOrderRepositoryInterface) UpdateCancelled(ctx context.Context, orderID string, by model.CancelledBy, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCancelled", ctx, orderID, by, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCancelled indicates an expected call of UpdateCancelled.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) UpdateCancelled(ctx, orderID, by, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCancelled", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).UpdateCancelled), ctx, orderID, by, reason)
}

// AssignDriver mocks base method.
func (m *MockFoodOrderRepositoryInterface) AssignDriver(ctx context.Context, orderID, driverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDriver", ctx, orderID, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignDriver indicates an expected call of AssignDriver.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) AssignDriver(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDriver", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).AssignDriver), ctx, orderID, driverID)
}

// UpdateDelivered mocks base method.
func (m *MockFoodOrderRepositoryInterface) UpdateDelivered(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDelivered", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDelivered indicates an expected call of UpdateDelivered.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) UpdateDelivered(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDelivered", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).UpdateDelivered), ctx, orderID)
}

// MarkRatingSubmitted mocks base method.
func (m *MockFoodOrderRepositoryInterface) MarkRatingSubmitted(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRatingSubmitted", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRatingSubmitted indicates an expected call of MarkRatingSubmitted.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) MarkRatingSubmitted(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRatingSubmitted", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).MarkRatingSubmitted), ctx, orderID)
}

// ListByUser mocks base method.
func (m *MockFoodOrderRepositoryInterface) ListByUser(ctx context.Context, userID, status string, page, limit int) ([]model.FoodOrder, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, status, page, limit)
	ret0, _ := ret[0].([]model.FoodOrder)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) ListByUser(ctx, userID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).ListByUser), ctx, userID, status, page, limit)
}

// ListByMerchant mocks base method.
func (m *MockFoodOrderRepositoryInterface) ListByMerchant(ctx context.Context, merchantID, status string, page, limit int) ([]model.FoodOrder, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMerchant", ctx, merchantID, status, page, limit)
	ret0, _ := ret[0].([]model.FoodOrder)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByMerchant indicates an expected call of ListByMerchant.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) ListByMerchant(ctx, merchantID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMerchant", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).ListByMerchant), ctx, merchantID, status, page, limit)
}

// SaveFareBreakdown mocks base method.
func (m *MockFoodOrderRepositoryInterface) SaveFareBreakdown(ctx context.Context, fb *model.FareBreakdown) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFareBreakdown", ctx, fb)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFareBreakdown indicates an expected call of SaveFareBreakdown.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) SaveFareBreakdown(ctx, fb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFareBreakdown", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).SaveFareBreakdown), ctx, fb)
}

// GetFareBreakdown mocks base method.
func (m *MockFoodOrderRepositoryInterface) GetFareBreakdown(ctx context.Context, orderID string) (*model.FareBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareBreakdown", ctx, orderID)
	ret0, _ := ret[0].(*model.FareBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFareBreakdown indicates an expected call of GetFareBreakdown.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) GetFareBreakdown(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareBreakdown", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).GetFareBreakdown), ctx, orderID)
}

// LogStateTransition mocks base method.
func (m *MockFoodOrderRepositoryInterface) LogStateTransition(ctx context.Context, log *model.FoodOrderStateLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogStateTransition", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogStateTransition indicates an expected call of LogStateTransition.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) LogStateTransition(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogStateTransition", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).LogStateTransition), ctx, log)
}

// SaveItems mocks base method.
func (m *MockFoodOrderRepositoryInterface) SaveItems(ctx context.Context, items []model.FoodOrderItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveItems", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveItems indicates an expected call of SaveItems.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) SaveItems(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveItems", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).SaveItems), ctx, items)
}

// GetItemsByOrderID mocks base method.
func (m *MockFoodOrderRepositoryInterface) GetItemsByOrderID(ctx context.Context, orderID string) ([]model.FoodOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]model.FoodOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsByOrderID indicates an expected call of GetItemsByOrderID.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) GetItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsByOrderID", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).GetItemsByOrderID), ctx, orderID)
}

// SetActiveOrder mocks base method.
func (m *MockFoodOrderRepositoryInterface) SetActiveOrder(ctx context.Context, userID, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveOrder", ctx, userID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActiveOrder indicates an expected call of SetActiveOrder.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) SetActiveOrder(ctx, userID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveOrder", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).SetActiveOrder), ctx, userID, orderID)
}

// GetActiveOrderID mocks base method.
func (m *MockFoodOrderRepositoryInterface) GetActiveOrderID(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrderID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrderID indicates an expected call of GetActiveOrderID.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) GetActiveOrderID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrderID", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).GetActiveOrderID), ctx, userID)
}

// ClearActiveOrder mocks base method.
func (m *MockFoodOrderRepositoryInterface) ClearActiveOrder(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearActiveOrder", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearActiveOrder indicates an expected call of ClearActiveOrder.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) ClearActiveOrder(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearActiveOrder", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).ClearActiveOrder), ctx, userID)
}

// AddToMerchantQueue mocks base method.
func (m *MockFoodOrderRepositoryInterface) AddToMerchantQueue(ctx context.Context, merchantID, orderID string, score float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToMerchantQueue", ctx, merchantID, orderID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToMerchantQueue indicates an expected call of AddToMerchantQueue.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) AddToMerchantQueue(ctx, merchantID, orderID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToMerchantQueue", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).AddToMerchantQueue), ctx, merchantID, orderID, score)
}

// RemoveFromMerchantQueue mocks base method.
func (m *MockFoodOrderRepositoryInterface) RemoveFromMerchantQueue(ctx context.Context, merchantID, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromMerchantQueue", ctx, merchantID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromMerchantQueue indicates an expected call of RemoveFromMerchantQueue.
func (mr *MockFoodOrderRepositoryInterfaceMockRecorder) RemoveFromMerchantQueue(ctx, merchantID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromMerchantQueue", reflect.TypeOf((*MockFoodOrderRepositoryInterface)(nil).RemoveFromMerchantQueue), ctx, merchantID, orderID)
}
