// Code generated by MockGen. DO NOT EDIT.
// Source: auth_service.go
//
// Generated by: mockgen -source=auth_service.go -destination=../../mocks/mock_auth_service.go -package=mocks

package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/auth-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockAuthServiceInterface) Register(ctx context.Context, req *service.RegisterRequest) (*service.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(*service.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceInterfaceMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceInterface)(nil).Register), ctx, req)
}

// RequestOTP mocks base method.
func (m *MockAuthServiceInterface) RequestOTP(ctx context.Context, req *service.OTPRequest) (*service.OTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestOTP", ctx, req)
	ret0, _ := ret[0].(*service.OTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestOTP indicates an expected call of RequestOTP.
func (mr *MockAuthServiceInterfaceMockRecorder) RequestOTP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestOTP", reflect.TypeOf((*MockAuthServiceInterface)(nil).RequestOTP), ctx, req)
}

// VerifyOTP mocks base method.
func (m *MockAuthServiceInterface) VerifyOTP(ctx context.Context, req *service.VerifyOTPRequest) (*service.VerifyOTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOTP", ctx, req)
	ret0, _ := ret[0].(*service.VerifyOTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyOTP indicates an expected call of VerifyOTP.
func (mr *MockAuthServiceInterfaceMockRecorder) VerifyOTP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOTP", reflect.TypeOf((*MockAuthServiceInterface)(nil).VerifyOTP), ctx, req)
}

// Login mocks base method.
func (m *MockAuthServiceInterface) Login(ctx context.Context, req *service.LoginRequest) (*service.AuthTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*service.AuthTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceInterfaceMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceInterface)(nil).Login), ctx, req)
}

// LoginWithOTP mocks base method.
func (m *MockAuthServiceInterface) LoginWithOTP(ctx context.Context, req *service.OTPLoginRequest) (*service.AuthTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithOTP", ctx, req)
	ret0, _ := ret[0].(*service.AuthTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginWithOTP indicates an expected call of LoginWithOTP.
func (mr *MockAuthServiceInterfaceMockRecorder) LoginWithOTP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithOTP", reflect.TypeOf((*MockAuthServiceInterface)(nil).LoginWithOTP), ctx, req)
}

// RefreshToken mocks base method.
func (m *MockAuthServiceInterface) RefreshToken(ctx context.Context, req *service.RefreshTokenRequest) (*service.AuthTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, req)
	ret0, _ := ret[0].(*service.AuthTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceInterfaceMockRecorder) RefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthServiceInterface)(nil).RefreshToken), ctx, req)
}

// Logout mocks base method.
func (m *MockAuthServiceInterface) Logout(ctx context.Context, userID string, req *service.LogoutRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInterfaceMockRecorder) Logout(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterface)(nil).Logout), ctx, userID, req)
}

// LogoutAll mocks base method.
func (m *MockAuthServiceInterface) LogoutAll(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutAll", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutAll indicates an expected call of LogoutAll.
func (mr *MockAuthServiceInterfaceMockRecorder) LogoutAll(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutAll", reflect.TypeOf((*MockAuthServiceInterface)(nil).LogoutAll), ctx, userID)
}

// ListSessions mocks base method.
func (m *MockAuthServiceInterface) ListSessions(ctx context.Context, userID string) ([]service.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, userID)
	ret0, _ := ret[0].([]service.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockAuthServiceInterfaceMockRecorder) ListSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockAuthServiceInterface)(nil).ListSessions), ctx, userID)
}

// RevokeSession mocks base method.
func (m *MockAuthServiceInterface) RevokeSession(ctx context.Context, userID, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockAuthServiceInterfaceMockRecorder) RevokeSession(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockAuthServiceInterface)(nil).RevokeSession), ctx, userID, sessionID)
}

// ForgotPassword mocks base method.
func (m *MockAuthServiceInterface) ForgotPassword(ctx context.Context, req *service.ForgotPasswordRequest) (*service.OTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, req)
	ret0, _ := ret[0].(*service.OTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockAuthServiceInterfaceMockRecorder) ForgotPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockAuthServiceInterface)(nil).ForgotPassword), ctx, req)
}

// ResetPassword mocks base method.
func (m *MockAuthServiceInterface) ResetPassword(ctx context.Context, req *service.ResetPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAuthServiceInterfaceMockRecorder) ResetPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAuthServiceInterface)(nil).ResetPassword), ctx, req)
}

// ChangePassword mocks base method.
func (m *MockAuthServiceInterface) ChangePassword(ctx context.Context, userID string, req *service.ChangePasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthServiceInterfaceMockRecorder) ChangePassword(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuthServiceInterface)(nil).ChangePassword), ctx, userID, req)
}
