// Code generated by MockGen. DO NOT EDIT.
// Source: user_repository.go
//
// Generated by this command:
//
//	mockgen -source=user_repository.go -destination=../../mocks/repomock/mock_user_repository.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/zicofarry/clay-app/backend/services/user-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// ApplyReferral mocks base method.
func (m *MockUserRepositoryInterface) ApplyReferral(ctx context.Context, userID, referredBy uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyReferral", ctx, userID, referredBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyReferral indicates an expected call of ApplyReferral.
func (mr *MockUserRepositoryInterfaceMockRecorder) ApplyReferral(ctx, userID, referredBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyReferral", reflect.TypeOf((*MockUserRepositoryInterface)(nil).ApplyReferral), ctx, userID, referredBy)
}

// CreateAddress mocks base method.
func (m *MockUserRepositoryInterface) CreateAddress(ctx context.Context, address *models.UserAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddress", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddress indicates an expected call of CreateAddress.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateAddress(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddress", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateAddress), ctx, address)
}

// CreateDriverDocument mocks base method.
func (m *MockUserRepositoryInterface) CreateDriverDocument(ctx context.Context, doc *models.DriverDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDriverDocument", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDriverDocument indicates an expected call of CreateDriverDocument.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateDriverDocument(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDriverDocument", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateDriverDocument), ctx, doc)
}

// CreateDriverProfile mocks base method.
func (m *MockUserRepositoryInterface) CreateDriverProfile(ctx context.Context, profile *models.DriverProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDriverProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDriverProfile indicates an expected call of CreateDriverProfile.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateDriverProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDriverProfile", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateDriverProfile), ctx, profile)
}

// CreateProfile mocks base method.
func (m *MockUserRepositoryInterface) CreateProfile(ctx context.Context, profile *models.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateProfile), ctx, profile)
}

// DeleteAddress mocks base method.
func (m *MockUserRepositoryInterface) DeleteAddress(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockUserRepositoryInterfaceMockRecorder) DeleteAddress(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockUserRepositoryInterface)(nil).DeleteAddress), ctx, id, userID)
}

// DeleteDriverDocument mocks base method.
func (m *MockUserRepositoryInterface) DeleteDriverDocument(ctx context.Context, id, driverID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDriverDocument", ctx, id, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDriverDocument indicates an expected call of DeleteDriverDocument.
func (mr *MockUserRepositoryInterfaceMockRecorder) DeleteDriverDocument(ctx, id, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDriverDocument", reflect.TypeOf((*MockUserRepositoryInterface)(nil).DeleteDriverDocument), ctx, id, driverID)
}

// GetAddress mocks base method.
func (m *MockUserRepositoryInterface) GetAddress(ctx context.Context, id uuid.UUID) (*models.UserAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddress", ctx, id)
	ret0, _ := ret[0].(*models.UserAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddress indicates an expected call of GetAddress.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetAddress(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddress", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetAddress), ctx, id)
}

// GetDriverDocument mocks base method.
func (m *MockUserRepositoryInterface) GetDriverDocument(ctx context.Context, id uuid.UUID) (*models.DriverDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverDocument", ctx, id)
	ret0, _ := ret[0].(*models.DriverDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverDocument indicates an expected call of GetDriverDocument.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetDriverDocument(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverDocument", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetDriverDocument), ctx, id)
}

// GetDriverProfileByID mocks base method.
func (m *MockUserRepositoryInterface) GetDriverProfileByID(ctx context.Context, driverID uuid.UUID) (*models.DriverProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverProfileByID", ctx, driverID)
	ret0, _ := ret[0].(*models.DriverProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverProfileByID indicates an expected call of GetDriverProfileByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetDriverProfileByID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverProfileByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetDriverProfileByID), ctx, driverID)
}

// GetDriverProfileByUserID mocks base method.
func (m *MockUserRepositoryInterface) GetDriverProfileByUserID(ctx context.Context, userID uuid.UUID) (*models.DriverProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverProfileByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.DriverProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverProfileByUserID indicates an expected call of GetDriverProfileByUserID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetDriverProfileByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverProfileByUserID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetDriverProfileByUserID), ctx, userID)
}

// GetProfileByUserID mocks base method.
func (m *MockUserRepositoryInterface) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUserID indicates an expected call of GetProfileByUserID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetProfileByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUserID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetProfileByUserID), ctx, userID)
}

// GetSettings mocks base method.
func (m *MockUserRepositoryInterface) GetSettings(ctx context.Context, userID uuid.UUID) (*models.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", ctx, userID)
	ret0, _ := ret[0].(*models.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetSettings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetSettings), ctx, userID)
}

// ListAddresses mocks base method.
func (m *MockUserRepositoryInterface) ListAddresses(ctx context.Context, userID uuid.UUID) ([]models.UserAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddresses", ctx, userID)
	ret0, _ := ret[0].([]models.UserAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddresses indicates an expected call of ListAddresses.
func (mr *MockUserRepositoryInterfaceMockRecorder) ListAddresses(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddresses", reflect.TypeOf((*MockUserRepositoryInterface)(nil).ListAddresses), ctx, userID)
}

// ListDriverDocuments mocks base method.
func (m *MockUserRepositoryInterface) ListDriverDocuments(ctx context.Context, driverID uuid.UUID) ([]models.DriverDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDriverDocuments", ctx, driverID)
	ret0, _ := ret[0].([]models.DriverDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDriverDocuments indicates an expected call of ListDriverDocuments.
func (mr *MockUserRepositoryInterfaceMockRecorder) ListDriverDocuments(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDriverDocuments", reflect.TypeOf((*MockUserRepositoryInterface)(nil).ListDriverDocuments), ctx, driverID)
}

// LookupUserByPhone mocks base method.
func (m *MockUserRepositoryInterface) LookupUserByPhone(ctx context.Context, phone string) (*models.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupUserByPhone", ctx, phone)
	ret0, _ := ret[0].(*models.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupUserByPhone indicates an expected call of LookupUserByPhone.
func (mr *MockUserRepositoryInterfaceMockRecorder) LookupUserByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupUserByPhone", reflect.TypeOf((*MockUserRepositoryInterface)(nil).LookupUserByPhone), ctx, phone)
}

// SetDefaultAddress mocks base method.
func (m *MockUserRepositoryInterface) SetDefaultAddress(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultAddress", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultAddress indicates an expected call of SetDefaultAddress.
func (mr *MockUserRepositoryInterfaceMockRecorder) SetDefaultAddress(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultAddress", reflect.TypeOf((*MockUserRepositoryInterface)(nil).SetDefaultAddress), ctx, id, userID)
}

// ToggleDriverOnline mocks base method.
func (m *MockUserRepositoryInterface) ToggleDriverOnline(ctx context.Context, driverID uuid.UUID, isOnline bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleDriverOnline", ctx, driverID, isOnline)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleDriverOnline indicates an expected call of ToggleDriverOnline.
func (mr *MockUserRepositoryInterfaceMockRecorder) ToggleDriverOnline(ctx, driverID, isOnline any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleDriverOnline", reflect.TypeOf((*MockUserRepositoryInterface)(nil).ToggleDriverOnline), ctx, driverID, isOnline)
}

// UpdateAddress mocks base method.
func (m *MockUserRepositoryInterface) UpdateAddress(ctx context.Context, address *models.UserAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateAddress(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateAddress), ctx, address)
}

// UpdateDriverDocumentStatus mocks base method.
func (m *MockUserRepositoryInterface) UpdateDriverDocumentStatus(ctx context.Context, id uuid.UUID, status, rejectionReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverDocumentStatus", ctx, id, status, rejectionReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDriverDocumentStatus indicates an expected call of UpdateDriverDocumentStatus.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateDriverDocumentStatus(ctx, id, status, rejectionReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverDocumentStatus", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateDriverDocumentStatus), ctx, id, status, rejectionReason)
}

// UpdateDriverProfile mocks base method.
func (m *MockUserRepositoryInterface) UpdateDriverProfile(ctx context.Context, profile *models.DriverProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDriverProfile indicates an expected call of UpdateDriverProfile.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateDriverProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverProfile", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateDriverProfile), ctx, profile)
}

// UpdateProfile mocks base method.
func (m *MockUserRepositoryInterface) UpdateProfile(ctx context.Context, profile *models.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateProfile), ctx, profile)
}

// UpdateSettings mocks base method.
func (m *MockUserRepositoryInterface) UpdateSettings(ctx context.Context, settings *models.UserSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateSettings), ctx, settings)
}
