// Code generated by MockGen. DO NOT EDIT.
// Source: audit_repository.go
//
// Generated by this command:
//
//	mockgen -source=audit_repository.go -destination=../../mocks/repomock/mock_audit_repository.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/audit-log-service/internal/repository"
	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditRepositoryInterface is a mock of AuditRepositoryInterface interface.
type MockAuditRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryInterfaceMockRecorder is the mock recorder for MockAuditRepositoryInterface.
type MockAuditRepositoryInterfaceMockRecorder struct {
	mock *MockAuditRepositoryInterface
}

// NewMockAuditRepositoryInterface creates a new mock instance.
func NewMockAuditRepositoryInterface(ctrl *gomock.Controller) *MockAuditRepositoryInterface {
	mock := &MockAuditRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepositoryInterface) EXPECT() *MockAuditRepositoryInterfaceMockRecorder {
	return m.recorder
}

// ExistsByEventID mocks base method.
func (m *MockAuditRepositoryInterface) ExistsByEventID(ctx context.Context, eventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEventID", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEventID indicates an expected call of ExistsByEventID.
func (mr *MockAuditRepositoryInterfaceMockRecorder) ExistsByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEventID", reflect.TypeOf((*MockAuditRepositoryInterface)(nil).ExistsByEventID), ctx, eventID)
}

// FindByID mocks base method.
func (m *MockAuditRepositoryInterface) FindByID(ctx context.Context, id primitive.ObjectID) (*repository.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*repository.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAuditRepositoryInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAuditRepositoryInterface)(nil).FindByID), ctx, id)
}

// Insert mocks base method.
func (m *MockAuditRepositoryInterface) Insert(ctx context.Context, log *repository.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAuditRepositoryInterfaceMockRecorder) Insert(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAuditRepositoryInterface)(nil).Insert), ctx, log)
}

// InsertBatch mocks base method.
func (m *MockAuditRepositoryInterface) InsertBatch(ctx context.Context, logs []any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBatch", ctx, logs)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertBatch indicates an expected call of InsertBatch.
func (mr *MockAuditRepositoryInterfaceMockRecorder) InsertBatch(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBatch", reflect.TypeOf((*MockAuditRepositoryInterface)(nil).InsertBatch), ctx, logs)
}

// Search mocks base method.
func (m *MockAuditRepositoryInterface) Search(ctx context.Context, filter bson.M, skip, limit int64) ([]*repository.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, filter, skip, limit)
	ret0, _ := ret[0].([]*repository.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockAuditRepositoryInterfaceMockRecorder) Search(ctx, filter, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockAuditRepositoryInterface)(nil).Search), ctx, filter, skip, limit)
}
