// Code generated by MockGen. DO NOT EDIT.
// Source: push_service.go
//
// Generated by this command:
//
//	mockgen -source=push_service.go -destination=../../mocks/mock_push_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/push-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockPushServiceInterface is a mock of PushServiceInterface interface.
type MockPushServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPushServiceInterfaceMockRecorder is the mock recorder for MockPushServiceInterface.
type MockPushServiceInterfaceMockRecorder struct {
	mock *MockPushServiceInterface
}

// NewMockPushServiceInterface creates a new mock instance.
func NewMockPushServiceInterface(ctrl *gomock.Controller) *MockPushServiceInterface {
	mock := &MockPushServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPushServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushServiceInterface) EXPECT() *MockPushServiceInterfaceMockRecorder {
	return m.recorder
}

// SendBatchPush mocks base method.
func (m *MockPushServiceInterface) SendBatchPush(ctx context.Context, req *service.SendBatchPushRequest) (*service.SendBatchPushResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatchPush", ctx, req)
	ret0, _ := ret[0].(*service.SendBatchPushResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendBatchPush indicates an expected call of SendBatchPush.
func (mr *MockPushServiceInterfaceMockRecorder) SendBatchPush(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatchPush", reflect.TypeOf((*MockPushServiceInterface)(nil).SendBatchPush), ctx, req)
}

// SendPush mocks base method.
func (m *MockPushServiceInterface) SendPush(ctx context.Context, req *service.SendPushRequest) (*service.SendPushResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPush", ctx, req)
	ret0, _ := ret[0].(*service.SendPushResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPush indicates an expected call of SendPush.
func (mr *MockPushServiceInterfaceMockRecorder) SendPush(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPush", reflect.TypeOf((*MockPushServiceInterface)(nil).SendPush), ctx, req)
}

// SendTopicPush mocks base method.
func (m *MockPushServiceInterface) SendTopicPush(ctx context.Context, topic string, req *service.SendTopicPushRequest) (*service.SendTopicPushResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTopicPush", ctx, topic, req)
	ret0, _ := ret[0].(*service.SendTopicPushResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTopicPush indicates an expected call of SendTopicPush.
func (mr *MockPushServiceInterfaceMockRecorder) SendTopicPush(ctx, topic, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTopicPush", reflect.TypeOf((*MockPushServiceInterface)(nil).SendTopicPush), ctx, topic, req)
}

// SubscribeTopic mocks base method.
func (m *MockPushServiceInterface) SubscribeTopic(ctx context.Context, topic string, req *service.TopicSubscribeRequest) (*service.TopicSubscribeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeTopic", ctx, topic, req)
	ret0, _ := ret[0].(*service.TopicSubscribeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeTopic indicates an expected call of SubscribeTopic.
func (mr *MockPushServiceInterfaceMockRecorder) SubscribeTopic(ctx, topic, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTopic", reflect.TypeOf((*MockPushServiceInterface)(nil).SubscribeTopic), ctx, topic, req)
}

// UnsubscribeTopic mocks base method.
func (m *MockPushServiceInterface) UnsubscribeTopic(ctx context.Context, topic string, req *service.TopicSubscribeRequest) (*service.TopicSubscribeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeTopic", ctx, topic, req)
	ret0, _ := ret[0].(*service.TopicSubscribeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsubscribeTopic indicates an expected call of UnsubscribeTopic.
func (mr *MockPushServiceInterfaceMockRecorder) UnsubscribeTopic(ctx, topic, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeTopic", reflect.TypeOf((*MockPushServiceInterface)(nil).UnsubscribeTopic), ctx, topic, req)
}
