// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go
//
// Generated by this command:
//
//	mockgen -source=user_service.go -destination=../../mocks/mock_user_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/zicofarry/clay-app/backend/services/user-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserServiceInterface is a mock of UserServiceInterface interface.
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface.
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance.
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// ApplyReferralCode mocks base method.
func (m *MockUserServiceInterface) ApplyReferralCode(ctx context.Context, userID uuid.UUID, referralCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyReferralCode", ctx, userID, referralCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyReferralCode indicates an expected call of ApplyReferralCode.
func (mr *MockUserServiceInterfaceMockRecorder) ApplyReferralCode(ctx, userID, referralCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyReferralCode", reflect.TypeOf((*MockUserServiceInterface)(nil).ApplyReferralCode), ctx, userID, referralCode)
}

// CreateAddress mocks base method.
func (m *MockUserServiceInterface) CreateAddress(ctx context.Context, userID uuid.UUID, req models.AddressRequest) (*models.AddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddress", ctx, userID, req)
	ret0, _ := ret[0].(*models.AddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAddress indicates an expected call of CreateAddress.
func (mr *MockUserServiceInterfaceMockRecorder) CreateAddress(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddress", reflect.TypeOf((*MockUserServiceInterface)(nil).CreateAddress), ctx, userID, req)
}

// CreateDriverProfile mocks base method.
func (m *MockUserServiceInterface) CreateDriverProfile(ctx context.Context, userID uuid.UUID, req models.CreateDriverProfileRequest) (*models.DriverProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDriverProfile", ctx, userID, req)
	ret0, _ := ret[0].(*models.DriverProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDriverProfile indicates an expected call of CreateDriverProfile.
func (mr *MockUserServiceInterfaceMockRecorder) CreateDriverProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDriverProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).CreateDriverProfile), ctx, userID, req)
}

// CreateProfile mocks base method.
func (m *MockUserServiceInterface) CreateProfile(ctx context.Context, userID uuid.UUID, req models.CreateProfileRequest) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, userID, req)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockUserServiceInterfaceMockRecorder) CreateProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).CreateProfile), ctx, userID, req)
}

// DeleteAddress mocks base method.
func (m *MockUserServiceInterface) DeleteAddress(ctx context.Context, userID, addressID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", ctx, userID, addressID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockUserServiceInterfaceMockRecorder) DeleteAddress(ctx, userID, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockUserServiceInterface)(nil).DeleteAddress), ctx, userID, addressID)
}

// DeleteDocument mocks base method.
func (m *MockUserServiceInterface) DeleteDocument(ctx context.Context, driverID, documentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDocument", ctx, driverID, documentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDocument indicates an expected call of DeleteDocument.
func (mr *MockUserServiceInterfaceMockRecorder) DeleteDocument(ctx, driverID, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDocument", reflect.TypeOf((*MockUserServiceInterface)(nil).DeleteDocument), ctx, driverID, documentID)
}

// GetDocument mocks base method.
func (m *MockUserServiceInterface) GetDocument(ctx context.Context, documentID uuid.UUID) (*models.DocumentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocument", ctx, documentID)
	ret0, _ := ret[0].(*models.DocumentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocument indicates an expected call of GetDocument.
func (mr *MockUserServiceInterfaceMockRecorder) GetDocument(ctx, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocument", reflect.TypeOf((*MockUserServiceInterface)(nil).GetDocument), ctx, documentID)
}

// GetDriverProfile mocks base method.
func (m *MockUserServiceInterface) GetDriverProfile(ctx context.Context, userID uuid.UUID) (*models.DriverProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverProfile", ctx, userID)
	ret0, _ := ret[0].(*models.DriverProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverProfile indicates an expected call of GetDriverProfile.
func (mr *MockUserServiceInterfaceMockRecorder) GetDriverProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).GetDriverProfile), ctx, userID)
}

// GetDriverVerificationStatus mocks base method.
func (m *MockUserServiceInterface) GetDriverVerificationStatus(ctx context.Context, driverID uuid.UUID) ([]models.DocumentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverVerificationStatus", ctx, driverID)
	ret0, _ := ret[0].([]models.DocumentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverVerificationStatus indicates an expected call of GetDriverVerificationStatus.
func (mr *MockUserServiceInterfaceMockRecorder) GetDriverVerificationStatus(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverVerificationStatus", reflect.TypeOf((*MockUserServiceInterface)(nil).GetDriverVerificationStatus), ctx, driverID)
}

// GetProfile mocks base method.
func (m *MockUserServiceInterface) GetProfile(ctx context.Context, userID uuid.UUID) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockUserServiceInterfaceMockRecorder) GetProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).GetProfile), ctx, userID)
}

// GetPublicDriverProfile mocks base method.
func (m *MockUserServiceInterface) GetPublicDriverProfile(ctx context.Context, driverID uuid.UUID) (*models.DriverPublicProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicDriverProfile", ctx, driverID)
	ret0, _ := ret[0].(*models.DriverPublicProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicDriverProfile indicates an expected call of GetPublicDriverProfile.
func (mr *MockUserServiceInterfaceMockRecorder) GetPublicDriverProfile(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicDriverProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).GetPublicDriverProfile), ctx, driverID)
}

// GetPublicProfile mocks base method.
func (m *MockUserServiceInterface) GetPublicProfile(ctx context.Context, targetUserID uuid.UUID) (*models.PublicProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicProfile", ctx, targetUserID)
	ret0, _ := ret[0].(*models.PublicProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicProfile indicates an expected call of GetPublicProfile.
func (mr *MockUserServiceInterfaceMockRecorder) GetPublicProfile(ctx, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).GetPublicProfile), ctx, targetUserID)
}

// GetSettings mocks base method.
func (m *MockUserServiceInterface) GetSettings(ctx context.Context, userID uuid.UUID) (*models.SettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", ctx, userID)
	ret0, _ := ret[0].(*models.SettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockUserServiceInterfaceMockRecorder) GetSettings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockUserServiceInterface)(nil).GetSettings), ctx, userID)
}

// ListAddresses mocks base method.
func (m *MockUserServiceInterface) ListAddresses(ctx context.Context, userID uuid.UUID) ([]models.AddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddresses", ctx, userID)
	ret0, _ := ret[0].([]models.AddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddresses indicates an expected call of ListAddresses.
func (mr *MockUserServiceInterfaceMockRecorder) ListAddresses(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddresses", reflect.TypeOf((*MockUserServiceInterface)(nil).ListAddresses), ctx, userID)
}

// ListDriverDocuments mocks base method.
func (m *MockUserServiceInterface) ListDriverDocuments(ctx context.Context, driverID uuid.UUID) ([]models.DocumentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDriverDocuments", ctx, driverID)
	ret0, _ := ret[0].([]models.DocumentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDriverDocuments indicates an expected call of ListDriverDocuments.
func (mr *MockUserServiceInterfaceMockRecorder) ListDriverDocuments(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDriverDocuments", reflect.TypeOf((*MockUserServiceInterface)(nil).ListDriverDocuments), ctx, driverID)
}

// LookupUserByPhone mocks base method.
func (m *MockUserServiceInterface) LookupUserByPhone(ctx context.Context, phone string) (*models.LookupUserByPhoneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupUserByPhone", ctx, phone)
	ret0, _ := ret[0].(*models.LookupUserByPhoneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupUserByPhone indicates an expected call of LookupUserByPhone.
func (mr *MockUserServiceInterfaceMockRecorder) LookupUserByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupUserByPhone", reflect.TypeOf((*MockUserServiceInterface)(nil).LookupUserByPhone), ctx, phone)
}

// SetDefaultAddress mocks base method.
func (m *MockUserServiceInterface) SetDefaultAddress(ctx context.Context, userID, addressID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultAddress", ctx, userID, addressID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultAddress indicates an expected call of SetDefaultAddress.
func (mr *MockUserServiceInterfaceMockRecorder) SetDefaultAddress(ctx, userID, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultAddress", reflect.TypeOf((*MockUserServiceInterface)(nil).SetDefaultAddress), ctx, userID, addressID)
}

// ToggleDriverOnline mocks base method.
func (m *MockUserServiceInterface) ToggleDriverOnline(ctx context.Context, driverID uuid.UUID, isOnline bool) (*models.DriverProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleDriverOnline", ctx, driverID, isOnline)
	ret0, _ := ret[0].(*models.DriverProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleDriverOnline indicates an expected call of ToggleDriverOnline.
func (mr *MockUserServiceInterfaceMockRecorder) ToggleDriverOnline(ctx, driverID, isOnline any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleDriverOnline", reflect.TypeOf((*MockUserServiceInterface)(nil).ToggleDriverOnline), ctx, driverID, isOnline)
}

// UpdateAddress mocks base method.
func (m *MockUserServiceInterface) UpdateAddress(ctx context.Context, userID, addressID uuid.UUID, req models.AddressRequest) (*models.AddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, userID, addressID, req)
	ret0, _ := ret[0].(*models.AddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockUserServiceInterfaceMockRecorder) UpdateAddress(ctx, userID, addressID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockUserServiceInterface)(nil).UpdateAddress), ctx, userID, addressID, req)
}

// UpdateDriverProfile mocks base method.
func (m *MockUserServiceInterface) UpdateDriverProfile(ctx context.Context, userID uuid.UUID, req models.UpdateDriverProfileRequest) (*models.DriverProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverProfile", ctx, userID, req)
	ret0, _ := ret[0].(*models.DriverProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDriverProfile indicates an expected call of UpdateDriverProfile.
func (mr *MockUserServiceInterfaceMockRecorder) UpdateDriverProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).UpdateDriverProfile), ctx, userID, req)
}

// UpdateProfile mocks base method.
func (m *MockUserServiceInterface) UpdateProfile(ctx context.Context, userID uuid.UUID, req models.UpdateProfileRequest) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, req)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserServiceInterfaceMockRecorder) UpdateProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).UpdateProfile), ctx, userID, req)
}

// UpdateSettings mocks base method.
func (m *MockUserServiceInterface) UpdateSettings(ctx context.Context, userID uuid.UUID, req models.UpdateSettingsRequest) (*models.SettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, userID, req)
	ret0, _ := ret[0].(*models.SettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockUserServiceInterfaceMockRecorder) UpdateSettings(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockUserServiceInterface)(nil).UpdateSettings), ctx, userID, req)
}

// UploadDocument mocks base method.
func (m *MockUserServiceInterface) UploadDocument(ctx context.Context, driverID uuid.UUID, docType, fileURL string) (*models.DocumentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadDocument", ctx, driverID, docType, fileURL)
	ret0, _ := ret[0].(*models.DocumentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadDocument indicates an expected call of UploadDocument.
func (mr *MockUserServiceInterfaceMockRecorder) UploadDocument(ctx, driverID, docType, fileURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadDocument", reflect.TypeOf((*MockUserServiceInterface)(nil).UploadDocument), ctx, driverID, docType, fileURL)
}

// VerifyDocument mocks base method.
func (m *MockUserServiceInterface) VerifyDocument(ctx context.Context, documentID uuid.UUID, status, rejectionReason string) (*models.DocumentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDocument", ctx, documentID, status, rejectionReason)
	ret0, _ := ret[0].(*models.DocumentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyDocument indicates an expected call of VerifyDocument.
func (mr *MockUserServiceInterfaceMockRecorder) VerifyDocument(ctx, documentID, status, rejectionReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDocument", reflect.TypeOf((*MockUserServiceInterface)(nil).VerifyDocument), ctx, documentID, status, rejectionReason)
}
