// Code generated by MockGen. DO NOT EDIT.
// Source: chat_service.go
//
// Generated by this command:
//
//	mockgen -source=chat_service.go -destination=../../mocks/chat_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/chat-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockChatServiceInterface is a mock of ChatServiceInterface interface.
type MockChatServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockChatServiceInterfaceMockRecorder is the mock recorder for MockChatServiceInterface.
type MockChatServiceInterfaceMockRecorder struct {
	mock *MockChatServiceInterface
}

// NewMockChatServiceInterface creates a new mock instance.
func NewMockChatServiceInterface(ctrl *gomock.Controller) *MockChatServiceInterface {
	mock := &MockChatServiceInterface{ctrl: ctrl}
	mock.recorder = &MockChatServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatServiceInterface) EXPECT() *MockChatServiceInterfaceMockRecorder {
	return m.recorder
}

// GetRoomByID mocks base method.
func (m *MockChatServiceInterface) GetRoomByID(ctx context.Context, roomID, participantID string) (*service.ChatRoomWithPreviewDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByID", ctx, roomID, participantID)
	ret0, _ := ret[0].(*service.ChatRoomWithPreviewDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByID indicates an expected call of GetRoomByID.
func (mr *MockChatServiceInterfaceMockRecorder) GetRoomByID(ctx, roomID, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByID", reflect.TypeOf((*MockChatServiceInterface)(nil).GetRoomByID), ctx, roomID, participantID)
}

// GetRoomByOrderID mocks base method.
func (m *MockChatServiceInterface) GetRoomByOrderID(ctx context.Context, orderID, participantID string) (*service.ChatRoomWithPreviewDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByOrderID", ctx, orderID, participantID)
	ret0, _ := ret[0].(*service.ChatRoomWithPreviewDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByOrderID indicates an expected call of GetRoomByOrderID.
func (mr *MockChatServiceInterfaceMockRecorder) GetRoomByOrderID(ctx, orderID, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByOrderID", reflect.TypeOf((*MockChatServiceInterface)(nil).GetRoomByOrderID), ctx, orderID, participantID)
}

// GetUnreadCount mocks base method.
func (m *MockChatServiceInterface) GetUnreadCount(ctx context.Context, roomID, participantID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadCount", ctx, roomID, participantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadCount indicates an expected call of GetUnreadCount.
func (mr *MockChatServiceInterfaceMockRecorder) GetUnreadCount(ctx, roomID, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadCount", reflect.TypeOf((*MockChatServiceInterface)(nil).GetUnreadCount), ctx, roomID, participantID)
}

// InternalAssignDriver mocks base method.
func (m *MockChatServiceInterface) InternalAssignDriver(ctx context.Context, orderID, driverID string) (*service.ChatRoomDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalAssignDriver", ctx, orderID, driverID)
	ret0, _ := ret[0].(*service.ChatRoomDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalAssignDriver indicates an expected call of InternalAssignDriver.
func (mr *MockChatServiceInterfaceMockRecorder) InternalAssignDriver(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalAssignDriver", reflect.TypeOf((*MockChatServiceInterface)(nil).InternalAssignDriver), ctx, orderID, driverID)
}

// InternalCloseRoom mocks base method.
func (m *MockChatServiceInterface) InternalCloseRoom(ctx context.Context, roomID string) (*service.ChatRoomDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalCloseRoom", ctx, roomID)
	ret0, _ := ret[0].(*service.ChatRoomDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalCloseRoom indicates an expected call of InternalCloseRoom.
func (mr *MockChatServiceInterfaceMockRecorder) InternalCloseRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalCloseRoom", reflect.TypeOf((*MockChatServiceInterface)(nil).InternalCloseRoom), ctx, roomID)
}

// InternalCreateRoom mocks base method.
func (m *MockChatServiceInterface) InternalCreateRoom(ctx context.Context, orderID, orderType, userID string, driverID *string) (*service.ChatRoomDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalCreateRoom", ctx, orderID, orderType, userID, driverID)
	ret0, _ := ret[0].(*service.ChatRoomDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalCreateRoom indicates an expected call of InternalCreateRoom.
func (mr *MockChatServiceInterfaceMockRecorder) InternalCreateRoom(ctx, orderID, orderType, userID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalCreateRoom", reflect.TypeOf((*MockChatServiceInterface)(nil).InternalCreateRoom), ctx, orderID, orderType, userID, driverID)
}

// ListMessages mocks base method.
func (m *MockChatServiceInterface) ListMessages(ctx context.Context, roomID, participantID, beforeID string, limit int) ([]service.MessageDTO, *service.MessageListMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, roomID, participantID, beforeID, limit)
	ret0, _ := ret[0].([]service.MessageDTO)
	ret1, _ := ret[1].(*service.MessageListMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockChatServiceInterfaceMockRecorder) ListMessages(ctx, roomID, participantID, beforeID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockChatServiceInterface)(nil).ListMessages), ctx, roomID, participantID, beforeID, limit)
}

// ListMyRooms mocks base method.
func (m *MockChatServiceInterface) ListMyRooms(ctx context.Context, userID, status string, page, limit int) ([]service.ChatRoomWithPreviewDTO, *service.PaginationMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyRooms", ctx, userID, status, page, limit)
	ret0, _ := ret[0].([]service.ChatRoomWithPreviewDTO)
	ret1, _ := ret[1].(*service.PaginationMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMyRooms indicates an expected call of ListMyRooms.
func (mr *MockChatServiceInterfaceMockRecorder) ListMyRooms(ctx, userID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyRooms", reflect.TypeOf((*MockChatServiceInterface)(nil).ListMyRooms), ctx, userID, status, page, limit)
}

// MarkMessagesAsRead mocks base method.
func (m *MockChatServiceInterface) MarkMessagesAsRead(ctx context.Context, roomID, participantID, upToMessageID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessagesAsRead", ctx, roomID, participantID, upToMessageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkMessagesAsRead indicates an expected call of MarkMessagesAsRead.
func (mr *MockChatServiceInterfaceMockRecorder) MarkMessagesAsRead(ctx, roomID, participantID, upToMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessagesAsRead", reflect.TypeOf((*MockChatServiceInterface)(nil).MarkMessagesAsRead), ctx, roomID, participantID, upToMessageID)
}

// SendMessage mocks base method.
func (m *MockChatServiceInterface) SendMessage(ctx context.Context, roomID, senderID, senderRole, content, msgType string, clientID *string) (*service.MessageDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, roomID, senderID, senderRole, content, msgType, clientID)
	ret0, _ := ret[0].(*service.MessageDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatServiceInterfaceMockRecorder) SendMessage(ctx, roomID, senderID, senderRole, content, msgType, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatServiceInterface)(nil).SendMessage), ctx, roomID, senderID, senderRole, content, msgType, clientID)
}
