// Code generated by MockGen. DO NOT EDIT.
// Source: merchant_service.go
//
// Generated by: mockgen -source=merchant_service.go -destination=../../mocks/mock_merchant_service.go -package=mocks

package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/zicofarry/clay-app/backend/services/merchant-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMerchantServiceInterface is a mock of MerchantServiceInterface interface.
type MockMerchantServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantServiceInterfaceMockRecorder
}

// MockMerchantServiceInterfaceMockRecorder is the mock recorder for MockMerchantServiceInterface.
type MockMerchantServiceInterfaceMockRecorder struct {
	mock *MockMerchantServiceInterface
}

// NewMockMerchantServiceInterface creates a new mock instance.
func NewMockMerchantServiceInterface(ctrl *gomock.Controller) *MockMerchantServiceInterface {
	mock := &MockMerchantServiceInterface{ctrl: ctrl}
	mock.recorder = &MockMerchantServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantServiceInterface) EXPECT() *MockMerchantServiceInterfaceMockRecorder {
	return m.recorder
}

// ── Merchant ──────────────────────────────────────────────────────────────────

// RegisterMerchant mocks base method.
func (m *MockMerchantServiceInterface) RegisterMerchant(ctx context.Context, userID string, req model.RegisterMerchantRequest) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterMerchant", ctx, userID, req)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) RegisterMerchant(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterMerchant", reflect.TypeOf((*MockMerchantServiceInterface)(nil).RegisterMerchant), ctx, userID, req)
}

// GetMyMerchant mocks base method.
func (m *MockMerchantServiceInterface) GetMyMerchant(ctx context.Context, userID string) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyMerchant", ctx, userID)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) GetMyMerchant(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyMerchant", reflect.TypeOf((*MockMerchantServiceInterface)(nil).GetMyMerchant), ctx, userID)
}

// UpdateMyMerchant mocks base method.
func (m *MockMerchantServiceInterface) UpdateMyMerchant(ctx context.Context, userID string, req model.UpdateMerchantRequest) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMyMerchant", ctx, userID, req)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) UpdateMyMerchant(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMyMerchant", reflect.TypeOf((*MockMerchantServiceInterface)(nil).UpdateMyMerchant), ctx, userID, req)
}

// GetMerchantByID mocks base method.
func (m *MockMerchantServiceInterface) GetMerchantByID(ctx context.Context, merchantID string) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByID", ctx, merchantID)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) GetMerchantByID(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByID", reflect.TypeOf((*MockMerchantServiceInterface)(nil).GetMerchantByID), ctx, merchantID)
}

// UpdateMerchantStatus mocks base method.
func (m *MockMerchantServiceInterface) UpdateMerchantStatus(ctx context.Context, merchantID, callerUserID string, req model.UpdateMerchantStatusRequest) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMerchantStatus", ctx, merchantID, callerUserID, req)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) UpdateMerchantStatus(ctx, merchantID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMerchantStatus", reflect.TypeOf((*MockMerchantServiceInterface)(nil).UpdateMerchantStatus), ctx, merchantID, callerUserID, req)
}

// IsOpen mocks base method.
func (m *MockMerchantServiceInterface) IsOpen(ctx context.Context, merchantID string) (*model.IsOpenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOpen", ctx, merchantID)
	ret0, _ := ret[0].(*model.IsOpenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) IsOpen(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOpen", reflect.TypeOf((*MockMerchantServiceInterface)(nil).IsOpen), ctx, merchantID)
}

// ── Operating Hours ───────────────────────────────────────────────────────────

// GetOperatingHours mocks base method.
func (m *MockMerchantServiceInterface) GetOperatingHours(ctx context.Context, merchantID string) ([]model.OperatingHours, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatingHours", ctx, merchantID)
	ret0, _ := ret[0].([]model.OperatingHours)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) GetOperatingHours(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatingHours", reflect.TypeOf((*MockMerchantServiceInterface)(nil).GetOperatingHours), ctx, merchantID)
}

// UpsertOperatingHours mocks base method.
func (m *MockMerchantServiceInterface) UpsertOperatingHours(ctx context.Context, merchantID, callerUserID string, req model.UpsertOperatingHoursRequest) ([]model.OperatingHours, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOperatingHours", ctx, merchantID, callerUserID, req)
	ret0, _ := ret[0].([]model.OperatingHours)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) UpsertOperatingHours(ctx, merchantID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOperatingHours", reflect.TypeOf((*MockMerchantServiceInterface)(nil).UpsertOperatingHours), ctx, merchantID, callerUserID, req)
}

// ── Bank Accounts ─────────────────────────────────────────────────────────────

// ListBankAccounts mocks base method.
func (m *MockMerchantServiceInterface) ListBankAccounts(ctx context.Context, merchantID, callerUserID string) ([]model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBankAccounts", ctx, merchantID, callerUserID)
	ret0, _ := ret[0].([]model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) ListBankAccounts(ctx, merchantID, callerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBankAccounts", reflect.TypeOf((*MockMerchantServiceInterface)(nil).ListBankAccounts), ctx, merchantID, callerUserID)
}

// AddBankAccount mocks base method.
func (m *MockMerchantServiceInterface) AddBankAccount(ctx context.Context, merchantID, callerUserID string, req model.AddBankAccountRequest) (*model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBankAccount", ctx, merchantID, callerUserID, req)
	ret0, _ := ret[0].(*model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) AddBankAccount(ctx, merchantID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBankAccount", reflect.TypeOf((*MockMerchantServiceInterface)(nil).AddBankAccount), ctx, merchantID, callerUserID, req)
}

// DeleteBankAccount mocks base method.
func (m *MockMerchantServiceInterface) DeleteBankAccount(ctx context.Context, merchantID, accountID, callerUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankAccount", ctx, merchantID, accountID, callerUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockMerchantServiceInterfaceMockRecorder) DeleteBankAccount(ctx, merchantID, accountID, callerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankAccount", reflect.TypeOf((*MockMerchantServiceInterface)(nil).DeleteBankAccount), ctx, merchantID, accountID, callerUserID)
}

// SetPrimaryBankAccount mocks base method.
func (m *MockMerchantServiceInterface) SetPrimaryBankAccount(ctx context.Context, merchantID, accountID, callerUserID string) (*model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimaryBankAccount", ctx, merchantID, accountID, callerUserID)
	ret0, _ := ret[0].(*model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) SetPrimaryBankAccount(ctx, merchantID, accountID, callerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimaryBankAccount", reflect.TypeOf((*MockMerchantServiceInterface)(nil).SetPrimaryBankAccount), ctx, merchantID, accountID, callerUserID)
}

// ── Menu Categories ───────────────────────────────────────────────────────────

// ListCategories mocks base method.
func (m *MockMerchantServiceInterface) ListCategories(ctx context.Context, merchantID string) ([]model.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, merchantID)
	ret0, _ := ret[0].([]model.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) ListCategories(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockMerchantServiceInterface)(nil).ListCategories), ctx, merchantID)
}

// CreateCategory mocks base method.
func (m *MockMerchantServiceInterface) CreateCategory(ctx context.Context, merchantID, callerUserID string, req model.CreateMenuCategoryRequest) (*model.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, merchantID, callerUserID, req)
	ret0, _ := ret[0].(*model.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) CreateCategory(ctx, merchantID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockMerchantServiceInterface)(nil).CreateCategory), ctx, merchantID, callerUserID, req)
}

// UpdateCategory mocks base method.
func (m *MockMerchantServiceInterface) UpdateCategory(ctx context.Context, merchantID, categoryID, callerUserID string, req model.UpdateMenuCategoryRequest) (*model.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, merchantID, categoryID, callerUserID, req)
	ret0, _ := ret[0].(*model.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) UpdateCategory(ctx, merchantID, categoryID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockMerchantServiceInterface)(nil).UpdateCategory), ctx, merchantID, categoryID, callerUserID, req)
}

// DeleteCategory mocks base method.
func (m *MockMerchantServiceInterface) DeleteCategory(ctx context.Context, merchantID, categoryID, callerUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, merchantID, categoryID, callerUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockMerchantServiceInterfaceMockRecorder) DeleteCategory(ctx, merchantID, categoryID, callerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockMerchantServiceInterface)(nil).DeleteCategory), ctx, merchantID, categoryID, callerUserID)
}

// ReorderCategories mocks base method.
func (m *MockMerchantServiceInterface) ReorderCategories(ctx context.Context, merchantID, callerUserID string, req model.ReorderCategoriesRequest) ([]model.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderCategories", ctx, merchantID, callerUserID, req)
	ret0, _ := ret[0].([]model.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) ReorderCategories(ctx, merchantID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderCategories", reflect.TypeOf((*MockMerchantServiceInterface)(nil).ReorderCategories), ctx, merchantID, callerUserID, req)
}

// ── Menu Items ────────────────────────────────────────────────────────────────

// ListItems mocks base method.
func (m *MockMerchantServiceInterface) ListItems(ctx context.Context, merchantID, categoryID string, isAvailable *bool) ([]model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, merchantID, categoryID, isAvailable)
	ret0, _ := ret[0].([]model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) ListItems(ctx, merchantID, categoryID, isAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockMerchantServiceInterface)(nil).ListItems), ctx, merchantID, categoryID, isAvailable)
}

// CreateItem mocks base method.
func (m *MockMerchantServiceInterface) CreateItem(ctx context.Context, merchantID, callerUserID string, req model.CreateMenuItemRequest) (*model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, merchantID, callerUserID, req)
	ret0, _ := ret[0].(*model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) CreateItem(ctx, merchantID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockMerchantServiceInterface)(nil).CreateItem), ctx, merchantID, callerUserID, req)
}

// GetItem mocks base method.
func (m *MockMerchantServiceInterface) GetItem(ctx context.Context, merchantID, itemID string) (*model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, merchantID, itemID)
	ret0, _ := ret[0].(*model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) GetItem(ctx, merchantID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockMerchantServiceInterface)(nil).GetItem), ctx, merchantID, itemID)
}

// UpdateItem mocks base method.
func (m *MockMerchantServiceInterface) UpdateItem(ctx context.Context, merchantID, itemID, callerUserID string, req model.UpdateMenuItemRequest) (*model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, merchantID, itemID, callerUserID, req)
	ret0, _ := ret[0].(*model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) UpdateItem(ctx, merchantID, itemID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockMerchantServiceInterface)(nil).UpdateItem), ctx, merchantID, itemID, callerUserID, req)
}

// DeleteItem mocks base method.
func (m *MockMerchantServiceInterface) DeleteItem(ctx context.Context, merchantID, itemID, callerUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, merchantID, itemID, callerUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockMerchantServiceInterfaceMockRecorder) DeleteItem(ctx, merchantID, itemID, callerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockMerchantServiceInterface)(nil).DeleteItem), ctx, merchantID, itemID, callerUserID)
}

// ToggleAvailability mocks base method.
func (m *MockMerchantServiceInterface) ToggleAvailability(ctx context.Context, merchantID, itemID, callerUserID string, req model.ToggleAvailabilityRequest) (*model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleAvailability", ctx, merchantID, itemID, callerUserID, req)
	ret0, _ := ret[0].(*model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) ToggleAvailability(ctx, merchantID, itemID, callerUserID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAvailability", reflect.TypeOf((*MockMerchantServiceInterface)(nil).ToggleAvailability), ctx, merchantID, itemID, callerUserID, req)
}

// BatchGetItems mocks base method.
func (m *MockMerchantServiceInterface) BatchGetItems(ctx context.Context, req model.BatchGetMenuItemsRequest) ([]model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetItems", ctx, req)
	ret0, _ := ret[0].([]model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantServiceInterfaceMockRecorder) BatchGetItems(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetItems", reflect.TypeOf((*MockMerchantServiceInterface)(nil).BatchGetItems), ctx, req)
}
