// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	context "context"
	reflect "reflect"

	cache "github.com/zicofarry/clay-app/backend/services/tracking-service/internal/cache"
	repository "github.com/zicofarry/clay-app/backend/services/tracking-service/internal/repository"
	service "github.com/zicofarry/clay-app/backend/services/tracking-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

type MockTrackingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingServiceInterfaceMockRecorder
}
type MockTrackingServiceInterfaceMockRecorder struct{ mock *MockTrackingServiceInterface }

func NewMockTrackingServiceInterface(ctrl *gomock.Controller) *MockTrackingServiceInterface {
	m := &MockTrackingServiceInterface{ctrl: ctrl}
	m.recorder = &MockTrackingServiceInterfaceMockRecorder{m}
	return m
}
func (m *MockTrackingServiceInterface) EXPECT() *MockTrackingServiceInterfaceMockRecorder {
	return m.recorder
}

func (m *MockTrackingServiceInterface) GetOrderPosition(ctx context.Context, orderID string) (*cache.OrderPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderPosition", ctx, orderID)
	ret0, _ := ret[0].(*cache.OrderPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockTrackingServiceInterfaceMockRecorder) GetOrderPosition(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderPosition", reflect.TypeOf((*MockTrackingServiceInterface)(nil).GetOrderPosition), ctx, orderID)
}

func (m *MockTrackingServiceInterface) GetOrderETA(ctx context.Context, orderID string) (*service.ETAResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderETA", ctx, orderID)
	ret0, _ := ret[0].(*service.ETAResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockTrackingServiceInterfaceMockRecorder) GetOrderETA(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderETA", reflect.TypeOf((*MockTrackingServiceInterface)(nil).GetOrderETA), ctx, orderID)
}

func (m *MockTrackingServiceInterface) GetOrderRoute(ctx context.Context, orderID string) (*service.RouteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderRoute", ctx, orderID)
	ret0, _ := ret[0].(*service.RouteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockTrackingServiceInterfaceMockRecorder) GetOrderRoute(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderRoute", reflect.TypeOf((*MockTrackingServiceInterface)(nil).GetOrderRoute), ctx, orderID)
}

func (m *MockTrackingServiceInterface) GetTripRoute(ctx context.Context, orderID string) (*repository.TripRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripRoute", ctx, orderID)
	ret0, _ := ret[0].(*repository.TripRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockTrackingServiceInterfaceMockRecorder) GetTripRoute(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripRoute", reflect.TypeOf((*MockTrackingServiceInterface)(nil).GetTripRoute), ctx, orderID)
}

func (m *MockTrackingServiceInterface) StartTracking(ctx context.Context, req *service.StartTrackingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTracking", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockTrackingServiceInterfaceMockRecorder) StartTracking(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTracking", reflect.TypeOf((*MockTrackingServiceInterface)(nil).StartTracking), ctx, req)
}

func (m *MockTrackingServiceInterface) StopTracking(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopTracking", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockTrackingServiceInterfaceMockRecorder) StopTracking(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopTracking", reflect.TypeOf((*MockTrackingServiceInterface)(nil).StopTracking), ctx, orderID)
}

func (m *MockTrackingServiceInterface) PushLocationUpdate(ctx context.Context, orderID string, req *service.LocationUpdateEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushLocationUpdate", ctx, orderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockTrackingServiceInterfaceMockRecorder) PushLocationUpdate(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushLocationUpdate", reflect.TypeOf((*MockTrackingServiceInterface)(nil).PushLocationUpdate), ctx, orderID, req)
}
