// Code generated by MockGen. DO NOT EDIT.
// Source: history_repository.go
//
// Generated by this command:
//
//	mockgen -source=history_repository.go -destination=../../mocks/repomock/history_repository_mock.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	repository "github.com/zicofarry/clay-app/backend/services/history-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoryRepositoryInterface is a mock of HistoryRepositoryInterface interface.
type MockHistoryRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockHistoryRepositoryInterfaceMockRecorder is the mock recorder for MockHistoryRepositoryInterface.
type MockHistoryRepositoryInterfaceMockRecorder struct {
	mock *MockHistoryRepositoryInterface
}

// NewMockHistoryRepositoryInterface creates a new mock instance.
func NewMockHistoryRepositoryInterface(ctrl *gomock.Controller) *MockHistoryRepositoryInterface {
	mock := &MockHistoryRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockHistoryRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryRepositoryInterface) EXPECT() *MockHistoryRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateActivityFeed mocks base method.
func (m *MockHistoryRepositoryInterface) CreateActivityFeed(ctx context.Context, feed *repository.ActivityFeed) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivityFeed", ctx, feed)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateActivityFeed indicates an expected call of CreateActivityFeed.
func (mr *MockHistoryRepositoryInterfaceMockRecorder) CreateActivityFeed(ctx, feed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivityFeed", reflect.TypeOf((*MockHistoryRepositoryInterface)(nil).CreateActivityFeed), ctx, feed)
}

// CreateOrUpdateOrderHistory mocks base method.
func (m *MockHistoryRepositoryInterface) CreateOrUpdateOrderHistory(ctx context.Context, history *repository.OrderHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateOrderHistory", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateOrderHistory indicates an expected call of CreateOrUpdateOrderHistory.
func (mr *MockHistoryRepositoryInterfaceMockRecorder) CreateOrUpdateOrderHistory(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateOrderHistory", reflect.TypeOf((*MockHistoryRepositoryInterface)(nil).CreateOrUpdateOrderHistory), ctx, history)
}

// GetActivityFeedByID mocks base method.
func (m *MockHistoryRepositoryInterface) GetActivityFeedByID(ctx context.Context, id uuid.UUID) (*repository.ActivityFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityFeedByID", ctx, id)
	ret0, _ := ret[0].(*repository.ActivityFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityFeedByID indicates an expected call of GetActivityFeedByID.
func (mr *MockHistoryRepositoryInterfaceMockRecorder) GetActivityFeedByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityFeedByID", reflect.TypeOf((*MockHistoryRepositoryInterface)(nil).GetActivityFeedByID), ctx, id)
}

// GetOrderHistoryByID mocks base method.
func (m *MockHistoryRepositoryInterface) GetOrderHistoryByID(ctx context.Context, id uuid.UUID) (*repository.OrderHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderHistoryByID", ctx, id)
	ret0, _ := ret[0].(*repository.OrderHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderHistoryByID indicates an expected call of GetOrderHistoryByID.
func (mr *MockHistoryRepositoryInterfaceMockRecorder) GetOrderHistoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderHistoryByID", reflect.TypeOf((*MockHistoryRepositoryInterface)(nil).GetOrderHistoryByID), ctx, id)
}

// GetOrderHistoryByOrderID mocks base method.
func (m *MockHistoryRepositoryInterface) GetOrderHistoryByOrderID(ctx context.Context, orderID uuid.UUID) (*repository.OrderHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderHistoryByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*repository.OrderHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderHistoryByOrderID indicates an expected call of GetOrderHistoryByOrderID.
func (mr *MockHistoryRepositoryInterfaceMockRecorder) GetOrderHistoryByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderHistoryByOrderID", reflect.TypeOf((*MockHistoryRepositoryInterface)(nil).GetOrderHistoryByOrderID), ctx, orderID)
}

// ListActivityFeedByUser mocks base method.
func (m *MockHistoryRepositoryInterface) ListActivityFeedByUser(ctx context.Context, userID uuid.UUID, eventType string, limit int, beforeCreatedAt *time.Time) ([]repository.ActivityFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivityFeedByUser", ctx, userID, eventType, limit, beforeCreatedAt)
	ret0, _ := ret[0].([]repository.ActivityFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActivityFeedByUser indicates an expected call of ListActivityFeedByUser.
func (mr *MockHistoryRepositoryInterfaceMockRecorder) ListActivityFeedByUser(ctx, userID, eventType, limit, beforeCreatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivityFeedByUser", reflect.TypeOf((*MockHistoryRepositoryInterface)(nil).ListActivityFeedByUser), ctx, userID, eventType, limit, beforeCreatedAt)
}

// ListOrderHistoryByDriver mocks base method.
func (m *MockHistoryRepositoryInterface) ListOrderHistoryByDriver(ctx context.Context, driverID uuid.UUID, orderType, status string, limit, offset int) ([]repository.OrderHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrderHistoryByDriver", ctx, driverID, orderType, status, limit, offset)
	ret0, _ := ret[0].([]repository.OrderHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrderHistoryByDriver indicates an expected call of ListOrderHistoryByDriver.
func (mr *MockHistoryRepositoryInterfaceMockRecorder) ListOrderHistoryByDriver(ctx, driverID, orderType, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrderHistoryByDriver", reflect.TypeOf((*MockHistoryRepositoryInterface)(nil).ListOrderHistoryByDriver), ctx, driverID, orderType, status, limit, offset)
}

// ListOrderHistoryByUser mocks base method.
func (m *MockHistoryRepositoryInterface) ListOrderHistoryByUser(ctx context.Context, userID uuid.UUID, orderType, status string, limit, offset int) ([]repository.OrderHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrderHistoryByUser", ctx, userID, orderType, status, limit, offset)
	ret0, _ := ret[0].([]repository.OrderHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrderHistoryByUser indicates an expected call of ListOrderHistoryByUser.
func (mr *MockHistoryRepositoryInterfaceMockRecorder) ListOrderHistoryByUser(ctx, userID, orderType, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrderHistoryByUser", reflect.TypeOf((*MockHistoryRepositoryInterface)(nil).ListOrderHistoryByUser), ctx, userID, orderType, status, limit, offset)
}
