// Code generated by MockGen. DO NOT EDIT.
// Source: sms_repository.go
//
// Generated by this command:
//
//	mockgen -source=sms_repository.go -destination=../../mocks/repomock/mock_sms_repository.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockSMSRepositoryInterface is a mock of SMSRepositoryInterface interface.
type MockSMSRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSMSRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSMSRepositoryInterfaceMockRecorder is the mock recorder for MockSMSRepositoryInterface.
type MockSMSRepositoryInterfaceMockRecorder struct {
	mock *MockSMSRepositoryInterface
}

// NewMockSMSRepositoryInterface creates a new mock instance.
func NewMockSMSRepositoryInterface(ctrl *gomock.Controller) *MockSMSRepositoryInterface {
	mock := &MockSMSRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSMSRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMSRepositoryInterface) EXPECT() *MockSMSRepositoryInterfaceMockRecorder {
	return m.recorder
}

// DeleteOTP mocks base method.
func (m *MockSMSRepositoryInterface) DeleteOTP(ctx context.Context, phone, purpose string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOTP", ctx, phone, purpose)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOTP indicates an expected call of DeleteOTP.
func (mr *MockSMSRepositoryInterfaceMockRecorder) DeleteOTP(ctx, phone, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOTP", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).DeleteOTP), ctx, phone, purpose)
}

// DeleteRetryMessage mocks base method.
func (m *MockSMSRepositoryInterface) DeleteRetryMessage(ctx context.Context, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRetryMessage", ctx, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRetryMessage indicates an expected call of DeleteRetryMessage.
func (mr *MockSMSRepositoryInterfaceMockRecorder) DeleteRetryMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRetryMessage", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).DeleteRetryMessage), ctx, messageID)
}

// GetOTP mocks base method.
func (m *MockSMSRepositoryInterface) GetOTP(ctx context.Context, phone, purpose string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOTP", ctx, phone, purpose)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOTP indicates an expected call of GetOTP.
func (mr *MockSMSRepositoryInterfaceMockRecorder) GetOTP(ctx, phone, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOTP", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).GetOTP), ctx, phone, purpose)
}

// GetRateLimit mocks base method.
func (m *MockSMSRepositoryInterface) GetRateLimit(ctx context.Context, phone string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateLimit", ctx, phone)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRateLimit indicates an expected call of GetRateLimit.
func (mr *MockSMSRepositoryInterfaceMockRecorder) GetRateLimit(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateLimit", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).GetRateLimit), ctx, phone)
}

// GetRetryMessage mocks base method.
func (m *MockSMSRepositoryInterface) GetRetryMessage(ctx context.Context, messageID string) (string, string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetryMessage", ctx, messageID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetRetryMessage indicates an expected call of GetRetryMessage.
func (mr *MockSMSRepositoryInterfaceMockRecorder) GetRetryMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetryMessage", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).GetRetryMessage), ctx, messageID)
}

// IncrementRateLimit mocks base method.
func (m *MockSMSRepositoryInterface) IncrementRateLimit(ctx context.Context, phone string, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRateLimit", ctx, phone, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementRateLimit indicates an expected call of IncrementRateLimit.
func (mr *MockSMSRepositoryInterfaceMockRecorder) IncrementRateLimit(ctx, phone, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRateLimit", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).IncrementRateLimit), ctx, phone, ttl)
}

// IncrementRetryAttempt mocks base method.
func (m *MockSMSRepositoryInterface) IncrementRetryAttempt(ctx context.Context, messageID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetryAttempt", ctx, messageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementRetryAttempt indicates an expected call of IncrementRetryAttempt.
func (mr *MockSMSRepositoryInterfaceMockRecorder) IncrementRetryAttempt(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetryAttempt", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).IncrementRetryAttempt), ctx, messageID)
}

// StoreOTP mocks base method.
func (m *MockSMSRepositoryInterface) StoreOTP(ctx context.Context, phone, purpose, code string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreOTP", ctx, phone, purpose, code, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreOTP indicates an expected call of StoreOTP.
func (mr *MockSMSRepositoryInterfaceMockRecorder) StoreOTP(ctx, phone, purpose, code, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreOTP", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).StoreOTP), ctx, phone, purpose, code, ttl)
}

// StoreRetryMessage mocks base method.
func (m *MockSMSRepositoryInterface) StoreRetryMessage(ctx context.Context, messageID, phone, message string, attempts int, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRetryMessage", ctx, messageID, phone, message, attempts, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRetryMessage indicates an expected call of StoreRetryMessage.
func (mr *MockSMSRepositoryInterfaceMockRecorder) StoreRetryMessage(ctx, messageID, phone, message, attempts, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRetryMessage", reflect.TypeOf((*MockSMSRepositoryInterface)(nil).StoreRetryMessage), ctx, messageID, phone, message, attempts, ttl)
}
