// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/pricing-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

type MockPricingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPricingServiceInterfaceMockRecorder
}
type MockPricingServiceInterfaceMockRecorder struct{ mock *MockPricingServiceInterface }

func NewMockPricingServiceInterface(ctrl *gomock.Controller) *MockPricingServiceInterface {
	m := &MockPricingServiceInterface{ctrl: ctrl}
	m.recorder = &MockPricingServiceInterfaceMockRecorder{m}
	return m
}
func (m *MockPricingServiceInterface) EXPECT() *MockPricingServiceInterfaceMockRecorder {
	return m.recorder
}

func (m *MockPricingServiceInterface) EstimateRideFare(ctx context.Context, req *service.RideEstimateRequest) (*service.RideFareEstimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateRideFare", ctx, req)
	ret0, _ := ret[0].(*service.RideFareEstimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingServiceInterfaceMockRecorder) EstimateRideFare(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateRideFare", reflect.TypeOf((*MockPricingServiceInterface)(nil).EstimateRideFare), ctx, req)
}

func (m *MockPricingServiceInterface) EstimateDeliveryFare(ctx context.Context, req *service.DeliveryEstimateRequest) (*service.DeliveryFareEstimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateDeliveryFare", ctx, req)
	ret0, _ := ret[0].(*service.DeliveryFareEstimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingServiceInterfaceMockRecorder) EstimateDeliveryFare(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateDeliveryFare", reflect.TypeOf((*MockPricingServiceInterface)(nil).EstimateDeliveryFare), ctx, req)
}

func (m *MockPricingServiceInterface) EstimateFoodFare(ctx context.Context, req *service.FoodEstimateRequest) (*service.FoodFareEstimate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFoodFare", ctx, req)
	ret0, _ := ret[0].(*service.FoodFareEstimate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingServiceInterfaceMockRecorder) EstimateFoodFare(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFoodFare", reflect.TypeOf((*MockPricingServiceInterface)(nil).EstimateFoodFare), ctx, req)
}

func (m *MockPricingServiceInterface) GetSurge(ctx context.Context, lat, lng float64, serviceType string) (*service.SurgeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSurge", ctx, lat, lng, serviceType)
	ret0, _ := ret[0].(*service.SurgeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingServiceInterfaceMockRecorder) GetSurge(ctx, lat, lng, serviceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurge", reflect.TypeOf((*MockPricingServiceInterface)(nil).GetSurge), ctx, lat, lng, serviceType)
}

func (m *MockPricingServiceInterface) CalculateFinalFare(ctx context.Context, req *service.FinalFareRequest) (*service.FinalFareResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFinalFare", ctx, req)
	ret0, _ := ret[0].(*service.FinalFareResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingServiceInterfaceMockRecorder) CalculateFinalFare(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFinalFare", reflect.TypeOf((*MockPricingServiceInterface)(nil).CalculateFinalFare), ctx, req)
}

func (m *MockPricingServiceInterface) GetFareRules(ctx context.Context, serviceType string, zoneID *string) (*service.FareRulesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareRules", ctx, serviceType, zoneID)
	ret0, _ := ret[0].(*service.FareRulesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockPricingServiceInterfaceMockRecorder) GetFareRules(ctx, serviceType, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareRules", reflect.TypeOf((*MockPricingServiceInterface)(nil).GetFareRules), ctx, serviceType, zoneID)
}
