// Code generated by MockGen. DO NOT EDIT.
// Source: ride_order_service.go
//
// Generated by: mockgen -source=ride_order_service.go -destination=../../mocks/mock_ride_order_service.go -package=mocks

package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/ride-order-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockRideOrderServiceInterface is a mock of RideOrderServiceInterface interface.
type MockRideOrderServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRideOrderServiceInterfaceMockRecorder
}

// MockRideOrderServiceInterfaceMockRecorder is the mock recorder for MockRideOrderServiceInterface.
type MockRideOrderServiceInterfaceMockRecorder struct {
	mock *MockRideOrderServiceInterface
}

// NewMockRideOrderServiceInterface creates a new mock instance.
func NewMockRideOrderServiceInterface(ctrl *gomock.Controller) *MockRideOrderServiceInterface {
	mock := &MockRideOrderServiceInterface{ctrl: ctrl}
	mock.recorder = &MockRideOrderServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRideOrderServiceInterface) EXPECT() *MockRideOrderServiceInterfaceMockRecorder {
	return m.recorder
}

// EstimateFare mocks base method.
func (m *MockRideOrderServiceInterface) EstimateFare(ctx context.Context, req *service.FareEstimateRequest) (*service.FareEstimateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFare", ctx, req)
	ret0, _ := ret[0].(*service.FareEstimateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateFare indicates an expected call of EstimateFare.
func (mr *MockRideOrderServiceInterfaceMockRecorder) EstimateFare(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFare", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).EstimateFare), ctx, req)
}

// CreateOrder mocks base method.
func (m *MockRideOrderServiceInterface) CreateOrder(ctx context.Context, userID string, req *service.CreateRideOrderRequest) (*service.RideOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, req)
	ret0, _ := ret[0].(*service.RideOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockRideOrderServiceInterfaceMockRecorder) CreateOrder(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).CreateOrder), ctx, userID, req)
}

// GetActiveOrder mocks base method.
func (m *MockRideOrderServiceInterface) GetActiveOrder(ctx context.Context, userID string) (*service.RideOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrder", ctx, userID)
	ret0, _ := ret[0].(*service.RideOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrder indicates an expected call of GetActiveOrder.
func (mr *MockRideOrderServiceInterfaceMockRecorder) GetActiveOrder(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrder", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).GetActiveOrder), ctx, userID)
}

// GetOrderHistory mocks base method.
func (m *MockRideOrderServiceInterface) GetOrderHistory(ctx context.Context, userID string, q service.HistoryQuery) (*service.RideOrderHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderHistory", ctx, userID, q)
	ret0, _ := ret[0].(*service.RideOrderHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderHistory indicates an expected call of GetOrderHistory.
func (mr *MockRideOrderServiceInterfaceMockRecorder) GetOrderHistory(ctx, userID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderHistory", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).GetOrderHistory), ctx, userID, q)
}

// GetOrder mocks base method.
func (m *MockRideOrderServiceInterface) GetOrder(ctx context.Context, userID, role, orderID string) (*service.RideOrderDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, userID, role, orderID)
	ret0, _ := ret[0].(*service.RideOrderDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockRideOrderServiceInterfaceMockRecorder) GetOrder(ctx, userID, role, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).GetOrder), ctx, userID, role, orderID)
}

// CancelOrder mocks base method.
func (m *MockRideOrderServiceInterface) CancelOrder(ctx context.Context, userID, orderID string, req *service.CancelOrderRequest) (*service.RideOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, userID, orderID, req)
	ret0, _ := ret[0].(*service.RideOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockRideOrderServiceInterfaceMockRecorder) CancelOrder(ctx, userID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).CancelOrder), ctx, userID, orderID, req)
}

// SubmitRating mocks base method.
func (m *MockRideOrderServiceInterface) SubmitRating(ctx context.Context, userID, orderID string, req *service.SubmitRatingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRating", ctx, userID, orderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitRating indicates an expected call of SubmitRating.
func (mr *MockRideOrderServiceInterfaceMockRecorder) SubmitRating(ctx, userID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRating", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).SubmitRating), ctx, userID, orderID, req)
}

// GetFareBreakdown mocks base method.
func (m *MockRideOrderServiceInterface) GetFareBreakdown(ctx context.Context, userID, orderID string) (*service.FareBreakdownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareBreakdown", ctx, userID, orderID)
	ret0, _ := ret[0].(*service.FareBreakdownResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFareBreakdown indicates an expected call of GetFareBreakdown.
func (mr *MockRideOrderServiceInterfaceMockRecorder) GetFareBreakdown(ctx, userID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareBreakdown", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).GetFareBreakdown), ctx, userID, orderID)
}

// DriverAcceptOrder mocks base method.
func (m *MockRideOrderServiceInterface) DriverAcceptOrder(ctx context.Context, driverID, orderID string) (*service.DriverAcceptResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverAcceptOrder", ctx, driverID, orderID)
	ret0, _ := ret[0].(*service.DriverAcceptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DriverAcceptOrder indicates an expected call of DriverAcceptOrder.
func (mr *MockRideOrderServiceInterfaceMockRecorder) DriverAcceptOrder(ctx, driverID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverAcceptOrder", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).DriverAcceptOrder), ctx, driverID, orderID)
}

// DriverRejectOrder mocks base method.
func (m *MockRideOrderServiceInterface) DriverRejectOrder(ctx context.Context, driverID, orderID string, req *service.DriverRejectRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverRejectOrder", ctx, driverID, orderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DriverRejectOrder indicates an expected call of DriverRejectOrder.
func (mr *MockRideOrderServiceInterfaceMockRecorder) DriverRejectOrder(ctx, driverID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverRejectOrder", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).DriverRejectOrder), ctx, driverID, orderID, req)
}

// DriverUpdateOrderStatus mocks base method.
func (m *MockRideOrderServiceInterface) DriverUpdateOrderStatus(ctx context.Context, driverID, orderID string, req *service.DriverUpdateStatusRequest) (*service.RideOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverUpdateOrderStatus", ctx, driverID, orderID, req)
	ret0, _ := ret[0].(*service.RideOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DriverUpdateOrderStatus indicates an expected call of DriverUpdateOrderStatus.
func (mr *MockRideOrderServiceInterfaceMockRecorder) DriverUpdateOrderStatus(ctx, driverID, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverUpdateOrderStatus", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).DriverUpdateOrderStatus), ctx, driverID, orderID, req)
}

// InternalCreateOrder mocks base method.
func (m *MockRideOrderServiceInterface) InternalCreateOrder(ctx context.Context, req *service.InternalCreateOrderRequest) (*service.RideOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalCreateOrder", ctx, req)
	ret0, _ := ret[0].(*service.RideOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalCreateOrder indicates an expected call of InternalCreateOrder.
func (mr *MockRideOrderServiceInterfaceMockRecorder) InternalCreateOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalCreateOrder", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).InternalCreateOrder), ctx, req)
}

// InternalGetOrder mocks base method.
func (m *MockRideOrderServiceInterface) InternalGetOrder(ctx context.Context, orderID string) (*service.RideOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetOrder", ctx, orderID)
	ret0, _ := ret[0].(*service.RideOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalGetOrder indicates an expected call of InternalGetOrder.
func (mr *MockRideOrderServiceInterfaceMockRecorder) InternalGetOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetOrder", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).InternalGetOrder), ctx, orderID)
}

// InternalUpdateStatus mocks base method.
func (m *MockRideOrderServiceInterface) InternalUpdateStatus(ctx context.Context, orderID string, req *service.InternalUpdateStatusRequest) (*service.RideOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalUpdateStatus", ctx, orderID, req)
	ret0, _ := ret[0].(*service.RideOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalUpdateStatus indicates an expected call of InternalUpdateStatus.
func (mr *MockRideOrderServiceInterfaceMockRecorder) InternalUpdateStatus(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalUpdateStatus", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).InternalUpdateStatus), ctx, orderID, req)
}

// InternalAssignDriver mocks base method.
func (m *MockRideOrderServiceInterface) InternalAssignDriver(ctx context.Context, orderID string, req *service.InternalAssignDriverRequest) (*service.InternalAssignDriverResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalAssignDriver", ctx, orderID, req)
	ret0, _ := ret[0].(*service.InternalAssignDriverResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalAssignDriver indicates an expected call of InternalAssignDriver.
func (mr *MockRideOrderServiceInterfaceMockRecorder) InternalAssignDriver(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalAssignDriver", reflect.TypeOf((*MockRideOrderServiceInterface)(nil).InternalAssignDriver), ctx, orderID, req)
}
