// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Github\clay\clay-search-service\internal\repository\search_repository.go
//
// Generated by this command:
//
//	mockgen -source=D:\Github\clay\clay-search-service\internal\repository\search_repository.go -destination=D:\Github\clay\clay-search-service\mocks\repomock\mock_search_repository.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	model "github.com/zicofarry/clay-app/backend/services/search-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchRepositoryInterface is a mock of SearchRepositoryInterface interface.
type MockSearchRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSearchRepositoryInterfaceMockRecorder is the mock recorder for MockSearchRepositoryInterface.
type MockSearchRepositoryInterfaceMockRecorder struct {
	mock *MockSearchRepositoryInterface
}

// NewMockSearchRepositoryInterface creates a new mock instance.
func NewMockSearchRepositoryInterface(ctrl *gomock.Controller) *MockSearchRepositoryInterface {
	mock := &MockSearchRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSearchRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRepositoryInterface) EXPECT() *MockSearchRepositoryInterfaceMockRecorder {
	return m.recorder
}

// IndexMenuItem mocks base method.
func (m *MockSearchRepositoryInterface) IndexMenuItem(ctx context.Context, doc model.MenuItemDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMenuItem", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMenuItem indicates an expected call of IndexMenuItem.
func (mr *MockSearchRepositoryInterfaceMockRecorder) IndexMenuItem(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMenuItem", reflect.TypeOf((*MockSearchRepositoryInterface)(nil).IndexMenuItem), ctx, doc)
}

// IndexMerchant mocks base method.
func (m *MockSearchRepositoryInterface) IndexMerchant(ctx context.Context, doc model.MerchantDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMerchant", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMerchant indicates an expected call of IndexMerchant.
func (mr *MockSearchRepositoryInterfaceMockRecorder) IndexMerchant(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMerchant", reflect.TypeOf((*MockSearchRepositoryInterface)(nil).IndexMerchant), ctx, doc)
}

// InitIndices mocks base method.
func (m *MockSearchRepositoryInterface) InitIndices(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitIndices", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitIndices indicates an expected call of InitIndices.
func (mr *MockSearchRepositoryInterfaceMockRecorder) InitIndices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitIndices", reflect.TypeOf((*MockSearchRepositoryInterface)(nil).InitIndices), ctx)
}

// Ping mocks base method.
func (m *MockSearchRepositoryInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSearchRepositoryInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSearchRepositoryInterface)(nil).Ping), ctx)
}
