// Code generated by MockGen. DO NOT EDIT.
// Source: promotion_service.go
//
// Generated by this command:
//
//	mockgen -source=promotion_service.go -destination=../../mocks/promotion_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	service "github.com/zicofarry/clay-app/backend/services/promotion-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockPromotionServiceInterface is a mock of PromotionServiceInterface interface.
type MockPromotionServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPromotionServiceInterfaceMockRecorder is the mock recorder for MockPromotionServiceInterface.
type MockPromotionServiceInterfaceMockRecorder struct {
	mock *MockPromotionServiceInterface
}

// NewMockPromotionServiceInterface creates a new mock instance.
func NewMockPromotionServiceInterface(ctrl *gomock.Controller) *MockPromotionServiceInterface {
	mock := &MockPromotionServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPromotionServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionServiceInterface) EXPECT() *MockPromotionServiceInterfaceMockRecorder {
	return m.recorder
}

// ApplyPromo mocks base method.
func (m *MockPromotionServiceInterface) ApplyPromo(ctx context.Context, req service.ApplyPromoRequest) (*service.ApplyPromoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPromo", ctx, req)
	ret0, _ := ret[0].(*service.ApplyPromoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyPromo indicates an expected call of ApplyPromo.
func (mr *MockPromotionServiceInterfaceMockRecorder) ApplyPromo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPromo", reflect.TypeOf((*MockPromotionServiceInterface)(nil).ApplyPromo), ctx, req)
}

// ClaimVoucher mocks base method.
func (m *MockPromotionServiceInterface) ClaimVoucher(ctx context.Context, userID, code string) (*service.VoucherDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimVoucher", ctx, userID, code)
	ret0, _ := ret[0].(*service.VoucherDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimVoucher indicates an expected call of ClaimVoucher.
func (mr *MockPromotionServiceInterfaceMockRecorder) ClaimVoucher(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimVoucher", reflect.TypeOf((*MockPromotionServiceInterface)(nil).ClaimVoucher), ctx, userID, code)
}

// CreatePromo mocks base method.
func (m *MockPromotionServiceInterface) CreatePromo(ctx context.Context, promo service.PromoDTO) (*service.PromoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePromo", ctx, promo)
	ret0, _ := ret[0].(*service.PromoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePromo indicates an expected call of CreatePromo.
func (mr *MockPromotionServiceInterfaceMockRecorder) CreatePromo(ctx, promo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePromo", reflect.TypeOf((*MockPromotionServiceInterface)(nil).CreatePromo), ctx, promo)
}

// DeactivatePromo mocks base method.
func (m *MockPromotionServiceInterface) DeactivatePromo(ctx context.Context, promoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivatePromo", ctx, promoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivatePromo indicates an expected call of DeactivatePromo.
func (mr *MockPromotionServiceInterfaceMockRecorder) DeactivatePromo(ctx, promoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivatePromo", reflect.TypeOf((*MockPromotionServiceInterface)(nil).DeactivatePromo), ctx, promoID)
}

// ListMyVouchers mocks base method.
func (m *MockPromotionServiceInterface) ListMyVouchers(ctx context.Context, userID, serviceType, status string) ([]service.VoucherDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyVouchers", ctx, userID, serviceType, status)
	ret0, _ := ret[0].([]service.VoucherDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyVouchers indicates an expected call of ListMyVouchers.
func (mr *MockPromotionServiceInterfaceMockRecorder) ListMyVouchers(ctx, userID, serviceType, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyVouchers", reflect.TypeOf((*MockPromotionServiceInterface)(nil).ListMyVouchers), ctx, userID, serviceType, status)
}

// ListPromos mocks base method.
func (m *MockPromotionServiceInterface) ListPromos(ctx context.Context, status string, page, limit int) ([]service.PromoDTO, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPromos", ctx, status, page, limit)
	ret0, _ := ret[0].([]service.PromoDTO)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPromos indicates an expected call of ListPromos.
func (mr *MockPromotionServiceInterfaceMockRecorder) ListPromos(ctx, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPromos", reflect.TypeOf((*MockPromotionServiceInterface)(nil).ListPromos), ctx, status, page, limit)
}

// ReleasePromo mocks base method.
func (m *MockPromotionServiceInterface) ReleasePromo(ctx context.Context, promoCode, orderID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleasePromo", ctx, promoCode, orderID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleasePromo indicates an expected call of ReleasePromo.
func (mr *MockPromotionServiceInterfaceMockRecorder) ReleasePromo(ctx, promoCode, orderID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleasePromo", reflect.TypeOf((*MockPromotionServiceInterface)(nil).ReleasePromo), ctx, promoCode, orderID, userID)
}

// UpdatePromo mocks base method.
func (m *MockPromotionServiceInterface) UpdatePromo(ctx context.Context, promoID string, isActive *bool, validUntil *time.Time, usageLimit, perUserLimit *int) (*service.PromoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePromo", ctx, promoID, isActive, validUntil, usageLimit, perUserLimit)
	ret0, _ := ret[0].(*service.PromoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePromo indicates an expected call of UpdatePromo.
func (mr *MockPromotionServiceInterfaceMockRecorder) UpdatePromo(ctx, promoID, isActive, validUntil, usageLimit, perUserLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePromo", reflect.TypeOf((*MockPromotionServiceInterface)(nil).UpdatePromo), ctx, promoID, isActive, validUntil, usageLimit, perUserLimit)
}

// ValidatePromo mocks base method.
func (m *MockPromotionServiceInterface) ValidatePromo(ctx context.Context, req service.ValidatePromoRequest) (*service.PromoValidationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePromo", ctx, req)
	ret0, _ := ret[0].(*service.PromoValidationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatePromo indicates an expected call of ValidatePromo.
func (mr *MockPromotionServiceInterfaceMockRecorder) ValidatePromo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePromo", reflect.TypeOf((*MockPromotionServiceInterface)(nil).ValidatePromo), ctx, req)
}
