// Code generated by MockGen. DO NOT EDIT.
// Source: history_service.go
//
// Generated by this command:
//
//	mockgen -source=history_service.go -destination=../../mocks/history_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/history-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoryServiceInterface is a mock of HistoryServiceInterface interface.
type MockHistoryServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockHistoryServiceInterfaceMockRecorder is the mock recorder for MockHistoryServiceInterface.
type MockHistoryServiceInterfaceMockRecorder struct {
	mock *MockHistoryServiceInterface
}

// NewMockHistoryServiceInterface creates a new mock instance.
func NewMockHistoryServiceInterface(ctrl *gomock.Controller) *MockHistoryServiceInterface {
	mock := &MockHistoryServiceInterface{ctrl: ctrl}
	mock.recorder = &MockHistoryServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryServiceInterface) EXPECT() *MockHistoryServiceInterfaceMockRecorder {
	return m.recorder
}

// GetActivityFeedEntry mocks base method.
func (m *MockHistoryServiceInterface) GetActivityFeedEntry(ctx context.Context, feedID, userID string) (*service.ActivityFeedDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityFeedEntry", ctx, feedID, userID)
	ret0, _ := ret[0].(*service.ActivityFeedDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityFeedEntry indicates an expected call of GetActivityFeedEntry.
func (mr *MockHistoryServiceInterfaceMockRecorder) GetActivityFeedEntry(ctx, feedID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityFeedEntry", reflect.TypeOf((*MockHistoryServiceInterface)(nil).GetActivityFeedEntry), ctx, feedID, userID)
}

// GetMyActivityFeed mocks base method.
func (m *MockHistoryServiceInterface) GetMyActivityFeed(ctx context.Context, userID, eventType, beforeID string, limit int) ([]service.ActivityFeedDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyActivityFeed", ctx, userID, eventType, beforeID, limit)
	ret0, _ := ret[0].([]service.ActivityFeedDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyActivityFeed indicates an expected call of GetMyActivityFeed.
func (mr *MockHistoryServiceInterfaceMockRecorder) GetMyActivityFeed(ctx, userID, eventType, beforeID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyActivityFeed", reflect.TypeOf((*MockHistoryServiceInterface)(nil).GetMyActivityFeed), ctx, userID, eventType, beforeID, limit)
}

// GetOrderHistoryDetail mocks base method.
func (m *MockHistoryServiceInterface) GetOrderHistoryDetail(ctx context.Context, orderID, participantID string) (*service.OrderHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderHistoryDetail", ctx, orderID, participantID)
	ret0, _ := ret[0].(*service.OrderHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderHistoryDetail indicates an expected call of GetOrderHistoryDetail.
func (mr *MockHistoryServiceInterfaceMockRecorder) GetOrderHistoryDetail(ctx, orderID, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderHistoryDetail", reflect.TypeOf((*MockHistoryServiceInterface)(nil).GetOrderHistoryDetail), ctx, orderID, participantID)
}

// InternalCreateFeedEntry mocks base method.
func (m *MockHistoryServiceInterface) InternalCreateFeedEntry(ctx context.Context, req service.InternalCreateFeedEntryRequest) (*service.ActivityFeedDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalCreateFeedEntry", ctx, req)
	ret0, _ := ret[0].(*service.ActivityFeedDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalCreateFeedEntry indicates an expected call of InternalCreateFeedEntry.
func (mr *MockHistoryServiceInterfaceMockRecorder) InternalCreateFeedEntry(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalCreateFeedEntry", reflect.TypeOf((*MockHistoryServiceInterface)(nil).InternalCreateFeedEntry), ctx, req)
}

// InternalSyncOrderHistory mocks base method.
func (m *MockHistoryServiceInterface) InternalSyncOrderHistory(ctx context.Context, req service.InternalCreateOrderHistoryRequest) (*service.OrderHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalSyncOrderHistory", ctx, req)
	ret0, _ := ret[0].(*service.OrderHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalSyncOrderHistory indicates an expected call of InternalSyncOrderHistory.
func (mr *MockHistoryServiceInterfaceMockRecorder) InternalSyncOrderHistory(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalSyncOrderHistory", reflect.TypeOf((*MockHistoryServiceInterface)(nil).InternalSyncOrderHistory), ctx, req)
}

// ListDriverTripHistory mocks base method.
func (m *MockHistoryServiceInterface) ListDriverTripHistory(ctx context.Context, driverID, orderType, status string, page, limit int) ([]service.OrderHistoryDTO, *service.PaginationMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDriverTripHistory", ctx, driverID, orderType, status, page, limit)
	ret0, _ := ret[0].([]service.OrderHistoryDTO)
	ret1, _ := ret[1].(*service.PaginationMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDriverTripHistory indicates an expected call of ListDriverTripHistory.
func (mr *MockHistoryServiceInterfaceMockRecorder) ListDriverTripHistory(ctx, driverID, orderType, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDriverTripHistory", reflect.TypeOf((*MockHistoryServiceInterface)(nil).ListDriverTripHistory), ctx, driverID, orderType, status, page, limit)
}

// ListMyOrderHistory mocks base method.
func (m *MockHistoryServiceInterface) ListMyOrderHistory(ctx context.Context, userID, orderType, status string, page, limit int) ([]service.OrderHistoryDTO, *service.PaginationMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyOrderHistory", ctx, userID, orderType, status, page, limit)
	ret0, _ := ret[0].([]service.OrderHistoryDTO)
	ret1, _ := ret[1].(*service.PaginationMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMyOrderHistory indicates an expected call of ListMyOrderHistory.
func (mr *MockHistoryServiceInterfaceMockRecorder) ListMyOrderHistory(ctx, userID, orderType, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyOrderHistory", reflect.TypeOf((*MockHistoryServiceInterface)(nil).ListMyOrderHistory), ctx, userID, orderType, status, page, limit)
}
