// Code generated by MockGen. DO NOT EDIT.
// Source: rating_repository.go
//
// Generated by this command:
//
//	mockgen -source=rating_repository.go -destination=../../mocks/repomock/rating_repository_mock.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	repository "github.com/zicofarry/clay-app/backend/services/rating-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRatingRepositoryInterface is a mock of RatingRepositoryInterface interface.
type MockRatingRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRatingRepositoryInterfaceMockRecorder is the mock recorder for MockRatingRepositoryInterface.
type MockRatingRepositoryInterfaceMockRecorder struct {
	mock *MockRatingRepositoryInterface
}

// NewMockRatingRepositoryInterface creates a new mock instance.
func NewMockRatingRepositoryInterface(ctrl *gomock.Controller) *MockRatingRepositoryInterface {
	mock := &MockRatingRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRatingRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepositoryInterface) EXPECT() *MockRatingRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateRating mocks base method.
func (m *MockRatingRepositoryInterface) CreateRating(ctx context.Context, rating *repository.Rating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRating", ctx, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRating indicates an expected call of CreateRating.
func (mr *MockRatingRepositoryInterfaceMockRecorder) CreateRating(ctx, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRating", reflect.TypeOf((*MockRatingRepositoryInterface)(nil).CreateRating), ctx, rating)
}

// GetDriverAggregate mocks base method.
func (m *MockRatingRepositoryInterface) GetDriverAggregate(ctx context.Context, driverID uuid.UUID) (*repository.DriverScoreAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverAggregate", ctx, driverID)
	ret0, _ := ret[0].(*repository.DriverScoreAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverAggregate indicates an expected call of GetDriverAggregate.
func (mr *MockRatingRepositoryInterfaceMockRecorder) GetDriverAggregate(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverAggregate", reflect.TypeOf((*MockRatingRepositoryInterface)(nil).GetDriverAggregate), ctx, driverID)
}

// GetMerchantAggregate mocks base method.
func (m *MockRatingRepositoryInterface) GetMerchantAggregate(ctx context.Context, merchantID uuid.UUID) (*repository.MerchantScoreAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantAggregate", ctx, merchantID)
	ret0, _ := ret[0].(*repository.MerchantScoreAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantAggregate indicates an expected call of GetMerchantAggregate.
func (mr *MockRatingRepositoryInterfaceMockRecorder) GetMerchantAggregate(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantAggregate", reflect.TypeOf((*MockRatingRepositoryInterface)(nil).GetMerchantAggregate), ctx, merchantID)
}

// GetRatingsByOrder mocks base method.
func (m *MockRatingRepositoryInterface) GetRatingsByOrder(ctx context.Context, orderID uuid.UUID) ([]repository.Rating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatingsByOrder", ctx, orderID)
	ret0, _ := ret[0].([]repository.Rating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatingsByOrder indicates an expected call of GetRatingsByOrder.
func (mr *MockRatingRepositoryInterfaceMockRecorder) GetRatingsByOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatingsByOrder", reflect.TypeOf((*MockRatingRepositoryInterface)(nil).GetRatingsByOrder), ctx, orderID)
}

// GetRatingsByRater mocks base method.
func (m *MockRatingRepositoryInterface) GetRatingsByRater(ctx context.Context, raterID uuid.UUID, limit, offset int) ([]repository.Rating, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatingsByRater", ctx, raterID, limit, offset)
	ret0, _ := ret[0].([]repository.Rating)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRatingsByRater indicates an expected call of GetRatingsByRater.
func (mr *MockRatingRepositoryInterfaceMockRecorder) GetRatingsByRater(ctx, raterID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatingsByRater", reflect.TypeOf((*MockRatingRepositoryInterface)(nil).GetRatingsByRater), ctx, raterID, limit, offset)
}

// GetRatingsBySubject mocks base method.
func (m *MockRatingRepositoryInterface) GetRatingsBySubject(ctx context.Context, subjectType string, subjectID uuid.UUID, limit, offset int) ([]repository.Rating, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatingsBySubject", ctx, subjectType, subjectID, limit, offset)
	ret0, _ := ret[0].([]repository.Rating)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRatingsBySubject indicates an expected call of GetRatingsBySubject.
func (mr *MockRatingRepositoryInterfaceMockRecorder) GetRatingsBySubject(ctx, subjectType, subjectID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatingsBySubject", reflect.TypeOf((*MockRatingRepositoryInterface)(nil).GetRatingsBySubject), ctx, subjectType, subjectID, limit, offset)
}

// RunInTx mocks base method.
func (m *MockRatingRepositoryInterface) RunInTx(ctx context.Context, fn func(repository.RatingRepositoryInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockRatingRepositoryInterfaceMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockRatingRepositoryInterface)(nil).RunInTx), ctx, fn)
}
