// Code generated by MockGen. DO NOT EDIT.
// Source: notification_repository.go
//
// Generated by this command:
//
//	mockgen -source=notification_repository.go -destination=../../mocks/repomock/mock_notification_repository.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/notification-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepositoryInterface is a mock of NotificationRepositoryInterface interface.
type MockNotificationRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryInterfaceMockRecorder is the mock recorder for MockNotificationRepositoryInterface.
type MockNotificationRepositoryInterfaceMockRecorder struct {
	mock *MockNotificationRepositoryInterface
}

// NewMockNotificationRepositoryInterface creates a new mock instance.
func NewMockNotificationRepositoryInterface(ctrl *gomock.Controller) *MockNotificationRepositoryInterface {
	mock := &MockNotificationRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepositoryInterface) EXPECT() *MockNotificationRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateDeviceToken mocks base method.
func (m *MockNotificationRepositoryInterface) CreateDeviceToken(ctx context.Context, token *repository.DeviceToken) (*repository.DeviceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeviceToken", ctx, token)
	ret0, _ := ret[0].(*repository.DeviceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeviceToken indicates an expected call of CreateDeviceToken.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) CreateDeviceToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeviceToken", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).CreateDeviceToken), ctx, token)
}

// CreateNotificationLog mocks base method.
func (m *MockNotificationRepositoryInterface) CreateNotificationLog(ctx context.Context, log *repository.NotificationLog) (*repository.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotificationLog", ctx, log)
	ret0, _ := ret[0].(*repository.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotificationLog indicates an expected call of CreateNotificationLog.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) CreateNotificationLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotificationLog", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).CreateNotificationLog), ctx, log)
}

// CreateTemplate mocks base method.
func (m *MockNotificationRepositoryInterface) CreateTemplate(ctx context.Context, tmpl *repository.NotificationTemplate) (*repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, tmpl)
	ret0, _ := ret[0].(*repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) CreateTemplate(ctx, tmpl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).CreateTemplate), ctx, tmpl)
}

// DeactivateDeviceToken mocks base method.
func (m *MockNotificationRepositoryInterface) DeactivateDeviceToken(ctx context.Context, tokenID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateDeviceToken", ctx, tokenID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateDeviceToken indicates an expected call of DeactivateDeviceToken.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) DeactivateDeviceToken(ctx, tokenID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateDeviceToken", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).DeactivateDeviceToken), ctx, tokenID, userID)
}

// DeactivateTemplate mocks base method.
func (m *MockNotificationRepositoryInterface) DeactivateTemplate(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTemplate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateTemplate indicates an expected call of DeactivateTemplate.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) DeactivateTemplate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTemplate", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).DeactivateTemplate), ctx, id)
}

// FindDeviceTokensByUserID mocks base method.
func (m *MockNotificationRepositoryInterface) FindDeviceTokensByUserID(ctx context.Context, userID string, activeOnly bool) ([]repository.DeviceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeviceTokensByUserID", ctx, userID, activeOnly)
	ret0, _ := ret[0].([]repository.DeviceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeviceTokensByUserID indicates an expected call of FindDeviceTokensByUserID.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) FindDeviceTokensByUserID(ctx, userID, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeviceTokensByUserID", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).FindDeviceTokensByUserID), ctx, userID, activeOnly)
}

// FindNotificationByID mocks base method.
func (m *MockNotificationRepositoryInterface) FindNotificationByID(ctx context.Context, id, userID string) (*repository.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNotificationByID", ctx, id, userID)
	ret0, _ := ret[0].(*repository.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNotificationByID indicates an expected call of FindNotificationByID.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) FindNotificationByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNotificationByID", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).FindNotificationByID), ctx, id, userID)
}

// FindNotificationsByUserID mocks base method.
func (m *MockNotificationRepositoryInterface) FindNotificationsByUserID(ctx context.Context, userID string, page, limit int) ([]repository.NotificationLog, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNotificationsByUserID", ctx, userID, page, limit)
	ret0, _ := ret[0].([]repository.NotificationLog)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindNotificationsByUserID indicates an expected call of FindNotificationsByUserID.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) FindNotificationsByUserID(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNotificationsByUserID", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).FindNotificationsByUserID), ctx, userID, page, limit)
}

// FindTemplateByEventAndChannel mocks base method.
func (m *MockNotificationRepositoryInterface) FindTemplateByEventAndChannel(ctx context.Context, eventType, channel string) (*repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTemplateByEventAndChannel", ctx, eventType, channel)
	ret0, _ := ret[0].(*repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTemplateByEventAndChannel indicates an expected call of FindTemplateByEventAndChannel.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) FindTemplateByEventAndChannel(ctx, eventType, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTemplateByEventAndChannel", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).FindTemplateByEventAndChannel), ctx, eventType, channel)
}

// FindTemplateByID mocks base method.
func (m *MockNotificationRepositoryInterface) FindTemplateByID(ctx context.Context, id string) (*repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTemplateByID", ctx, id)
	ret0, _ := ret[0].(*repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTemplateByID indicates an expected call of FindTemplateByID.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) FindTemplateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTemplateByID", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).FindTemplateByID), ctx, id)
}

// GetPreferences mocks base method.
func (m *MockNotificationRepositoryInterface) GetPreferences(ctx context.Context, userID string) (*repository.NotificationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreferences", ctx, userID)
	ret0, _ := ret[0].(*repository.NotificationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreferences indicates an expected call of GetPreferences.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) GetPreferences(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreferences", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).GetPreferences), ctx, userID)
}

// ListTemplates mocks base method.
func (m *MockNotificationRepositoryInterface) ListTemplates(ctx context.Context) ([]repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", ctx)
	ret0, _ := ret[0].([]repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) ListTemplates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).ListTemplates), ctx)
}

// UpdateTemplate mocks base method.
func (m *MockNotificationRepositoryInterface) UpdateTemplate(ctx context.Context, tmpl *repository.NotificationTemplate) (*repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, tmpl)
	ret0, _ := ret[0].(*repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) UpdateTemplate(ctx, tmpl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).UpdateTemplate), ctx, tmpl)
}

// UpsertPreferences mocks base method.
func (m *MockNotificationRepositoryInterface) UpsertPreferences(ctx context.Context, pref *repository.NotificationPreference) (*repository.NotificationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPreferences", ctx, pref)
	ret0, _ := ret[0].(*repository.NotificationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPreferences indicates an expected call of UpsertPreferences.
func (mr *MockNotificationRepositoryInterfaceMockRecorder) UpsertPreferences(ctx, pref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPreferences", reflect.TypeOf((*MockNotificationRepositoryInterface)(nil).UpsertPreferences), ctx, pref)
}
