// Code generated by MockGen. DO NOT EDIT.
package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/geo-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

type MockGeoRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGeoRepositoryInterfaceMockRecorder
}
type MockGeoRepositoryInterfaceMockRecorder struct{ mock *MockGeoRepositoryInterface }

func NewMockGeoRepositoryInterface(ctrl *gomock.Controller) *MockGeoRepositoryInterface {
	m := &MockGeoRepositoryInterface{ctrl: ctrl}
	m.recorder = &MockGeoRepositoryInterfaceMockRecorder{m}
	return m
}
func (m *MockGeoRepositoryInterface) EXPECT() *MockGeoRepositoryInterfaceMockRecorder { return m.recorder }

func (m *MockGeoRepositoryInterface) CreateZone(ctx context.Context, zone *repository.GeofenceZone) (*repository.GeofenceZone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZone", ctx, zone)
	ret0, _ := ret[0].(*repository.GeofenceZone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoRepositoryInterfaceMockRecorder) CreateZone(ctx, zone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZone", reflect.TypeOf((*MockGeoRepositoryInterface)(nil).CreateZone), ctx, zone)
}

func (m *MockGeoRepositoryInterface) ListZones(ctx context.Context) ([]repository.GeofenceZone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZones", ctx)
	ret0, _ := ret[0].([]repository.GeofenceZone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoRepositoryInterfaceMockRecorder) ListZones(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZones", reflect.TypeOf((*MockGeoRepositoryInterface)(nil).ListZones), ctx)
}

func (m *MockGeoRepositoryInterface) FindZonesByPoint(ctx context.Context, lat, lng float64) ([]repository.GeofenceZone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindZonesByPoint", ctx, lat, lng)
	ret0, _ := ret[0].([]repository.GeofenceZone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockGeoRepositoryInterfaceMockRecorder) FindZonesByPoint(ctx, lat, lng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindZonesByPoint", reflect.TypeOf((*MockGeoRepositoryInterface)(nil).FindZonesByPoint), ctx, lat, lng)
}
