// Code generated by MockGen. DO NOT EDIT.
// Source: menu_repository.go
//
// Generated by: mockgen -source=menu_repository.go -destination=../../mocks/repomock/mock_menu_repository.go -package=repomock

package repomock

import (
	context "context"
	reflect "reflect"

	model "github.com/zicofarry/clay-app/backend/services/merchant-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMenuRepositoryInterface is a mock of MenuRepositoryInterface interface.
type MockMenuRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMenuRepositoryInterfaceMockRecorder
}

// MockMenuRepositoryInterfaceMockRecorder is the mock recorder for MockMenuRepositoryInterface.
type MockMenuRepositoryInterfaceMockRecorder struct {
	mock *MockMenuRepositoryInterface
}

// NewMockMenuRepositoryInterface creates a new mock instance.
func NewMockMenuRepositoryInterface(ctrl *gomock.Controller) *MockMenuRepositoryInterface {
	mock := &MockMenuRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockMenuRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuRepositoryInterface) EXPECT() *MockMenuRepositoryInterfaceMockRecorder {
	return m.recorder
}

// ListCategories mocks base method.
func (m *MockMenuRepositoryInterface) ListCategories(ctx context.Context, merchantID string) ([]model.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, merchantID)
	ret0, _ := ret[0].([]model.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) ListCategories(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).ListCategories), ctx, merchantID)
}

// CreateCategory mocks base method.
func (m *MockMenuRepositoryInterface) CreateCategory(ctx context.Context, merchantID string, req model.CreateMenuCategoryRequest) (*model.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, merchantID, req)
	ret0, _ := ret[0].(*model.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) CreateCategory(ctx, merchantID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).CreateCategory), ctx, merchantID, req)
}

// UpdateCategory mocks base method.
func (m *MockMenuRepositoryInterface) UpdateCategory(ctx context.Context, categoryID, merchantID string, req model.UpdateMenuCategoryRequest) (*model.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, categoryID, merchantID, req)
	ret0, _ := ret[0].(*model.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) UpdateCategory(ctx, categoryID, merchantID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).UpdateCategory), ctx, categoryID, merchantID, req)
}

// DeleteCategory mocks base method.
func (m *MockMenuRepositoryInterface) DeleteCategory(ctx context.Context, categoryID, merchantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, categoryID, merchantID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) DeleteCategory(ctx, categoryID, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).DeleteCategory), ctx, categoryID, merchantID)
}

// ReorderCategories mocks base method.
func (m *MockMenuRepositoryInterface) ReorderCategories(ctx context.Context, merchantID string, req model.ReorderCategoriesRequest) ([]model.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderCategories", ctx, merchantID, req)
	ret0, _ := ret[0].([]model.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) ReorderCategories(ctx, merchantID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderCategories", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).ReorderCategories), ctx, merchantID, req)
}

// ListItems mocks base method.
func (m *MockMenuRepositoryInterface) ListItems(ctx context.Context, merchantID string, categoryID string, isAvailable *bool) ([]model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, merchantID, categoryID, isAvailable)
	ret0, _ := ret[0].([]model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) ListItems(ctx, merchantID, categoryID, isAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).ListItems), ctx, merchantID, categoryID, isAvailable)
}

// CreateItem mocks base method.
func (m *MockMenuRepositoryInterface) CreateItem(ctx context.Context, merchantID string, req model.CreateMenuItemRequest) (*model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, merchantID, req)
	ret0, _ := ret[0].(*model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) CreateItem(ctx, merchantID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).CreateItem), ctx, merchantID, req)
}

// GetItemByID mocks base method.
func (m *MockMenuRepositoryInterface) GetItemByID(ctx context.Context, itemID, merchantID string) (*model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByID", ctx, itemID, merchantID)
	ret0, _ := ret[0].(*model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) GetItemByID(ctx, itemID, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByID", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).GetItemByID), ctx, itemID, merchantID)
}

// UpdateItem mocks base method.
func (m *MockMenuRepositoryInterface) UpdateItem(ctx context.Context, itemID, merchantID string, req model.UpdateMenuItemRequest) (*model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, itemID, merchantID, req)
	ret0, _ := ret[0].(*model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) UpdateItem(ctx, itemID, merchantID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).UpdateItem), ctx, itemID, merchantID, req)
}

// DeleteItem mocks base method.
func (m *MockMenuRepositoryInterface) DeleteItem(ctx context.Context, itemID, merchantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, itemID, merchantID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) DeleteItem(ctx, itemID, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).DeleteItem), ctx, itemID, merchantID)
}

// ToggleAvailability mocks base method.
func (m *MockMenuRepositoryInterface) ToggleAvailability(ctx context.Context, itemID, merchantID string, available bool) (*model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleAvailability", ctx, itemID, merchantID, available)
	ret0, _ := ret[0].(*model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) ToggleAvailability(ctx, itemID, merchantID, available any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAvailability", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).ToggleAvailability), ctx, itemID, merchantID, available)
}

// BatchGetItems mocks base method.
func (m *MockMenuRepositoryInterface) BatchGetItems(ctx context.Context, itemIDs []string) ([]model.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetItems", ctx, itemIDs)
	ret0, _ := ret[0].([]model.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMenuRepositoryInterfaceMockRecorder) BatchGetItems(ctx, itemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetItems", reflect.TypeOf((*MockMenuRepositoryInterface)(nil).BatchGetItems), ctx, itemIDs)
}
