// Code generated by MockGen. DO NOT EDIT.
// Source: merchant_repository.go
//
// Generated by: mockgen -source=merchant_repository.go -destination=../../mocks/repomock/mock_merchant_repository.go -package=repomock

package repomock

import (
	context "context"
	reflect "reflect"

	model "github.com/zicofarry/clay-app/backend/services/merchant-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMerchantRepositoryInterface is a mock of MerchantRepositoryInterface interface.
type MockMerchantRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantRepositoryInterfaceMockRecorder
}

// MockMerchantRepositoryInterfaceMockRecorder is the mock recorder for MockMerchantRepositoryInterface.
type MockMerchantRepositoryInterfaceMockRecorder struct {
	mock *MockMerchantRepositoryInterface
}

// NewMockMerchantRepositoryInterface creates a new mock instance.
func NewMockMerchantRepositoryInterface(ctrl *gomock.Controller) *MockMerchantRepositoryInterface {
	mock := &MockMerchantRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockMerchantRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantRepositoryInterface) EXPECT() *MockMerchantRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMerchantRepositoryInterface) Create(ctx context.Context, merchant *model.Merchant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, merchant)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) Create(ctx, merchant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).Create), ctx, merchant)
}

// GetByID mocks base method.
func (m *MockMerchantRepositoryInterface) GetByID(ctx context.Context, id string) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockMerchantRepositoryInterface) GetByUserID(ctx context.Context, userID string) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockMerchantRepositoryInterface) Update(ctx context.Context, id string, req model.UpdateMerchantRequest) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).Update), ctx, id, req)
}

// UpdateStatus mocks base method.
func (m *MockMerchantRepositoryInterface) UpdateStatus(ctx context.Context, id string, status model.MerchantStatus) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).UpdateStatus), ctx, id, status)
}

// ExistsByUserID mocks base method.
func (m *MockMerchantRepositoryInterface) ExistsByUserID(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUserID", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) ExistsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUserID", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).ExistsByUserID), ctx, userID)
}

// GetOperatingHours mocks base method.
func (m *MockMerchantRepositoryInterface) GetOperatingHours(ctx context.Context, merchantID string) ([]model.OperatingHours, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatingHours", ctx, merchantID)
	ret0, _ := ret[0].([]model.OperatingHours)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) GetOperatingHours(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatingHours", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).GetOperatingHours), ctx, merchantID)
}

// UpsertOperatingHours mocks base method.
func (m *MockMerchantRepositoryInterface) UpsertOperatingHours(ctx context.Context, merchantID string, req model.UpsertOperatingHoursRequest) ([]model.OperatingHours, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOperatingHours", ctx, merchantID, req)
	ret0, _ := ret[0].([]model.OperatingHours)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) UpsertOperatingHours(ctx, merchantID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOperatingHours", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).UpsertOperatingHours), ctx, merchantID, req)
}

// ListBankAccounts mocks base method.
func (m *MockMerchantRepositoryInterface) ListBankAccounts(ctx context.Context, merchantID string) ([]model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBankAccounts", ctx, merchantID)
	ret0, _ := ret[0].([]model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) ListBankAccounts(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBankAccounts", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).ListBankAccounts), ctx, merchantID)
}

// AddBankAccount mocks base method.
func (m *MockMerchantRepositoryInterface) AddBankAccount(ctx context.Context, merchantID string, req model.AddBankAccountRequest) (*model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBankAccount", ctx, merchantID, req)
	ret0, _ := ret[0].(*model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) AddBankAccount(ctx, merchantID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBankAccount", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).AddBankAccount), ctx, merchantID, req)
}

// DeleteBankAccount mocks base method.
func (m *MockMerchantRepositoryInterface) DeleteBankAccount(ctx context.Context, accountID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankAccount", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) DeleteBankAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankAccount", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).DeleteBankAccount), ctx, accountID)
}

// SetPrimaryBankAccount mocks base method.
func (m *MockMerchantRepositoryInterface) SetPrimaryBankAccount(ctx context.Context, merchantID, accountID string) (*model.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimaryBankAccount", ctx, merchantID, accountID)
	ret0, _ := ret[0].(*model.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockMerchantRepositoryInterfaceMockRecorder) SetPrimaryBankAccount(ctx, merchantID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimaryBankAccount", reflect.TypeOf((*MockMerchantRepositoryInterface)(nil).SetPrimaryBankAccount), ctx, merchantID, accountID)
}
