// Code generated by MockGen. DO NOT EDIT.
// Source: matching_repository.go
//
// Generated by: mockgen -source=matching_repository.go -destination=../../mocks/repomock/mock_matching_repository.go -package=repomock

package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/zicofarry/clay-app/backend/services/matching-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchingRepositoryInterface is a mock of MatchingRepositoryInterface interface.
type MockMatchingRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMatchingRepositoryInterfaceMockRecorder
}

// MockMatchingRepositoryInterfaceMockRecorder is the mock recorder for MockMatchingRepositoryInterface.
type MockMatchingRepositoryInterfaceMockRecorder struct {
	mock *MockMatchingRepositoryInterface
}

// NewMockMatchingRepositoryInterface creates a new mock instance.
func NewMockMatchingRepositoryInterface(ctrl *gomock.Controller) *MockMatchingRepositoryInterface {
	mock := &MockMatchingRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockMatchingRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchingRepositoryInterface) EXPECT() *MockMatchingRepositoryInterfaceMockRecorder {
	return m.recorder
}

// SetDriverStatus mocks base method.
func (m *MockMatchingRepositoryInterface) SetDriverStatus(ctx context.Context, s *repository.DriverStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDriverStatus", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDriverStatus indicates an expected call of SetDriverStatus.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) SetDriverStatus(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDriverStatus", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).SetDriverStatus), ctx, s)
}

// GetDriverStatus mocks base method.
func (m *MockMatchingRepositoryInterface) GetDriverStatus(ctx context.Context, driverID string) (*repository.DriverStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverStatus", ctx, driverID)
	ret0, _ := ret[0].(*repository.DriverStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverStatus indicates an expected call of GetDriverStatus.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) GetDriverStatus(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverStatus", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).GetDriverStatus), ctx, driverID)
}

// RefreshDriverStatusTTL mocks base method.
func (m *MockMatchingRepositoryInterface) RefreshDriverStatusTTL(ctx context.Context, driverID string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshDriverStatusTTL", ctx, driverID)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshDriverStatusTTL indicates an expected call of RefreshDriverStatusTTL.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) RefreshDriverStatusTTL(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshDriverStatusTTL", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).RefreshDriverStatusTTL), ctx, driverID)
}

// DeleteDriverStatus mocks base method.
func (m *MockMatchingRepositoryInterface) DeleteDriverStatus(ctx context.Context, driverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDriverStatus", ctx, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDriverStatus indicates an expected call of DeleteDriverStatus.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) DeleteDriverStatus(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDriverStatus", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).DeleteDriverStatus), ctx, driverID)
}

// UpdateDriverLocation mocks base method.
func (m *MockMatchingRepositoryInterface) UpdateDriverLocation(ctx context.Context, driverID string, lat, lng float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverLocation", ctx, driverID, lat, lng)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDriverLocation indicates an expected call of UpdateDriverLocation.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) UpdateDriverLocation(ctx, driverID, lat, lng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverLocation", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).UpdateDriverLocation), ctx, driverID, lat, lng)
}

// AddDriverToGeo mocks base method.
func (m *MockMatchingRepositoryInterface) AddDriverToGeo(ctx context.Context, vehicleType, driverID string, lat, lng float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDriverToGeo", ctx, vehicleType, driverID, lat, lng)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDriverToGeo indicates an expected call of AddDriverToGeo.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) AddDriverToGeo(ctx, vehicleType, driverID, lat, lng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDriverToGeo", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).AddDriverToGeo), ctx, vehicleType, driverID, lat, lng)
}

// RemoveDriverFromGeo mocks base method.
func (m *MockMatchingRepositoryInterface) RemoveDriverFromGeo(ctx context.Context, vehicleType, driverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDriverFromGeo", ctx, vehicleType, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDriverFromGeo indicates an expected call of RemoveDriverFromGeo.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) RemoveDriverFromGeo(ctx, vehicleType, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDriverFromGeo", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).RemoveDriverFromGeo), ctx, vehicleType, driverID)
}

// NearbyDrivers mocks base method.
func (m *MockMatchingRepositoryInterface) NearbyDrivers(ctx context.Context, vehicleType string, lat, lng, radiusKm float64, limit int) ([]repository.GeoDriver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NearbyDrivers", ctx, vehicleType, lat, lng, radiusKm, limit)
	ret0, _ := ret[0].([]repository.GeoDriver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NearbyDrivers indicates an expected call of NearbyDrivers.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) NearbyDrivers(ctx, vehicleType, lat, lng, radiusKm, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NearbyDrivers", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).NearbyDrivers), ctx, vehicleType, lat, lng, radiusKm, limit)
}

// SetDriverMode mocks base method.
func (m *MockMatchingRepositoryInterface) SetDriverMode(ctx context.Context, driverID string, mode *repository.DriverMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDriverMode", ctx, driverID, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDriverMode indicates an expected call of SetDriverMode.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) SetDriverMode(ctx, driverID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDriverMode", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).SetDriverMode), ctx, driverID, mode)
}

// GetDriverMode mocks base method.
func (m *MockMatchingRepositoryInterface) GetDriverMode(ctx context.Context, driverID string) (*repository.DriverMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverMode", ctx, driverID)
	ret0, _ := ret[0].(*repository.DriverMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverMode indicates an expected call of GetDriverMode.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) GetDriverMode(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverMode", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).GetDriverMode), ctx, driverID)
}

// DeleteDriverMode mocks base method.
func (m *MockMatchingRepositoryInterface) DeleteDriverMode(ctx context.Context, driverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDriverMode", ctx, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDriverMode indicates an expected call of DeleteDriverMode.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) DeleteDriverMode(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDriverMode", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).DeleteDriverMode), ctx, driverID)
}

// IncrementDriverEarnings mocks base method.
func (m *MockMatchingRepositoryInterface) IncrementDriverEarnings(ctx context.Context, driverID, date string, fare int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementDriverEarnings", ctx, driverID, date, fare)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementDriverEarnings indicates an expected call of IncrementDriverEarnings.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) IncrementDriverEarnings(ctx, driverID, date, fare any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementDriverEarnings", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).IncrementDriverEarnings), ctx, driverID, date, fare)
}

// GetDriverEarnings mocks base method.
func (m *MockMatchingRepositoryInterface) GetDriverEarnings(ctx context.Context, driverID, date string) (*repository.DriverEarnings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverEarnings", ctx, driverID, date)
	ret0, _ := ret[0].(*repository.DriverEarnings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverEarnings indicates an expected call of GetDriverEarnings.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) GetDriverEarnings(ctx, driverID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverEarnings", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).GetDriverEarnings), ctx, driverID, date)
}

// IncrementAcceptance mocks base method.
func (m *MockMatchingRepositoryInterface) IncrementAcceptance(ctx context.Context, driverID string, accepted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAcceptance", ctx, driverID, accepted)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAcceptance indicates an expected call of IncrementAcceptance.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) IncrementAcceptance(ctx, driverID, accepted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAcceptance", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).IncrementAcceptance), ctx, driverID, accepted)
}

// GetAcceptance mocks base method.
func (m *MockMatchingRepositoryInterface) GetAcceptance(ctx context.Context, driverID string) (*repository.DriverAcceptance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAcceptance", ctx, driverID)
	ret0, _ := ret[0].(*repository.DriverAcceptance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAcceptance indicates an expected call of GetAcceptance.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) GetAcceptance(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAcceptance", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).GetAcceptance), ctx, driverID)
}

// SetActiveOrder mocks base method.
func (m *MockMatchingRepositoryInterface) SetActiveOrder(ctx context.Context, driverID, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveOrder", ctx, driverID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActiveOrder indicates an expected call of SetActiveOrder.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) SetActiveOrder(ctx, driverID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveOrder", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).SetActiveOrder), ctx, driverID, orderID)
}

// GetActiveOrder mocks base method.
func (m *MockMatchingRepositoryInterface) GetActiveOrder(ctx context.Context, driverID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrder", ctx, driverID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrder indicates an expected call of GetActiveOrder.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) GetActiveOrder(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrder", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).GetActiveOrder), ctx, driverID)
}

// ClearActiveOrder mocks base method.
func (m *MockMatchingRepositoryInterface) ClearActiveOrder(ctx context.Context, driverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearActiveOrder", ctx, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearActiveOrder indicates an expected call of ClearActiveOrder.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) ClearActiveOrder(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearActiveOrder", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).ClearActiveOrder), ctx, driverID)
}

// SetCachedRating mocks base method.
func (m *MockMatchingRepositoryInterface) SetCachedRating(ctx context.Context, driverID string, rating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCachedRating", ctx, driverID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCachedRating indicates an expected call of SetCachedRating.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) SetCachedRating(ctx, driverID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCachedRating", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).SetCachedRating), ctx, driverID, rating)
}

// GetCachedRating mocks base method.
func (m *MockMatchingRepositoryInterface) GetCachedRating(ctx context.Context, driverID string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedRating", ctx, driverID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedRating indicates an expected call of GetCachedRating.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) GetCachedRating(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedRating", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).GetCachedRating), ctx, driverID)
}

// CreateSession mocks base method.
func (m *MockMatchingRepositoryInterface) CreateSession(ctx context.Context, s *repository.MatchingSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) CreateSession(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).CreateSession), ctx, s)
}

// GetSession mocks base method.
func (m *MockMatchingRepositoryInterface) GetSession(ctx context.Context, orderID string) (*repository.MatchingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, orderID)
	ret0, _ := ret[0].(*repository.MatchingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) GetSession(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).GetSession), ctx, orderID)
}

// UpdateSession mocks base method.
func (m *MockMatchingRepositoryInterface) UpdateSession(ctx context.Context, s *repository.MatchingSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) UpdateSession(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).UpdateSession), ctx, s)
}

// DeleteSession mocks base method.
func (m *MockMatchingRepositoryInterface) DeleteSession(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) DeleteSession(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).DeleteSession), ctx, orderID)
}

// MarkRejected mocks base method.
func (m *MockMatchingRepositoryInterface) MarkRejected(ctx context.Context, orderID, driverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRejected", ctx, orderID, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRejected indicates an expected call of MarkRejected.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) MarkRejected(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRejected", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).MarkRejected), ctx, orderID, driverID)
}

// IsRejected mocks base method.
func (m *MockMatchingRepositoryInterface) IsRejected(ctx context.Context, orderID, driverID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRejected", ctx, orderID, driverID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRejected indicates an expected call of IsRejected.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) IsRejected(ctx, orderID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRejected", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).IsRejected), ctx, orderID, driverID)
}

// UpsertZoneStats mocks base method.
func (m *MockMatchingRepositoryInterface) UpsertZoneStats(ctx context.Context, vehicleType, zoneID string, online, pending int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertZoneStats", ctx, vehicleType, zoneID, online, pending)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertZoneStats indicates an expected call of UpsertZoneStats.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) UpsertZoneStats(ctx, vehicleType, zoneID, online, pending any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertZoneStats", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).UpsertZoneStats), ctx, vehicleType, zoneID, online, pending)
}

// GetZoneStats mocks base method.
func (m *MockMatchingRepositoryInterface) GetZoneStats(ctx context.Context, vehicleType, zoneID string) (*repository.ZoneStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZoneStats", ctx, vehicleType, zoneID)
	ret0, _ := ret[0].(*repository.ZoneStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZoneStats indicates an expected call of GetZoneStats.
func (mr *MockMatchingRepositoryInterfaceMockRecorder) GetZoneStats(ctx, vehicleType, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZoneStats", reflect.TypeOf((*MockMatchingRepositoryInterface)(nil).GetZoneStats), ctx, vehicleType, zoneID)
}
