// Code generated by MockGen. DO NOT EDIT.
// Source: ride_order_repository.go
//
// Generated by: mockgen -source=ride_order_repository.go -destination=../../mocks/repomock/mock_ride_order_repository.go -package=repomock

package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/ride-order-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRideOrderRepositoryInterface is a mock of RideOrderRepositoryInterface interface.
type MockRideOrderRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRideOrderRepositoryInterfaceMockRecorder
}

// MockRideOrderRepositoryInterfaceMockRecorder is the mock recorder for MockRideOrderRepositoryInterface.
type MockRideOrderRepositoryInterfaceMockRecorder struct {
	mock *MockRideOrderRepositoryInterface
}

// NewMockRideOrderRepositoryInterface creates a new mock instance.
func NewMockRideOrderRepositoryInterface(ctrl *gomock.Controller) *MockRideOrderRepositoryInterface {
	mock := &MockRideOrderRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRideOrderRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRideOrderRepositoryInterface) EXPECT() *MockRideOrderRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockRideOrderRepositoryInterface) CreateOrder(ctx context.Context, order *repository.RideOrder) (*repository.RideOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order)
	ret0, _ := ret[0].(*repository.RideOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) CreateOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).CreateOrder), ctx, order)
}

// GetOrderByID mocks base method.
func (m *MockRideOrderRepositoryInterface) GetOrderByID(ctx context.Context, orderID string) (*repository.RideOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, orderID)
	ret0, _ := ret[0].(*repository.RideOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) GetOrderByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).GetOrderByID), ctx, orderID)
}

// GetActiveOrderByUserID mocks base method.
func (m *MockRideOrderRepositoryInterface) GetActiveOrderByUserID(ctx context.Context, userID string) (*repository.RideOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrderByUserID", ctx, userID)
	ret0, _ := ret[0].(*repository.RideOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrderByUserID indicates an expected call of GetActiveOrderByUserID.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) GetActiveOrderByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrderByUserID", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).GetActiveOrderByUserID), ctx, userID)
}

// ListUserHistory mocks base method.
func (m *MockRideOrderRepositoryInterface) ListUserHistory(ctx context.Context, userID string, f repository.HistoryFilter) ([]*repository.RideOrder, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserHistory", ctx, userID, f)
	ret0, _ := ret[0].([]*repository.RideOrder)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserHistory indicates an expected call of ListUserHistory.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) ListUserHistory(ctx, userID, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserHistory", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).ListUserHistory), ctx, userID, f)
}

// UpdateStatus mocks base method.
func (m *MockRideOrderRepositoryInterface) UpdateStatus(ctx context.Context, orderID, fromStatus, toStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, orderID, fromStatus, toStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) UpdateStatus(ctx, orderID, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).UpdateStatus), ctx, orderID, fromStatus, toStatus)
}

// AssignDriver mocks base method.
func (m *MockRideOrderRepositoryInterface) AssignDriver(ctx context.Context, orderID, driverID, otpCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDriver", ctx, orderID, driverID, otpCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignDriver indicates an expected call of AssignDriver.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) AssignDriver(ctx, orderID, driverID, otpCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDriver", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).AssignDriver), ctx, orderID, driverID, otpCode)
}

// SetCancelled mocks base method.
func (m *MockRideOrderRepositoryInterface) SetCancelled(ctx context.Context, orderID, reason, cancelledBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCancelled", ctx, orderID, reason, cancelledBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCancelled indicates an expected call of SetCancelled.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) SetCancelled(ctx, orderID, reason, cancelledBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCancelled", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).SetCancelled), ctx, orderID, reason, cancelledBy)
}

// SetFareFinal mocks base method.
func (m *MockRideOrderRepositoryInterface) SetFareFinal(ctx context.Context, orderID string, fareFinal float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFareFinal", ctx, orderID, fareFinal)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFareFinal indicates an expected call of SetFareFinal.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) SetFareFinal(ctx, orderID, fareFinal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFareFinal", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).SetFareFinal), ctx, orderID, fareFinal)
}

// InsertStateLog mocks base method.
func (m *MockRideOrderRepositoryInterface) InsertStateLog(ctx context.Context, log *repository.OrderStateLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertStateLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertStateLog indicates an expected call of InsertStateLog.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) InsertStateLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertStateLog", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).InsertStateLog), ctx, log)
}

// ListStateLogs mocks base method.
func (m *MockRideOrderRepositoryInterface) ListStateLogs(ctx context.Context, orderID string) ([]*repository.OrderStateLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStateLogs", ctx, orderID)
	ret0, _ := ret[0].([]*repository.OrderStateLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStateLogs indicates an expected call of ListStateLogs.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) ListStateLogs(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStateLogs", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).ListStateLogs), ctx, orderID)
}

// UpsertTripDetails mocks base method.
func (m *MockRideOrderRepositoryInterface) UpsertTripDetails(ctx context.Context, td *repository.TripDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTripDetails", ctx, td)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTripDetails indicates an expected call of UpsertTripDetails.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) UpsertTripDetails(ctx, td any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTripDetails", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).UpsertTripDetails), ctx, td)
}

// GetTripDetails mocks base method.
func (m *MockRideOrderRepositoryInterface) GetTripDetails(ctx context.Context, orderID string) (*repository.TripDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripDetails", ctx, orderID)
	ret0, _ := ret[0].(*repository.TripDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripDetails indicates an expected call of GetTripDetails.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) GetTripDetails(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripDetails", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).GetTripDetails), ctx, orderID)
}

// UpsertFareBreakdown mocks base method.
func (m *MockRideOrderRepositoryInterface) UpsertFareBreakdown(ctx context.Context, fb *repository.FareBreakdown) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFareBreakdown", ctx, fb)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFareBreakdown indicates an expected call of UpsertFareBreakdown.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) UpsertFareBreakdown(ctx, fb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFareBreakdown", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).UpsertFareBreakdown), ctx, fb)
}

// GetFareBreakdown mocks base method.
func (m *MockRideOrderRepositoryInterface) GetFareBreakdown(ctx context.Context, orderID string) (*repository.FareBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareBreakdown", ctx, orderID)
	ret0, _ := ret[0].(*repository.FareBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFareBreakdown indicates an expected call of GetFareBreakdown.
func (mr *MockRideOrderRepositoryInterfaceMockRecorder) GetFareBreakdown(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareBreakdown", reflect.TypeOf((*MockRideOrderRepositoryInterface)(nil).GetFareBreakdown), ctx, orderID)
}
