// Code generated by MockGen. DO NOT EDIT.
// Source: auth_repository.go
//
// Generated by: mockgen -source=auth_repository.go -destination=../../mocks/repomock/mock_auth_repository.go -package=repomock

package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/auth-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepositoryInterface is a mock of AuthRepositoryInterface interface.
type MockAuthRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryInterfaceMockRecorder
}

// MockAuthRepositoryInterfaceMockRecorder is the mock recorder for MockAuthRepositoryInterface.
type MockAuthRepositoryInterfaceMockRecorder struct {
	mock *MockAuthRepositoryInterface
}

// NewMockAuthRepositoryInterface creates a new mock instance.
func NewMockAuthRepositoryInterface(ctrl *gomock.Controller) *MockAuthRepositoryInterface {
	mock := &MockAuthRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepositoryInterface) EXPECT() *MockAuthRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockAuthRepositoryInterface) CreateCredential(ctx context.Context, cred *repository.Credential) (*repository.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, cred)
	ret0, _ := ret[0].(*repository.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockAuthRepositoryInterfaceMockRecorder) CreateCredential(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).CreateCredential), ctx, cred)
}

// FindByID mocks base method.
func (m *MockAuthRepositoryInterface) FindByID(ctx context.Context, id string) (*repository.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*repository.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAuthRepositoryInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).FindByID), ctx, id)
}

// FindByIdentifier mocks base method.
func (m *MockAuthRepositoryInterface) FindByIdentifier(ctx context.Context, identifier string) (*repository.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdentifier", ctx, identifier)
	ret0, _ := ret[0].(*repository.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdentifier indicates an expected call of FindByIdentifier.
func (mr *MockAuthRepositoryInterfaceMockRecorder) FindByIdentifier(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdentifier", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).FindByIdentifier), ctx, identifier)
}

// ExistsByEmailOrPhone mocks base method.
func (m *MockAuthRepositoryInterface) ExistsByEmailOrPhone(ctx context.Context, email, phone string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmailOrPhone", ctx, email, phone)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmailOrPhone indicates an expected call of ExistsByEmailOrPhone.
func (mr *MockAuthRepositoryInterfaceMockRecorder) ExistsByEmailOrPhone(ctx, email, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmailOrPhone", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).ExistsByEmailOrPhone), ctx, email, phone)
}

// UpdatePassword mocks base method.
func (m *MockAuthRepositoryInterface) UpdatePassword(ctx context.Context, userID, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockAuthRepositoryInterfaceMockRecorder) UpdatePassword(ctx, userID, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).UpdatePassword), ctx, userID, hashedPassword)
}

// SetPhoneVerified mocks base method.
func (m *MockAuthRepositoryInterface) SetPhoneVerified(ctx context.Context, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPhoneVerified", ctx, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPhoneVerified indicates an expected call of SetPhoneVerified.
func (mr *MockAuthRepositoryInterfaceMockRecorder) SetPhoneVerified(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPhoneVerified", reflect.TypeOf((*MockAuthRepositoryInterface)(nil).SetPhoneVerified), ctx, phone)
}
