// Code generated by MockGen. DO NOT EDIT.
package repomock

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/tracking-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

type MockTrackingRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingRepositoryInterfaceMockRecorder
}
type MockTrackingRepositoryInterfaceMockRecorder struct{ mock *MockTrackingRepositoryInterface }

func NewMockTrackingRepositoryInterface(ctrl *gomock.Controller) *MockTrackingRepositoryInterface {
	m := &MockTrackingRepositoryInterface{ctrl: ctrl}
	m.recorder = &MockTrackingRepositoryInterfaceMockRecorder{m}
	return m
}
func (m *MockTrackingRepositoryInterface) EXPECT() *MockTrackingRepositoryInterfaceMockRecorder {
	return m.recorder
}

func (m *MockTrackingRepositoryInterface) SaveTripRoute(ctx context.Context, route *repository.TripRoute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTripRoute", ctx, route)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockTrackingRepositoryInterfaceMockRecorder) SaveTripRoute(ctx, route any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTripRoute", reflect.TypeOf((*MockTrackingRepositoryInterface)(nil).SaveTripRoute), ctx, route)
}

func (m *MockTrackingRepositoryInterface) GetTripRoute(ctx context.Context, orderID string) (*repository.TripRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripRoute", ctx, orderID)
	ret0, _ := ret[0].(*repository.TripRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockTrackingRepositoryInterfaceMockRecorder) GetTripRoute(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripRoute", reflect.TypeOf((*MockTrackingRepositoryInterface)(nil).GetTripRoute), ctx, orderID)
}
