// Code generated by MockGen. DO NOT EDIT.
// Source: security_service.go
//
// Generated by: mockgen -source=security_service.go -destination=../../mocks/mock_security_service.go -package=mocks

package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/security-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityServiceInterface is a mock of SecurityServiceInterface interface.
type MockSecurityServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityServiceInterfaceMockRecorder
}

// MockSecurityServiceInterfaceMockRecorder is the mock recorder for MockSecurityServiceInterface.
type MockSecurityServiceInterfaceMockRecorder struct {
	mock *MockSecurityServiceInterface
}

// NewMockSecurityServiceInterface creates a new mock instance.
func NewMockSecurityServiceInterface(ctrl *gomock.Controller) *MockSecurityServiceInterface {
	mock := &MockSecurityServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSecurityServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityServiceInterface) EXPECT() *MockSecurityServiceInterfaceMockRecorder {
	return m.recorder
}

// RecordLoginAttempt mocks base method.
func (m *MockSecurityServiceInterface) RecordLoginAttempt(ctx context.Context, req *service.RecordLoginAttemptRequest) (*service.RecordLoginAttemptResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLoginAttempt", ctx, req)
	ret0, _ := ret[0].(*service.RecordLoginAttemptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordLoginAttempt indicates an expected call of RecordLoginAttempt.
func (mr *MockSecurityServiceInterfaceMockRecorder) RecordLoginAttempt(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLoginAttempt", reflect.TypeOf((*MockSecurityServiceInterface)(nil).RecordLoginAttempt), ctx, req)
}

// ListMyLoginAttempts mocks base method.
func (m *MockSecurityServiceInterface) ListMyLoginAttempts(ctx context.Context, userID string, q service.LoginAttemptQuery) (*service.LoginAttemptListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyLoginAttempts", ctx, userID, q)
	ret0, _ := ret[0].(*service.LoginAttemptListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyLoginAttempts indicates an expected call of ListMyLoginAttempts.
func (mr *MockSecurityServiceInterfaceMockRecorder) ListMyLoginAttempts(ctx, userID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyLoginAttempts", reflect.TypeOf((*MockSecurityServiceInterface)(nil).ListMyLoginAttempts), ctx, userID, q)
}

// AdminListLoginAttempts mocks base method.
func (m *MockSecurityServiceInterface) AdminListLoginAttempts(ctx context.Context, q service.LoginAttemptQuery) (*service.LoginAttemptListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListLoginAttempts", ctx, q)
	ret0, _ := ret[0].(*service.LoginAttemptListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListLoginAttempts indicates an expected call of AdminListLoginAttempts.
func (mr *MockSecurityServiceInterfaceMockRecorder) AdminListLoginAttempts(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListLoginAttempts", reflect.TypeOf((*MockSecurityServiceInterface)(nil).AdminListLoginAttempts), ctx, q)
}

// CreateFraudFlag mocks base method.
func (m *MockSecurityServiceInterface) CreateFraudFlag(ctx context.Context, adminID string, req *service.CreateFraudFlagRequest) (*service.FraudFlagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFraudFlag", ctx, adminID, req)
	ret0, _ := ret[0].(*service.FraudFlagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFraudFlag indicates an expected call of CreateFraudFlag.
func (mr *MockSecurityServiceInterfaceMockRecorder) CreateFraudFlag(ctx, adminID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFraudFlag", reflect.TypeOf((*MockSecurityServiceInterface)(nil).CreateFraudFlag), ctx, adminID, req)
}

// GetFraudFlag mocks base method.
func (m *MockSecurityServiceInterface) GetFraudFlag(ctx context.Context, flagID string) (*service.FraudFlagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFraudFlag", ctx, flagID)
	ret0, _ := ret[0].(*service.FraudFlagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFraudFlag indicates an expected call of GetFraudFlag.
func (mr *MockSecurityServiceInterfaceMockRecorder) GetFraudFlag(ctx, flagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFraudFlag", reflect.TypeOf((*MockSecurityServiceInterface)(nil).GetFraudFlag), ctx, flagID)
}

// ListFraudFlags mocks base method.
func (m *MockSecurityServiceInterface) ListFraudFlags(ctx context.Context, q service.FraudFlagQuery) (*service.FraudFlagListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFraudFlags", ctx, q)
	ret0, _ := ret[0].(*service.FraudFlagListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFraudFlags indicates an expected call of ListFraudFlags.
func (mr *MockSecurityServiceInterfaceMockRecorder) ListFraudFlags(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFraudFlags", reflect.TypeOf((*MockSecurityServiceInterface)(nil).ListFraudFlags), ctx, q)
}

// ResolveFraudFlag mocks base method.
func (m *MockSecurityServiceInterface) ResolveFraudFlag(ctx context.Context, flagID, adminID string, req *service.ResolveFraudFlagRequest) (*service.FraudFlagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveFraudFlag", ctx, flagID, adminID, req)
	ret0, _ := ret[0].(*service.FraudFlagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveFraudFlag indicates an expected call of ResolveFraudFlag.
func (mr *MockSecurityServiceInterfaceMockRecorder) ResolveFraudFlag(ctx, flagID, adminID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveFraudFlag", reflect.TypeOf((*MockSecurityServiceInterface)(nil).ResolveFraudFlag), ctx, flagID, adminID, req)
}

// GetUserFraudSummary mocks base method.
func (m *MockSecurityServiceInterface) GetUserFraudSummary(ctx context.Context, userID string) (*service.UserFraudSummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFraudSummary", ctx, userID)
	ret0, _ := ret[0].(*service.UserFraudSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFraudSummary indicates an expected call of GetUserFraudSummary.
func (mr *MockSecurityServiceInterfaceMockRecorder) GetUserFraudSummary(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFraudSummary", reflect.TypeOf((*MockSecurityServiceInterface)(nil).GetUserFraudSummary), ctx, userID)
}

// BlockIP mocks base method.
func (m *MockSecurityServiceInterface) BlockIP(ctx context.Context, adminID string, req *service.BlockIPRequest) (*service.IPBlacklistResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockIP", ctx, adminID, req)
	ret0, _ := ret[0].(*service.IPBlacklistResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockIP indicates an expected call of BlockIP.
func (mr *MockSecurityServiceInterfaceMockRecorder) BlockIP(ctx, adminID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockIP", reflect.TypeOf((*MockSecurityServiceInterface)(nil).BlockIP), ctx, adminID, req)
}

// UnblockIP mocks base method.
func (m *MockSecurityServiceInterface) UnblockIP(ctx context.Context, blockID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockIP", ctx, blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockIP indicates an expected call of UnblockIP.
func (mr *MockSecurityServiceInterfaceMockRecorder) UnblockIP(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockIP", reflect.TypeOf((*MockSecurityServiceInterface)(nil).UnblockIP), ctx, blockID)
}

// ListBlockedIPs mocks base method.
func (m *MockSecurityServiceInterface) ListBlockedIPs(ctx context.Context, q service.IPBlacklistQuery) (*service.IPBlacklistListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlockedIPs", ctx, q)
	ret0, _ := ret[0].(*service.IPBlacklistListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockedIPs indicates an expected call of ListBlockedIPs.
func (mr *MockSecurityServiceInterfaceMockRecorder) ListBlockedIPs(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockedIPs", reflect.TypeOf((*MockSecurityServiceInterface)(nil).ListBlockedIPs), ctx, q)
}

// ValidateIP mocks base method.
func (m *MockSecurityServiceInterface) ValidateIP(ctx context.Context, req *service.ValidateIPRequest) (*service.ValidateIPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateIP", ctx, req)
	ret0, _ := ret[0].(*service.ValidateIPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateIP indicates an expected call of ValidateIP.
func (mr *MockSecurityServiceInterfaceMockRecorder) ValidateIP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateIP", reflect.TypeOf((*MockSecurityServiceInterface)(nil).ValidateIP), ctx, req)
}

// ValidateUser mocks base method.
func (m *MockSecurityServiceInterface) ValidateUser(ctx context.Context, req *service.ValidateUserRequest) (*service.ValidateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUser", ctx, req)
	ret0, _ := ret[0].(*service.ValidateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUser indicates an expected call of ValidateUser.
func (mr *MockSecurityServiceInterfaceMockRecorder) ValidateUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUser", reflect.TypeOf((*MockSecurityServiceInterface)(nil).ValidateUser), ctx, req)
}
