// Code generated by MockGen. DO NOT EDIT.
// Source: notification_service.go
//
// Generated by this command:
//
//	mockgen -source=notification_service.go -destination=../../mocks/mock_notification_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/zicofarry/clay-app/backend/services/notification-service/internal/repository"
	service "github.com/zicofarry/clay-app/backend/services/notification-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationServiceInterface is a mock of NotificationServiceInterface interface.
type MockNotificationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceInterfaceMockRecorder is the mock recorder for MockNotificationServiceInterface.
type MockNotificationServiceInterfaceMockRecorder struct {
	mock *MockNotificationServiceInterface
}

// NewMockNotificationServiceInterface creates a new mock instance.
func NewMockNotificationServiceInterface(ctrl *gomock.Controller) *MockNotificationServiceInterface {
	mock := &MockNotificationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationServiceInterface) EXPECT() *MockNotificationServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateTemplate mocks base method.
func (m *MockNotificationServiceInterface) CreateTemplate(ctx context.Context, req *service.CreateTemplateRequest) (*repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, req)
	ret0, _ := ret[0].(*repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockNotificationServiceInterfaceMockRecorder) CreateTemplate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockNotificationServiceInterface)(nil).CreateTemplate), ctx, req)
}

// DeactivateDeviceToken mocks base method.
func (m *MockNotificationServiceInterface) DeactivateDeviceToken(ctx context.Context, userID, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateDeviceToken", ctx, userID, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateDeviceToken indicates an expected call of DeactivateDeviceToken.
func (mr *MockNotificationServiceInterfaceMockRecorder) DeactivateDeviceToken(ctx, userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateDeviceToken", reflect.TypeOf((*MockNotificationServiceInterface)(nil).DeactivateDeviceToken), ctx, userID, tokenID)
}

// DeleteTemplate mocks base method.
func (m *MockNotificationServiceInterface) DeleteTemplate(ctx context.Context, templateID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockNotificationServiceInterfaceMockRecorder) DeleteTemplate(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockNotificationServiceInterface)(nil).DeleteTemplate), ctx, templateID)
}

// GetNotification mocks base method.
func (m *MockNotificationServiceInterface) GetNotification(ctx context.Context, userID, notificationID string) (*repository.NotificationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotification", ctx, userID, notificationID)
	ret0, _ := ret[0].(*repository.NotificationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotification indicates an expected call of GetNotification.
func (mr *MockNotificationServiceInterfaceMockRecorder) GetNotification(ctx, userID, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotification", reflect.TypeOf((*MockNotificationServiceInterface)(nil).GetNotification), ctx, userID, notificationID)
}

// GetPreferences mocks base method.
func (m *MockNotificationServiceInterface) GetPreferences(ctx context.Context, userID string) (*repository.NotificationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreferences", ctx, userID)
	ret0, _ := ret[0].(*repository.NotificationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreferences indicates an expected call of GetPreferences.
func (mr *MockNotificationServiceInterfaceMockRecorder) GetPreferences(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreferences", reflect.TypeOf((*MockNotificationServiceInterface)(nil).GetPreferences), ctx, userID)
}

// GetTemplate mocks base method.
func (m *MockNotificationServiceInterface) GetTemplate(ctx context.Context, templateID string) (*repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", ctx, templateID)
	ret0, _ := ret[0].(*repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockNotificationServiceInterfaceMockRecorder) GetTemplate(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockNotificationServiceInterface)(nil).GetTemplate), ctx, templateID)
}

// ListDeviceTokens mocks base method.
func (m *MockNotificationServiceInterface) ListDeviceTokens(ctx context.Context, userID string, activeOnly bool) ([]repository.DeviceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeviceTokens", ctx, userID, activeOnly)
	ret0, _ := ret[0].([]repository.DeviceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeviceTokens indicates an expected call of ListDeviceTokens.
func (mr *MockNotificationServiceInterfaceMockRecorder) ListDeviceTokens(ctx, userID, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeviceTokens", reflect.TypeOf((*MockNotificationServiceInterface)(nil).ListDeviceTokens), ctx, userID, activeOnly)
}

// ListNotifications mocks base method.
func (m *MockNotificationServiceInterface) ListNotifications(ctx context.Context, userID string, page, limit int) ([]repository.NotificationLog, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, userID, page, limit)
	ret0, _ := ret[0].([]repository.NotificationLog)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockNotificationServiceInterfaceMockRecorder) ListNotifications(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockNotificationServiceInterface)(nil).ListNotifications), ctx, userID, page, limit)
}

// ListTemplates mocks base method.
func (m *MockNotificationServiceInterface) ListTemplates(ctx context.Context) ([]repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", ctx)
	ret0, _ := ret[0].([]repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockNotificationServiceInterfaceMockRecorder) ListTemplates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockNotificationServiceInterface)(nil).ListTemplates), ctx)
}

// PreviewTemplate mocks base method.
func (m *MockNotificationServiceInterface) PreviewTemplate(ctx context.Context, templateID string, req *service.PreviewTemplateRequest) (*service.PreviewTemplateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewTemplate", ctx, templateID, req)
	ret0, _ := ret[0].(*service.PreviewTemplateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewTemplate indicates an expected call of PreviewTemplate.
func (mr *MockNotificationServiceInterfaceMockRecorder) PreviewTemplate(ctx, templateID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewTemplate", reflect.TypeOf((*MockNotificationServiceInterface)(nil).PreviewTemplate), ctx, templateID, req)
}

// RegisterDeviceToken mocks base method.
func (m *MockNotificationServiceInterface) RegisterDeviceToken(ctx context.Context, userID string, req *service.RegisterDeviceTokenRequest) (*repository.DeviceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDeviceToken", ctx, userID, req)
	ret0, _ := ret[0].(*repository.DeviceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterDeviceToken indicates an expected call of RegisterDeviceToken.
func (mr *MockNotificationServiceInterfaceMockRecorder) RegisterDeviceToken(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDeviceToken", reflect.TypeOf((*MockNotificationServiceInterface)(nil).RegisterDeviceToken), ctx, userID, req)
}

// SendBatchNotification mocks base method.
func (m *MockNotificationServiceInterface) SendBatchNotification(ctx context.Context, req *service.InternalSendBatchRequest) (*service.InternalSendBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatchNotification", ctx, req)
	ret0, _ := ret[0].(*service.InternalSendBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendBatchNotification indicates an expected call of SendBatchNotification.
func (mr *MockNotificationServiceInterfaceMockRecorder) SendBatchNotification(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatchNotification", reflect.TypeOf((*MockNotificationServiceInterface)(nil).SendBatchNotification), ctx, req)
}

// SendNotification mocks base method.
func (m *MockNotificationServiceInterface) SendNotification(ctx context.Context, req *service.InternalSendRequest) (*service.InternalSendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, req)
	ret0, _ := ret[0].(*service.InternalSendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockNotificationServiceInterfaceMockRecorder) SendNotification(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockNotificationServiceInterface)(nil).SendNotification), ctx, req)
}

// UpdatePreferences mocks base method.
func (m *MockNotificationServiceInterface) UpdatePreferences(ctx context.Context, userID string, req *service.UpdatePreferenceRequest) (*repository.NotificationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreferences", ctx, userID, req)
	ret0, _ := ret[0].(*repository.NotificationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePreferences indicates an expected call of UpdatePreferences.
func (mr *MockNotificationServiceInterfaceMockRecorder) UpdatePreferences(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreferences", reflect.TypeOf((*MockNotificationServiceInterface)(nil).UpdatePreferences), ctx, userID, req)
}

// UpdateTemplate mocks base method.
func (m *MockNotificationServiceInterface) UpdateTemplate(ctx context.Context, templateID string, req *service.UpdateTemplateRequest) (*repository.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, templateID, req)
	ret0, _ := ret[0].(*repository.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockNotificationServiceInterfaceMockRecorder) UpdateTemplate(ctx, templateID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockNotificationServiceInterface)(nil).UpdateTemplate), ctx, templateID, req)
}
