// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Github\clay\clay-search-service\internal\service\search_service.go
//
// Generated by this command:
//
//	mockgen -source=D:\Github\clay\clay-search-service\internal\service\search_service.go -destination=D:\Github\clay\clay-search-service\mocks\mock_search_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/zicofarry/clay-app/backend/services/search-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchServiceInterface is a mock of SearchServiceInterface interface.
type MockSearchServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockSearchServiceInterfaceMockRecorder is the mock recorder for MockSearchServiceInterface.
type MockSearchServiceInterfaceMockRecorder struct {
	mock *MockSearchServiceInterface
}

// NewMockSearchServiceInterface creates a new mock instance.
func NewMockSearchServiceInterface(ctrl *gomock.Controller) *MockSearchServiceInterface {
	mock := &MockSearchServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSearchServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchServiceInterface) EXPECT() *MockSearchServiceInterfaceMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockSearchServiceInterface) CheckHealth(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockSearchServiceInterfaceMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockSearchServiceInterface)(nil).CheckHealth), ctx)
}

// DeleteMenuItemIndex mocks base method.
func (m *MockSearchServiceInterface) DeleteMenuItemIndex(ctx context.Context, itemId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMenuItemIndex", ctx, itemId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMenuItemIndex indicates an expected call of DeleteMenuItemIndex.
func (mr *MockSearchServiceInterfaceMockRecorder) DeleteMenuItemIndex(ctx, itemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMenuItemIndex", reflect.TypeOf((*MockSearchServiceInterface)(nil).DeleteMenuItemIndex), ctx, itemId)
}

// DeleteMerchantIndex mocks base method.
func (m *MockSearchServiceInterface) DeleteMerchantIndex(ctx context.Context, merchantId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMerchantIndex", ctx, merchantId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMerchantIndex indicates an expected call of DeleteMerchantIndex.
func (mr *MockSearchServiceInterfaceMockRecorder) DeleteMerchantIndex(ctx, merchantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMerchantIndex", reflect.TypeOf((*MockSearchServiceInterface)(nil).DeleteMerchantIndex), ctx, merchantId)
}

// GetPopular mocks base method.
func (m *MockSearchServiceInterface) GetPopular(ctx context.Context, query map[string]string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopular", ctx, query)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopular indicates an expected call of GetPopular.
func (mr *MockSearchServiceInterfaceMockRecorder) GetPopular(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopular", reflect.TypeOf((*MockSearchServiceInterface)(nil).GetPopular), ctx, query)
}

// GetTrending mocks base method.
func (m *MockSearchServiceInterface) GetTrending(ctx context.Context, query map[string]string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrending", ctx, query)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrending indicates an expected call of GetTrending.
func (mr *MockSearchServiceInterfaceMockRecorder) GetTrending(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrending", reflect.TypeOf((*MockSearchServiceInterface)(nil).GetTrending), ctx, query)
}

// IndexMenuItem mocks base method.
func (m *MockSearchServiceInterface) IndexMenuItem(ctx context.Context, payload model.MenuItemDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMenuItem", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMenuItem indicates an expected call of IndexMenuItem.
func (mr *MockSearchServiceInterfaceMockRecorder) IndexMenuItem(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMenuItem", reflect.TypeOf((*MockSearchServiceInterface)(nil).IndexMenuItem), ctx, payload)
}

// IndexMerchant mocks base method.
func (m *MockSearchServiceInterface) IndexMerchant(ctx context.Context, payload model.MerchantDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMerchant", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMerchant indicates an expected call of IndexMerchant.
func (mr *MockSearchServiceInterfaceMockRecorder) IndexMerchant(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMerchant", reflect.TypeOf((*MockSearchServiceInterface)(nil).IndexMerchant), ctx, payload)
}

// SearchMenuItems mocks base method.
func (m *MockSearchServiceInterface) SearchMenuItems(ctx context.Context, query map[string]string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMenuItems", ctx, query)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMenuItems indicates an expected call of SearchMenuItems.
func (mr *MockSearchServiceInterfaceMockRecorder) SearchMenuItems(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMenuItems", reflect.TypeOf((*MockSearchServiceInterface)(nil).SearchMenuItems), ctx, query)
}

// SearchMerchants mocks base method.
func (m *MockSearchServiceInterface) SearchMerchants(ctx context.Context, query map[string]string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMerchants", ctx, query)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMerchants indicates an expected call of SearchMerchants.
func (mr *MockSearchServiceInterfaceMockRecorder) SearchMerchants(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMerchants", reflect.TypeOf((*MockSearchServiceInterface)(nil).SearchMerchants), ctx, query)
}

// SearchSuggest mocks base method.
func (m *MockSearchServiceInterface) SearchSuggest(ctx context.Context, query map[string]string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSuggest", ctx, query)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSuggest indicates an expected call of SearchSuggest.
func (mr *MockSearchServiceInterfaceMockRecorder) SearchSuggest(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSuggest", reflect.TypeOf((*MockSearchServiceInterface)(nil).SearchSuggest), ctx, query)
}

// TriggerReindex mocks base method.
func (m *MockSearchServiceInterface) TriggerReindex(ctx context.Context, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerReindex", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerReindex indicates an expected call of TriggerReindex.
func (mr *MockSearchServiceInterfaceMockRecorder) TriggerReindex(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerReindex", reflect.TypeOf((*MockSearchServiceInterface)(nil).TriggerReindex), ctx, payload)
}
