// Code generated by MockGen. DO NOT EDIT.
// Source: sms_service.go
//
// Generated by this command:
//
//	mockgen -source=sms_service.go -destination=../../mocks/mock_sms_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/sms-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSMSServiceInterface is a mock of SMSServiceInterface interface.
type MockSMSServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSMSServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockSMSServiceInterfaceMockRecorder is the mock recorder for MockSMSServiceInterface.
type MockSMSServiceInterfaceMockRecorder struct {
	mock *MockSMSServiceInterface
}

// NewMockSMSServiceInterface creates a new mock instance.
func NewMockSMSServiceInterface(ctrl *gomock.Controller) *MockSMSServiceInterface {
	mock := &MockSMSServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSMSServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMSServiceInterface) EXPECT() *MockSMSServiceInterfaceMockRecorder {
	return m.recorder
}

// GetSMSStatus mocks base method.
func (m *MockSMSServiceInterface) GetSMSStatus(ctx context.Context, smsID string) (*service.SmsStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSMSStatus", ctx, smsID)
	ret0, _ := ret[0].(*service.SmsStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSMSStatus indicates an expected call of GetSMSStatus.
func (mr *MockSMSServiceInterfaceMockRecorder) GetSMSStatus(ctx, smsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSMSStatus", reflect.TypeOf((*MockSMSServiceInterface)(nil).GetSMSStatus), ctx, smsID)
}

// ProcessWebhook mocks base method.
func (m *MockSMSServiceInterface) ProcessWebhook(ctx context.Context, payload service.WebhookPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWebhook", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessWebhook indicates an expected call of ProcessWebhook.
func (mr *MockSMSServiceInterfaceMockRecorder) ProcessWebhook(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWebhook", reflect.TypeOf((*MockSMSServiceInterface)(nil).ProcessWebhook), ctx, payload)
}

// SendOTP mocks base method.
func (m *MockSMSServiceInterface) SendOTP(ctx context.Context, req service.SendOTPRequest) (*service.SendOTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOTP", ctx, req)
	ret0, _ := ret[0].(*service.SendOTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendOTP indicates an expected call of SendOTP.
func (mr *MockSMSServiceInterfaceMockRecorder) SendOTP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOTP", reflect.TypeOf((*MockSMSServiceInterface)(nil).SendOTP), ctx, req)
}

// SendSMS mocks base method.
func (m *MockSMSServiceInterface) SendSMS(ctx context.Context, req service.SendSMSRequest, idempotencyKey string) (*service.SendSMSResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSMS", ctx, req, idempotencyKey)
	ret0, _ := ret[0].(*service.SendSMSResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendSMS indicates an expected call of SendSMS.
func (mr *MockSMSServiceInterfaceMockRecorder) SendSMS(ctx, req, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSMS", reflect.TypeOf((*MockSMSServiceInterface)(nil).SendSMS), ctx, req, idempotencyKey)
}

// VerifyOTP mocks base method.
func (m *MockSMSServiceInterface) VerifyOTP(ctx context.Context, req service.VerifyOTPRequest) (*service.VerifyOTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOTP", ctx, req)
	ret0, _ := ret[0].(*service.VerifyOTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyOTP indicates an expected call of VerifyOTP.
func (mr *MockSMSServiceInterfaceMockRecorder) VerifyOTP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOTP", reflect.TypeOf((*MockSMSServiceInterface)(nil).VerifyOTP), ctx, req)
}
