// Code generated by MockGen. DO NOT EDIT.
package cachemock

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/zicofarry/clay-app/backend/services/tracking-service/internal/cache"
	gomock "go.uber.org/mock/gomock"
)

type MockTrackingCacheInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingCacheInterfaceMockRecorder
}
type MockTrackingCacheInterfaceMockRecorder struct{ mock *MockTrackingCacheInterface }

func NewMockTrackingCacheInterface(ctrl *gomock.Controller) *MockTrackingCacheInterface {
	m := &MockTrackingCacheInterface{ctrl: ctrl}
	m.recorder = &MockTrackingCacheInterfaceMockRecorder{m}
	return m
}
func (m *MockTrackingCacheInterface) EXPECT() *MockTrackingCacheInterfaceMockRecorder {
	return m.recorder
}

func (m *MockTrackingCacheInterface) SetOrderPosition(ctx context.Context, pos *cache.OrderPosition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrderPosition", ctx, pos)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockTrackingCacheInterfaceMockRecorder) SetOrderPosition(ctx, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrderPosition", reflect.TypeOf((*MockTrackingCacheInterface)(nil).SetOrderPosition), ctx, pos)
}

func (m *MockTrackingCacheInterface) GetOrderPosition(ctx context.Context, orderID string) (*cache.OrderPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderPosition", ctx, orderID)
	ret0, _ := ret[0].(*cache.OrderPosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockTrackingCacheInterfaceMockRecorder) GetOrderPosition(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderPosition", reflect.TypeOf((*MockTrackingCacheInterface)(nil).GetOrderPosition), ctx, orderID)
}

func (m *MockTrackingCacheInterface) DeleteOrderPosition(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderPosition", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockTrackingCacheInterfaceMockRecorder) DeleteOrderPosition(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderPosition", reflect.TypeOf((*MockTrackingCacheInterface)(nil).DeleteOrderPosition), ctx, orderID)
}

func (m *MockTrackingCacheInterface) AppendRoutePoint(ctx context.Context, orderID string, lat, lng float64, ts time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendRoutePoint", ctx, orderID, lat, lng, ts)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockTrackingCacheInterfaceMockRecorder) AppendRoutePoint(ctx, orderID, lat, lng, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRoutePoint", reflect.TypeOf((*MockTrackingCacheInterface)(nil).AppendRoutePoint), ctx, orderID, lat, lng, ts)
}

func (m *MockTrackingCacheInterface) GetActiveRoutePoints(ctx context.Context, orderID string) ([]cache.RoutePointData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRoutePoints", ctx, orderID)
	ret0, _ := ret[0].([]cache.RoutePointData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockTrackingCacheInterfaceMockRecorder) GetActiveRoutePoints(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRoutePoints", reflect.TypeOf((*MockTrackingCacheInterface)(nil).GetActiveRoutePoints), ctx, orderID)
}

func (m *MockTrackingCacheInterface) ClearActiveRoutePoints(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearActiveRoutePoints", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}
func (mr *MockTrackingCacheInterfaceMockRecorder) ClearActiveRoutePoints(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearActiveRoutePoints", reflect.TypeOf((*MockTrackingCacheInterface)(nil).ClearActiveRoutePoints), ctx, orderID)
}
