// Code generated by MockGen. DO NOT EDIT.
// Source: audit_service.go
//
// Generated by this command:
//
//	mockgen -source=audit_service.go -destination=../../mocks/mock_audit_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zicofarry/clay-app/backend/services/audit-log-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditServiceInterface is a mock of AuditServiceInterface interface.
type MockAuditServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAuditServiceInterfaceMockRecorder is the mock recorder for MockAuditServiceInterface.
type MockAuditServiceInterfaceMockRecorder struct {
	mock *MockAuditServiceInterface
}

// NewMockAuditServiceInterface creates a new mock instance.
func NewMockAuditServiceInterface(ctrl *gomock.Controller) *MockAuditServiceInterface {
	mock := &MockAuditServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuditServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditServiceInterface) EXPECT() *MockAuditServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateLog mocks base method.
func (m *MockAuditServiceInterface) CreateLog(ctx context.Context, req *service.CreateAuditLogRequest) (*service.AuditLogDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLog", ctx, req)
	ret0, _ := ret[0].(*service.AuditLogDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLog indicates an expected call of CreateLog.
func (mr *MockAuditServiceInterfaceMockRecorder) CreateLog(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLog", reflect.TypeOf((*MockAuditServiceInterface)(nil).CreateLog), ctx, req)
}

// CreateLogBatch mocks base method.
func (m *MockAuditServiceInterface) CreateLogBatch(ctx context.Context, reqs []service.CreateAuditLogRequest) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLogBatch", ctx, reqs)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateLogBatch indicates an expected call of CreateLogBatch.
func (mr *MockAuditServiceInterfaceMockRecorder) CreateLogBatch(ctx, reqs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLogBatch", reflect.TypeOf((*MockAuditServiceInterface)(nil).CreateLogBatch), ctx, reqs)
}

// GetLog mocks base method.
func (m *MockAuditServiceInterface) GetLog(ctx context.Context, logID string) (*service.AuditLogDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLog", ctx, logID)
	ret0, _ := ret[0].(*service.AuditLogDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLog indicates an expected call of GetLog.
func (mr *MockAuditServiceInterfaceMockRecorder) GetLog(ctx, logID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLog", reflect.TypeOf((*MockAuditServiceInterface)(nil).GetLog), ctx, logID)
}

// SearchLogs mocks base method.
func (m *MockAuditServiceInterface) SearchLogs(ctx context.Context, params service.SearchLogsParams) (*service.AuditLogListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchLogs", ctx, params)
	ret0, _ := ret[0].(*service.AuditLogListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchLogs indicates an expected call of SearchLogs.
func (mr *MockAuditServiceInterfaceMockRecorder) SearchLogs(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchLogs", reflect.TypeOf((*MockAuditServiceInterface)(nil).SearchLogs), ctx, params)
}
