// Code generated by MockGen. DO NOT EDIT.
// Source: security_repository.go
//
// Generated by: mockgen -source=security_repository.go -destination=../../mocks/repomock/mock_security_repository.go -package=repomock

package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/zicofarry/clay-app/backend/services/security-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityRepositoryInterface is a mock of SecurityRepositoryInterface interface.
type MockSecurityRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityRepositoryInterfaceMockRecorder
}

// MockSecurityRepositoryInterfaceMockRecorder is the mock recorder for MockSecurityRepositoryInterface.
type MockSecurityRepositoryInterfaceMockRecorder struct {
	mock *MockSecurityRepositoryInterface
}

// NewMockSecurityRepositoryInterface creates a new mock instance.
func NewMockSecurityRepositoryInterface(ctrl *gomock.Controller) *MockSecurityRepositoryInterface {
	mock := &MockSecurityRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSecurityRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityRepositoryInterface) EXPECT() *MockSecurityRepositoryInterfaceMockRecorder {
	return m.recorder
}

// InsertLoginAttempt mocks base method.
func (m *MockSecurityRepositoryInterface) InsertLoginAttempt(ctx context.Context, a *repository.LoginAttempt) (*repository.LoginAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLoginAttempt", ctx, a)
	ret0, _ := ret[0].(*repository.LoginAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertLoginAttempt indicates an expected call of InsertLoginAttempt.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) InsertLoginAttempt(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLoginAttempt", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).InsertLoginAttempt), ctx, a)
}

// ListLoginAttempts mocks base method.
func (m *MockSecurityRepositoryInterface) ListLoginAttempts(ctx context.Context, f repository.LoginAttemptFilter) ([]*repository.LoginAttempt, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoginAttempts", ctx, f)
	ret0, _ := ret[0].([]*repository.LoginAttempt)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLoginAttempts indicates an expected call of ListLoginAttempts.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) ListLoginAttempts(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoginAttempts", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).ListLoginAttempts), ctx, f)
}

// CountFailedLoginsInWindow mocks base method.
func (m *MockSecurityRepositoryInterface) CountFailedLoginsInWindow(ctx context.Context, userID string, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFailedLoginsInWindow", ctx, userID, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFailedLoginsInWindow indicates an expected call of CountFailedLoginsInWindow.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) CountFailedLoginsInWindow(ctx, userID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFailedLoginsInWindow", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).CountFailedLoginsInWindow), ctx, userID, since)
}

// InsertFraudFlag mocks base method.
func (m *MockSecurityRepositoryInterface) InsertFraudFlag(ctx context.Context, f *repository.FraudFlag) (*repository.FraudFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFraudFlag", ctx, f)
	ret0, _ := ret[0].(*repository.FraudFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertFraudFlag indicates an expected call of InsertFraudFlag.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) InsertFraudFlag(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFraudFlag", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).InsertFraudFlag), ctx, f)
}

// GetFraudFlagByID mocks base method.
func (m *MockSecurityRepositoryInterface) GetFraudFlagByID(ctx context.Context, flagID string) (*repository.FraudFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFraudFlagByID", ctx, flagID)
	ret0, _ := ret[0].(*repository.FraudFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFraudFlagByID indicates an expected call of GetFraudFlagByID.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) GetFraudFlagByID(ctx, flagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFraudFlagByID", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).GetFraudFlagByID), ctx, flagID)
}

// ListFraudFlags mocks base method.
func (m *MockSecurityRepositoryInterface) ListFraudFlags(ctx context.Context, f repository.FraudFlagFilter) ([]*repository.FraudFlag, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFraudFlags", ctx, f)
	ret0, _ := ret[0].([]*repository.FraudFlag)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFraudFlags indicates an expected call of ListFraudFlags.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) ListFraudFlags(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFraudFlags", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).ListFraudFlags), ctx, f)
}

// ResolveFraudFlag mocks base method.
func (m *MockSecurityRepositoryInterface) ResolveFraudFlag(ctx context.Context, flagID, resolvedBy, note string, resolvedAt time.Time) (*repository.FraudFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveFraudFlag", ctx, flagID, resolvedBy, note, resolvedAt)
	ret0, _ := ret[0].(*repository.FraudFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveFraudFlag indicates an expected call of ResolveFraudFlag.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) ResolveFraudFlag(ctx, flagID, resolvedBy, note, resolvedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveFraudFlag", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).ResolveFraudFlag), ctx, flagID, resolvedBy, note, resolvedAt)
}

// CountActiveFlagsForUser mocks base method.
func (m *MockSecurityRepositoryInterface) CountActiveFlagsForUser(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveFlagsForUser", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveFlagsForUser indicates an expected call of CountActiveFlagsForUser.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) CountActiveFlagsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveFlagsForUser", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).CountActiveFlagsForUser), ctx, userID)
}

// GetMaxSeverityForUser mocks base method.
func (m *MockSecurityRepositoryInterface) GetMaxSeverityForUser(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxSeverityForUser", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxSeverityForUser indicates an expected call of GetMaxSeverityForUser.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) GetMaxSeverityForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxSeverityForUser", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).GetMaxSeverityForUser), ctx, userID)
}

// InsertIPBlock mocks base method.
func (m *MockSecurityRepositoryInterface) InsertIPBlock(ctx context.Context, e *repository.IPBlacklistEntry) (*repository.IPBlacklistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertIPBlock", ctx, e)
	ret0, _ := ret[0].(*repository.IPBlacklistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertIPBlock indicates an expected call of InsertIPBlock.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) InsertIPBlock(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertIPBlock", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).InsertIPBlock), ctx, e)
}

// GetIPBlockByID mocks base method.
func (m *MockSecurityRepositoryInterface) GetIPBlockByID(ctx context.Context, blockID string) (*repository.IPBlacklistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPBlockByID", ctx, blockID)
	ret0, _ := ret[0].(*repository.IPBlacklistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPBlockByID indicates an expected call of GetIPBlockByID.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) GetIPBlockByID(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPBlockByID", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).GetIPBlockByID), ctx, blockID)
}

// GetActiveIPBlock mocks base method.
func (m *MockSecurityRepositoryInterface) GetActiveIPBlock(ctx context.Context, ipAddress string) (*repository.IPBlacklistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveIPBlock", ctx, ipAddress)
	ret0, _ := ret[0].(*repository.IPBlacklistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveIPBlock indicates an expected call of GetActiveIPBlock.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) GetActiveIPBlock(ctx, ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveIPBlock", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).GetActiveIPBlock), ctx, ipAddress)
}

// ListBlockedIPs mocks base method.
func (m *MockSecurityRepositoryInterface) ListBlockedIPs(ctx context.Context, f repository.IPBlacklistFilter) ([]*repository.IPBlacklistEntry, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlockedIPs", ctx, f)
	ret0, _ := ret[0].([]*repository.IPBlacklistEntry)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBlockedIPs indicates an expected call of ListBlockedIPs.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) ListBlockedIPs(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockedIPs", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).ListBlockedIPs), ctx, f)
}

// DeactivateIPBlock mocks base method.
func (m *MockSecurityRepositoryInterface) DeactivateIPBlock(ctx context.Context, blockID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateIPBlock", ctx, blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateIPBlock indicates an expected call of DeactivateIPBlock.
func (mr *MockSecurityRepositoryInterfaceMockRecorder) DeactivateIPBlock(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateIPBlock", reflect.TypeOf((*MockSecurityRepositoryInterface)(nil).DeactivateIPBlock), ctx, blockID)
}
